MERGE INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INVOICE_DETAIL"  tgt USING 
   ( 
    select INVOICE_DETAIL_ID,SOURCE_SYSTEM, GLOBAL_ESTIMATED_COST_AMT from "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."NETSUITE_INVOICE_DETAIL_STG"
    )stg
    ON tgt.INVOICE_DETAIL_ID = stg.INVOICE_DETAIL_ID and tgt.SOURCE_SYSTEM = stg.SOURCE_SYSTEM and tgt.LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000'
      when matched then 
       UPDATE SET 
        tgt.GLOBAL_ESTIMATED_COST_AMT = stg.GLOBAL_ESTIMATED_COST_AMT;