MERGE INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INVOICE_DETAIL" TARGET USING
        (
       	 SELECT STG1_1.INVOICE_DETAIL_KEY AS MERGE_KEY, STG1_1.* FROM "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INVOICE_DETAIL_RMS_STAGE" STG1_1
       	 UNION
       	 SELECT NULL AS MERGE_KEY, STG1_2.* FROM "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INVOICE_DETAIL_RMS_STAGE" STG1_2
        ) STG1 ON TARGET.INVOICE_DETAIL_KEY = STG1.MERGE_KEY
         WHEN MATCHED AND TARGET.LAST_EFFECTIVE_TS > '9999-12-31' THEN
       	  UPDATE SET
       		  LAST_EFFECTIVE_TS = STG1.FIRST_EFFECTIVE_TS,
       		  UPDATE_TS = STG1.UPDATE_TS
         WHEN NOT MATCHED AND MERGE_KEY IS NULL THEN
       	  INSERT (
              INVOICE_DETAIL_KEY,  
                INVOICE_DETAIL_ID,
                CONCEPT_CD,
                SOURCE_SYSTEM,
                PRIME_LINE_SEQ_NBR,
                INVOICE_KEY,
                INVOICE_ID,
                INVOICE_DT,
                ITEM_KEY,
                ITEM_ID,
                ORDER_LINE_KEY,
                ORDER_LINE_ID,
                LOCATION_KEY, 
                LOCATION_ID, 
                GLOBAL_COST_CENTER_KEY,
                GLOBAL_COST_CENTER_ID,
                GLOBAL_SUBSIDIARY_KEY,
                GLOBAL_SUBSIDIARY_ID,
                FIRST_EFFECTIVE_TS,
                LAST_EFFECTIVE_TS,
                RETAIL_TYPE_CD,
                POS_RING_TYPE_CD,
                TXN_TYPE_CD,
                TXN_SUB_TYPE_CD,
                ENTRY_METHOD,
                SLSPRSN_ID,
                INVOICE_QTY,
                INVOICE_AMT,
                UNIT_PRICE_AMT,
                GLOBAL_ESTIMATED_COST_AMT,
                TXN_SIGN,
                TAXABLE_FLAG,                
                ORIG_TXN_NBR,
                ORIG_UNIT_PRICE_AMT,
                ORIG_TXN_SIGN_CD,
                REASON_ID,
                RETURN_REASON_ID,
                DROP_SHIP_FLAG,
                ACTUAL_SHIP_DT,
                WEIGHTED_AVG_COST,
                LABOR_COST,
                LABOR_SKU,
                VENDOR_COST,
                PO_EXPENSES,
                PO_DUTY,
                FULFILLMENT_STATUS_ID,
                DISCOUNT_RATE_AMT,
                ELC_AGENT_COMMISSION_AMT,
                ELC_HTS_AMT,
                ELC_FREIGHT_AMT,
                ELC_MISC_AMT,
                FIRST_COST_AMT,
                PACK_GROUP_NBR,
                COMMITTED_QTY,
                CLOSED_DT,
                INSERT_TS,
                UPDATE_TS 
       	      ) VALUES (
                 STG1.INVOICE_DETAIL_KEY,
                 STG1.INVOICE_DETAIL_ID,
                 STG1.CONCEPT_CD,
                 STG1.SOURCE_SYSTEM,
                 STG1.PRIME_LINE_SEQ_NBR,
                 STG1.INVOICE_KEY,
                 STG1.INVOICE_ID,
                 STG1.INVOICE_DT,
                 STG1.ITEM_KEY,
                 STG1.ITEM_ID,
                 STG1.ORDER_LINE_KEY,
                 STG1.ORDER_LINE_ID,
                 STG1.LOCATION_KEY, 
                 STG1.LOCATION_ID, 
                 STG1.GLOBAL_COST_CENTER_KEY,
                 STG1.GLOBAL_COST_CENTER_ID,
                 STG1.GLOBAL_SUBSIDIARY_KEY,
                 STG1.GLOBAL_SUBSIDIARY_ID,
                 STG1.FIRST_EFFECTIVE_TS,
                 STG1.LAST_EFFECTIVE_TS,
                 STG1.RETAIL_TYPE_CD,
                 STG1.POS_RING_TYPE_CD ,
                 STG1.TXN_TYPE_CD ,
                 STG1.TXN_SUB_TYPE_CD ,
                 STG1.ENTRY_METHOD,
                 STG1.SLSPRSN_ID,
                 STG1.INVOICE_QTY,
                 STG1.INVOICE_AMT,
                 STG1.UNIT_PRICE_AMT,
                 null,
                 STG1.TXN_SIGN,
                 STG1.TAXABLE_FLAG, 
                 STG1.ORIG_TXN_NBR,
                 STG1.ORIG_UNIT_PRICE_AMT,
                 STG1.ORIG_TXN_SIGN_CD,
                 STG1.REASON_ID,
                 STG1.RETURN_REASON_ID,
                 STG1.DROP_SHIP_FLAG,
                 STG1.ACTUAL_SHIP_DT,
                 STG1.WEIGHTED_AVG_COST,
                 STG1.LABOR_COST,
                 STG1.LABOR_SKU,
                 STG1.VENDOR_COST,
                 STG1.PO_EXPENSES,
                 STG1.PO_DUTY,
                 STG1.FULFILLMENT_STATUS_ID,
                 STG1.DISCOUNT_RATE_AMT,
                 STG1.ELC_AGENT_COMMISSION_AMT,
                 STG1.ELC_HTS_AMT,
                 STG1.ELC_FREIGHT_AMT,
                 STG1.ELC_MISC_AMT,
                 STG1.FIRST_COST_AMT,
                 STG1.PACK_GROUP_NBR,
                 STG1.COMMITTED_QTY,
                 STG1.CLOSED_DT,
                 STG1.INSERT_TS,
                 STG1.UPDATE_TS
       	      );