-- Databricks notebook source
-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/locationItemInvFcstAgg/locationItemInvFcstAgg_FL_transform_l1_l2.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/locationItemInvFcstAgg/bkp_05232022/locationItemInvFcstAgg_FL_transform_l1_l2.json',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/locationItemInvFcstAgg/locationItemInvFcstAgg_IL_transform_l1_l2.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/locationItemInvFcstAgg/bkp_05232022/locationItemInvFcstAgg_IL_transform_l1_l2.json',True);

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/locationItemInvFcstAgg/locationItemInvFcstAgg_IL_merge_into_sf.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/locationItemInvFcstAgg/bkp_05232022/locationItemInvFcstAgg_IL_merge_into_sf.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/locationItemInvFcstAgg/locationItemInvFcstAgg_merge_into_ndp.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/locationItemInvFcstAgg/bkp_05232022/locationItemInvFcstAgg_merge_into_ndp.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/locationItemInvFcstAgg/locationItemInvFcstAgg_surrogate_key_gen.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/locationItemInvFcstAgg/bkp_05232022/locationItemInvFcstAgg_surrogate_key_gen.sql',True);

-- COMMAND ----------

--Upload sql files to dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/ path

-- COMMAND ----------

CREATE TABLE l2_analytics_tables.LOCATION_ITEM_INV_FCST_WEEK_AGG_20220523
 DEEP CLONE l2_analytics_tables.LOCATION_ITEM_INV_FCST_WEEK_AGG 
LOCATION 'dbfs:/mnt/data/governed/l2/bkp/bkp052022/analytics/je/locationItemInvFcstAgg_20220523'


-- COMMAND ----------

-- DBTITLE 1,Replace Stage Table

CREATE OR REPLACE TABLE `L2_STAGE`.`LOCATION_ITEM_INV_FCST_WEEK_AGG_STG` (
  `LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY` BIGINT,
  `LOCATION_ITEM_INV_FCST_WEEK_AGG_ID` STRING,
  `CONCEPT_CD` STRING,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `ITEM_NAME` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `FISCAL_WEEK_KEY` BIGINT,
  `FISCAL_WEEK_NBR` INT,
  `FISCAL_WEEK_START_DT` DATE,
  `FISCAL_WEEK_END_DT` DATE,
  `FIRST_EFFECTIVE_TS` TIMESTAMP,
  `LAST_EFFECTIVE_TS` TIMESTAMP,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `PROJECTED_STOCK_ON_HAND_QTY` DECIMAL(15,4),
  `CONSTRAINED_DEMAND_UNITS_CNT` DECIMAL(15,4),
  `EFFECTIVE_SAFETY_STOCK_UNITS_CNT` DECIMAL(15,4),
  `LOST_SALES_UNITS_CNT` DECIMAL(15,4),
  `MIN_SAFETY_STOCK_UNITS_CNT` DECIMAL(15,4),
  `MODEL_STOCK_UNITS_CNT` DECIMAL(15,4),
  `PRE_AUTHORIZED_ORDER_CNT` DECIMAL(15,4),
  `RECOMMENDED_ORDER_UNITS_CNT` DECIMAL(15,4),
  `EXPEDITE_UNITS_CNT` DECIMAL(15,4),
  `MAX_STOCK_DAYS_CNT` DECIMAL(15,4),
  `MAX_STOCK_UNITS_CNT` DECIMAL(15,4),
  `SHORT_FALL_UNITS_CNT` DECIMAL(15,4),
  `STOCK_OUT_UNITS_CNT` DECIMAL(15,4),
  `SURPLUS_UNITS_CNT` DECIMAL(15,4),
  `RESERVED_STOCK_UNITS_CNT` DECIMAL(15,4),
  `RECOMMENDED_SAFETY_STOCK_UNITS_CNT` DECIMAL(15,4),
  `OPTIMAL_ALLOCATION_UNIT_CNT` DECIMAL(15,4),
  `DC_RESERVED_UNIT_CNT` DECIMAL(15,4),
  `ALLOCATED_IN_TRANSIT_UNIT_CNT` DECIMAL(15,4),
  `ALLOCATED_UNIT_CNT` DECIMAL(15,4),
  `PRE_ALLOCATED_UNIT_CNT` DECIMAL(15,4),
  `INSERT_TS` TIMESTAMP,
  `UPDATE_TS` TIMESTAMP)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/stage/je/locationItemInvFcstAgg_stg' ) PARTITIONED BY (UPDATE_TS) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);


-- COMMAND ----------

select count(*) from L2_ANALYTICS_TABLES.LOCATION_ITEM_INV_FCST_WEEK_AGG

-- COMMAND ----------

select count(*) from l2_analytics_tables.LOCATION_ITEM_INV_FCST_WEEK_AGG_20220523

-- COMMAND ----------

drop table  L2_ANALYTICS_TABLES.LOCATION_ITEM_INV_FCST_WEEK_AGG

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.rm('dbfs:/mnt/data/governed/l2/analytics/je/locationItemInvFcstAgg',True)

-- COMMAND ----------

-- DBTITLE 1,Replace Target Table

CREATE TABLE `L2_ANALYTICS_TABLES`.`LOCATION_ITEM_INV_FCST_WEEK_AGG` (
  `LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY` BIGINT,
  `LOCATION_ITEM_INV_FCST_WEEK_AGG_ID` STRING,
  `CONCEPT_CD` STRING,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `ITEM_NAME` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `FISCAL_WEEK_KEY` BIGINT,
  `FISCAL_WEEK_NBR` INT,
  `FISCAL_WEEK_START_DT` DATE,
  `FISCAL_WEEK_END_DT` DATE,
  `FIRST_EFFECTIVE_TS` TIMESTAMP,
  `LAST_EFFECTIVE_TS` TIMESTAMP,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `PROJECTED_STOCK_ON_HAND_QTY` DECIMAL(15,4),
  `CONSTRAINED_DEMAND_UNITS_CNT` DECIMAL(15,4),
  `EFFECTIVE_SAFETY_STOCK_UNITS_CNT` DECIMAL(15,4),
  `LOST_SALES_UNITS_CNT` DECIMAL(15,4),
  `MIN_SAFETY_STOCK_UNITS_CNT` DECIMAL(15,4),
  `MODEL_STOCK_UNITS_CNT` DECIMAL(15,4),
  `PRE_AUTHORIZED_ORDER_CNT` DECIMAL(15,4),
  `RECOMMENDED_ORDER_UNITS_CNT` DECIMAL(15,4),
  `EXPEDITE_UNITS_CNT` DECIMAL(15,4),
  `MAX_STOCK_DAYS_CNT` DECIMAL(15,4),
  `MAX_STOCK_UNITS_CNT` DECIMAL(15,4),
  `SHORT_FALL_UNITS_CNT` DECIMAL(15,4),
  `STOCK_OUT_UNITS_CNT` DECIMAL(15,4),
  `SURPLUS_UNITS_CNT` DECIMAL(15,4),
  `RESERVED_STOCK_UNITS_CNT` DECIMAL(15,4),
  `RECOMMENDED_SAFETY_STOCK_UNITS_CNT` DECIMAL(15,4),
  `OPTIMAL_ALLOCATION_UNIT_CNT` DECIMAL(15,4),
  `DC_RESERVED_UNIT_CNT` DECIMAL(15,4),
  `ALLOCATED_IN_TRANSIT_UNIT_CNT` DECIMAL(15,4),
  `ALLOCATED_UNIT_CNT` DECIMAL(15,4),
  `PRE_ALLOCATED_UNIT_CNT` DECIMAL(15,4),
  `INSERT_TS` TIMESTAMP,
  `UPDATE_TS` TIMESTAMP)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/analytics/je/locationItemInvFcstAgg' ) PARTITIONED BY (UPDATE_TS) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);


-- COMMAND ----------

-- DBTITLE 1,Confirm if reqd to execute this query...

INSERT INTO `L2_ANALYTICS_TABLES`.`LOCATION_ITEM_INV_FCST_WEEK_AGG` SELECT
  A.LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY AS LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY,
  A.LOCATION_ITEM_INV_FCST_WEEK_AGG_ID AS LOCATION_ITEM_INV_FCST_WEEK_AGG_ID,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.LOCATION_KEY AS LOCATION_KEY,
  A.LOCATION_ID AS LOCATION_ID,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.ITEM_NAME AS ITEM_NAME,
  A.MARKET_CD AS MARKET_CD,
  A.INV_FCST_ITEM_PLACEHOLDER_KEY AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  A.INV_FCST_ITEM_PLACEHOLDER_ID AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.FISCAL_WEEK_KEY AS FISCAL_WEEK_KEY,
  A.FISCAL_WEEK_NBR AS FISCAL_WEEK_NBR,
  A.FISCAL_WEEK_START_DT AS FISCAL_WEEK_START_DT,
  A.FISCAL_WEEK_END_DT AS FISCAL_WEEK_END_DT,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  A.PARENT_ITEM_PLACEHOLDER_CD AS PARENT_ITEM_PLACEHOLDER_CD,
  A.ITEM_PLACEHOLDER_DESC AS ITEM_PLACEHOLDER_DESC,
  A.ITEM_PLACEHOLDER_DEPT_DESC AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.PROJECTED_STOCK_ON_HAND_QTY AS PROJECTED_STOCK_ON_HAND_QTY,
  A.CONSTRAINED_DEMAND_UNITS_CNT AS CONSTRAINED_DEMAND_UNITS_CNT,
  A.EFFECTIVE_SAFETY_STOCK_UNITS_CNT AS EFFECTIVE_SAFETY_STOCK_UNITS_CNT,
  A.LOST_SALES_UNITS_CNT AS LOST_SALES_UNITS_CNT,
  A.MIN_SAFETY_STOCK_UNITS_CNT AS MIN_SAFETY_STOCK_UNITS_CNT,
  A.MODEL_STOCK_UNITS_CNT AS MODEL_STOCK_UNITS_CNT,
  A.PRE_AUTHORIZED_ORDER_CNT AS PRE_AUTHORIZED_ORDER_CNT,
  A.RECOMMENDED_ORDER_UNITS_CNT AS RECOMMENDED_ORDER_UNITS_CNT,
  A.EXPEDITE_UNITS_CNT AS EXPEDITE_UNITS_CNT,
  A.MAX_STOCK_DAYS_CNT AS MAX_STOCK_DAYS_CNT,
  A.MAX_STOCK_UNITS_CNT AS MAX_STOCK_UNITS_CNT,
  A.SHORT_FALL_UNITS_CNT AS SHORT_FALL_UNITS_CNT,
  A.STOCK_OUT_UNITS_CNT AS STOCK_OUT_UNITS_CNT,
  A.SURPLUS_UNITS_CNT AS SURPLUS_UNITS_CNT,
  A.RESERVED_STOCK_UNITS_CNT AS RESERVED_STOCK_UNITS_CNT,
  A.RECOMMENDED_SAFETY_STOCK_UNITS_CNT AS RECOMMENDED_SAFETY_STOCK_UNITS_CNT,
  NULL AS OPTIMAL_ALLOCATION_UNIT_CNT,
  NULL AS DC_RESERVED_UNIT_CNT,
  NULL AS ALLOCATED_IN_TRANSIT_UNIT_CNT,
  NULL AS ALLOCATED_UNIT_CNT,
  NULL AS PRE_ALLOCATED_UNIT_CNT,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
FROM l2_analytics_tables.LOCATION_ITEM_INV_FCST_WEEK_AGG_20220523 A

-- COMMAND ----------

-- DBTITLE 1,Refresh Delta Views
CREATE OR REPLACE VIEW L2_ANALYTICS.LOCATION_ITEM_INV_FCST_WEEK_AGG AS 
 select * from L2_ANALYTICS_TABLES.LOCATION_ITEM_INV_FCST_WEEK_AGG  WHERE LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000';
CREATE OR REPLACE VIEW L2_ANALYTICS.LOCATION_ITEM_INV_FCST_WEEK_AGG_HIST AS select * from L2_ANALYTICS_TABLES.LOCATION_ITEM_INV_FCST_WEEK_AGG ;

-- COMMAND ----------

-- DBTITLE 1,Snowflake
drop table "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG_STAGE"


CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG_20220523" CLONE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG";


select * from "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG_20220523"


drop table "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG"


create or replace TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG" (
	LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY NUMBER(38,0) NOT NULL,
	LOCATION_ITEM_INV_FCST_WEEK_AGG_ID VARCHAR(16777216),
	CONCEPT_CD VARCHAR(16777216),
	LOCATION_KEY NUMBER(38,0),
	LOCATION_ID VARCHAR(16777216),
	ITEM_KEY NUMBER(38,0) NOT NULL,
	ITEM_ID VARCHAR(16777216) NOT NULL,
	ITEM_NAME VARCHAR(16777216),
	MARKET_CD VARCHAR(16777216),
	INV_FCST_ITEM_PLACEHOLDER_KEY NUMBER(38,0),
	INV_FCST_ITEM_PLACEHOLDER_ID VARCHAR(16777216),
	FISCAL_WEEK_KEY NUMBER(38,0),
	FISCAL_WEEK_NBR NUMBER(38,0),
	FISCAL_WEEK_START_DT DATE,
	FISCAL_WEEK_END_DT DATE,
	FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9),
	LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	PARENT_ITEM_PLACEHOLDER_CD VARCHAR(16777216),
	ITEM_PLACEHOLDER_DESC VARCHAR(16777216),
	ITEM_PLACEHOLDER_DEPT_DESC VARCHAR(16777216),
	PROJECTED_STOCK_ON_HAND_QTY NUMBER(15,4),
	CONSTRAINED_DEMAND_UNITS_CNT NUMBER(15,4),
	EFFECTIVE_SAFETY_STOCK_UNITS_CNT NUMBER(15,4),
	LOST_SALES_UNITS_CNT NUMBER(15,4),
	MIN_SAFETY_STOCK_UNITS_CNT NUMBER(15,4),
	MODEL_STOCK_UNITS_CNT NUMBER(15,4),
	PRE_AUTHORIZED_ORDER_CNT NUMBER(15,4),
	RECOMMENDED_ORDER_UNITS_CNT NUMBER(15,4),
	EXPEDITE_UNITS_CNT NUMBER(15,4),
	MAX_STOCK_DAYS_CNT NUMBER(15,4),
	MAX_STOCK_UNITS_CNT NUMBER(15,4),
	SHORT_FALL_UNITS_CNT NUMBER(15,4),
	STOCK_OUT_UNITS_CNT NUMBER(15,4),
	SURPLUS_UNITS_CNT NUMBER(15,4),
	RESERVED_STOCK_UNITS_CNT NUMBER(15,4),
	RECOMMENDED_SAFETY_STOCK_UNITS_CNT NUMBER(15,4),
	OPTIMAL_ALLOCATION_UNIT_CNT NUMBER(15,4),
	DC_RESERVED_UNIT_CNT NUMBER(15,4),
	ALLOCATED_IN_TRANSIT_UNIT_CNT NUMBER(15,4),
	ALLOCATED_UNIT_CNT NUMBER(15,4),
	PRE_ALLOCATED_UNIT_CNT NUMBER(15,4),
	INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
);


INSERT INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG" SELECT
  A.LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY AS LOCATION_ITEM_INV_FCST_WEEK_AGG_KEY,
  A.LOCATION_ITEM_INV_FCST_WEEK_AGG_ID AS LOCATION_ITEM_INV_FCST_WEEK_AGG_ID,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.LOCATION_KEY AS LOCATION_KEY,
  A.LOCATION_ID AS LOCATION_ID,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.ITEM_NAME AS ITEM_NAME,
  A.MARKET_CD AS MARKET_CD,
  A.INV_FCST_ITEM_PLACEHOLDER_KEY AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  A.INV_FCST_ITEM_PLACEHOLDER_ID AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.FISCAL_WEEK_KEY AS FISCAL_WEEK_KEY,
  A.FISCAL_WEEK_NBR AS FISCAL_WEEK_NBR,
  A.FISCAL_WEEK_START_DT AS FISCAL_WEEK_START_DT,
  A.FISCAL_WEEK_END_DT AS FISCAL_WEEK_END_DT,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  A.PARENT_ITEM_PLACEHOLDER_CD AS PARENT_ITEM_PLACEHOLDER_CD,
  A.ITEM_PLACEHOLDER_DESC AS ITEM_PLACEHOLDER_DESC,
  A.ITEM_PLACEHOLDER_DEPT_DESC AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.PROJECTED_STOCK_ON_HAND_QTY AS PROJECTED_STOCK_ON_HAND_QTY,
  A.CONSTRAINED_DEMAND_UNITS_CNT AS CONSTRAINED_DEMAND_UNITS_CNT,
  A.EFFECTIVE_SAFETY_STOCK_UNITS_CNT AS EFFECTIVE_SAFETY_STOCK_UNITS_CNT,
  A.LOST_SALES_UNITS_CNT AS LOST_SALES_UNITS_CNT,
  A.MIN_SAFETY_STOCK_UNITS_CNT AS MIN_SAFETY_STOCK_UNITS_CNT,
  A.MODEL_STOCK_UNITS_CNT AS MODEL_STOCK_UNITS_CNT,
  A.PRE_AUTHORIZED_ORDER_CNT AS PRE_AUTHORIZED_ORDER_CNT,
  A.RECOMMENDED_ORDER_UNITS_CNT AS RECOMMENDED_ORDER_UNITS_CNT,
  A.EXPEDITE_UNITS_CNT AS EXPEDITE_UNITS_CNT,
  A.MAX_STOCK_DAYS_CNT AS MAX_STOCK_DAYS_CNT,
  A.MAX_STOCK_UNITS_CNT AS MAX_STOCK_UNITS_CNT,
  A.SHORT_FALL_UNITS_CNT AS SHORT_FALL_UNITS_CNT,
  A.STOCK_OUT_UNITS_CNT AS STOCK_OUT_UNITS_CNT,
  A.SURPLUS_UNITS_CNT AS SURPLUS_UNITS_CNT,
  A.RESERVED_STOCK_UNITS_CNT AS RESERVED_STOCK_UNITS_CNT,
  A.RECOMMENDED_SAFETY_STOCK_UNITS_CNT AS RECOMMENDED_SAFETY_STOCK_UNITS_CNT,
  NULL AS OPTIMAL_ALLOCATION_UNIT_CNT,
  NULL AS DC_RESERVED_UNIT_CNT,
  NULL AS ALLOCATED_IN_TRANSIT_UNIT_CNT,
  NULL AS ALLOCATED_UNIT_CNT,
  NULL AS PRE_ALLOCATED_UNIT_CNT,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
FROM "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION_ITEM_INV_FCST_WEEK_AGG_20220523" A;


CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.LOCATION_ITEM_INV_FCST_WEEK_AGG AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.LOCATION_ITEM_INV_FCST_WEEK_AGG WHERE LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';


CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.LOCATION_ITEM_INV_FCST_WEEK_AGG_HIST AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.LOCATION_ITEM_INV_FCST_WEEK_AGG ;
