SELECT 
                COALESCE(CAST(IFLIP.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY as BIGINT),-1) AS INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY,
                COALESCE(CAST(L2_LOCATION.LOCATION_KEY as BIGINT),-1) AS LOCATION_KEY,
                LPAD(TRIM(CAST(STG.LOCATION_ID AS STRING)),GREATEST(LENGTH(STG.LOCATION_ID),4),0) AS LOCATION_ID,
                TRIM(CAST(L2_LOCATION.LOCATION_DESC AS STRING)) AS LOCATION_DESC,
                TRIM(CAST(L2_LOCATION.LOCATION_TYPE_CD AS STRING)) AS LOCATION_TYPE_CD,
                TRIM(STG.CONCEPT_CD) AS CONCEPT_CD,
                COALESCE(CAST(L2_ITEM.ITEM_KEY as BIGINT),-1) AS ITEM_KEY,
                TRIM(CAST(STG.ITEM_ID AS STRING)) AS ITEM_ID,
                TRIM(L2_ITEM.MARKET_CD) AS MARKET_CD,
                COALESCE(CAST(L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_KEY as BIGINT),-1) AS INV_FCST_ITEM_PLACEHOLDER_KEY,
                TRIM(CAST(L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_ID AS STRING)) AS INV_FCST_ITEM_PLACEHOLDER_ID,
                COALESCE(CAST(L2_VIRTUAL_WH.VIRTUAL_WAREHOUSE_KEY as BIGINT),-1) AS VIRTUAL_WAREHOUSE_KEY,
                TRIM(CAST(L2_VIRTUAL_WH.VIRTUAL_WAREHOUSE_ID AS STRING)) as VIRTUAL_WAREHOUSE_ID,
                CAST(L2_VIRTUAL_WH.WAREHOUSE_NM as STRING) AS VIRTUAL_WAREHOUSE_NM,
                COALESCE(CAST(L2_VIRTUAL_WH.SHIP_NODE_KEY as BIGINT),-1) AS SHIP_NODE_KEY,
                TRIM(CAST(L2_VIRTUAL_WH.SHIP_NODE_ID AS STRING)) as SHIP_NODE_ID,
                TIMESTAMP(FROM_UNIXTIME(UNIX_TIMESTAMP(cast(STG.FIRST_EFFECTIVE_TS as STRING),'yyyyMMddHHmmss'))) AS FIRST_EFFECTIVE_TS,
                TIMESTAMP(STG.LAST_EFFECTIVE_TS) AS LAST_EFFECTIVE_TS,
                TRIM(L2_PH_ITEM.PARENT_ITEM_PLACEHOLDER_CD) AS PARENT_ITEM_PLACEHOLDER_CD,
                TRIM(L2_PH_ITEM.ITEM_PLACEHOLDER_DESC) AS ITEM_PLACEHOLDER_DESC,
                TRIM(L2_PH_ITEM.ITEM_PLACEHOLDER_DEPT_DESC) AS ITEM_PLACEHOLDER_DEPT_DESC,
                TRIM(STG.ALLOCATION_STRATEGY_CD) AS ALLOCATION_STRATEGY_CD,
                TRIM(STG.ALLOCATION_STRATEGY_TYPE_CD) AS ALLOCATION_STRATEGY_TYPE_CD,
                TRIM(STG.MATERIAL_EXCEPTIONS_DESC) AS MATERIAL_EXCEPTIONS_DESC,
                TRIM(STG.PRESENTATION_PRIORITY_DESC) AS PRESENTATION_PRIORITY_DESC,
                TRIM(STG.DEMAND_TYPE_CD) AS DEMAND_TYPE_CD,
                TRIM(STG.CURVE_ASSIGNMENT_SIZE_DESC) AS CURVE_ASSIGNMENT_SIZE_DESC,
                TRIM(STG.PRODUCT_MODEL_DESC) AS PRODUCT_MODEL_DESC,
                TRIM(STG.RETREND_METHOD_CD) AS RETREND_METHOD_CD,
                TRIM(CAST(STG.USE_RETREND_FLAG as CHAR(1))) AS USE_RETREND_FLAG,
                TRIM(STG.LOCATION_CLUSTER_SET) AS LOCATION_CLUSTER_SET,
                TRIM(STG.LOCATION_CLUSTER) AS LOCATION_CLUSTER,
                TRIM(STG.LOCATION_STRATEGY_DESC) AS LOCATION_STRATEGY_DESC,
                CAST(TRIM(STG.PRESENTATION_MAX_NBR) AS INT) AS PRESENTATION_MAX_NBR,
                CAST(TRIM(STG.MIN_STOCK_PER_SIZE_NBR) AS INT) AS MIN_STOCK_PER_SIZE_NBR,
                TRIM(CAST(STG.SITE_ELIGIBLE_FLAG as CHAR(1))) AS SITE_ELIGIBLE_FLAG,
                TRIM(STG.INVENTORY_SOURCE_SELECTION_DESC) AS INVENTORY_SOURCE_SELECTION_DESC,
                TRIM(STG.PRIORITY_SEQUENCE_DESC) AS PRIORITY_SEQUENCE_DESC,
                CAST(TRIM(STG.SELL_THROUGH_TARGET_PCT) AS DECIMAL(15,4)) AS SELL_THROUGH_TARGET_PCT,  
                TRIM(STG.SALES_CURVE_SELECTION_DESC) AS SALES_CURVE_SELECTION_DESC,
                CAST(TRIM(STG.HOLD_BACK_PCT) AS DECIMAL(15,4)) AS HOLD_BACK_PCT, 
                TRIM(STG.ALLOCATION_STATUS_DESC) AS ALLOCATION_STATUS_DESC, 
                TRIM(STG.SETTING_SOURCE_DESC) AS SETTING_SOURCE_DESC,
                TRIM(CAST(STG.ALLOW_RESERVATION_FLAG as CHAR(1))) AS ALLOW_RESERVATION_FLAG,
                TRIM(STG.SALES_PLAN_BASIS_DESC) AS SALES_PLAN_BASIS_DESC,
                TRIM(STG.TEMPORAL_PLAN_DESC) AS TEMPORAL_PLAN_DESC,
                TRIM(CAST(STG.GROUP_STRATEGY_FLAG as CHAR(1))) AS GROUP_STRATEGY_FLAG,
                CAST(TRIM(STG.STORE_EXPECTED_QTY) AS INT) AS STORE_EXPECTED_QTY,
                TIMESTAMP(STG.INSERT_TS) AS INSERT_TS,
                TIMESTAMP(STG.UPDATE_TS) AS UPDATE_TS 
                FROM  
                STG_TEMP_LOOKUP_INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY STG
                  LEFT OUTER JOIN  
                   (select VIRTUAL_WAREHOUSE_KEY,VIRTUAL_WAREHOUSE_ID,WAREHOUSE_NM,SHIP_NODE_KEY,SHIP_NODE_ID from delta.`dbfs:/mnt/data/governed/l2/analytics/wh/virtual_warehouse` where last_effective_ts like '%9999%' )L2_VIRTUAL_WH 
on TRIM(CAST(STG.LOCATION_ID AS STRING))=L2_VIRTUAL_WH.VIRTUAL_WAREHOUSE_ID 
          LEFT OUTER JOIN
          (select INV_FCST_ITEM_PLACEHOLDER_KEY,INV_FCST_ITEM_PLACEHOLDER_ID,PARENT_ITEM_PLACEHOLDER_CD,ITEM_PLACEHOLDER_DESC,ITEM_PLACEHOLDER_DEPT_DESC from  delta.`dbfs:/mnt/data/governed/l2/analytics/je/placeholderitem` where last_effective_ts='9999-12-31T23:59:59.000+0000')L2_PH_ITEM
          on TRIM(CAST(STG.ITEM_ID AS STRING))=trim(L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_ID) 
          LEFT OUTER JOIN  
    (select LOCATION_ID,LOCATION_KEY,LOCATION_DESC,LOCATION_TYPE_CD,country_cd from delta.`dbfs:/mnt/data/governed/l2/analytics/location/location` where last_effective_ts like '%9999%' )L2_LOCATION 
on LPAD(TRIM(CAST(STG.LOCATION_ID AS STRING)),GREATEST(LENGTH(STG.LOCATION_ID),4),0)=L2_LOCATION.LOCATION_ID 
 LEFT OUTER JOIN 
(select ship_node_id,ship_node_key, COUNTRY_CD from delta.`dbfs:/mnt/data/governed/l2/analytics/ship_node` where last_effective_ts like '%9999%' )L2_SHIP_NODE  
on L2_SHIP_NODE.ship_node_id=L2_VIRTUAL_WH.SHIP_NODE_ID  
LEFT OUTER JOIN   
(select item_id,item_key,market_cd from delta.`dbfs:/mnt/data/governed/l2/analytics/item/item` where last_effective_ts like '%9999%')L2_ITEM 
on TRIM(CAST(STG.ITEM_ID AS STRING))=L2_ITEM.item_id and L2_ITEM.MARKET_CD = 'USA' 
    LEFT OUTER JOIN  
(SELECT * FROM L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY where last_effective_ts like '%9999%') IFLIP 
                 ON IFLIP.ITEM_ID=TRIM(CAST(STG.ITEM_ID AS STRING))  AND   
                 IFLIP.LOCATION_ID=LPAD(TRIM(CAST(STG.LOCATION_ID AS STRING)),GREATEST(LENGTH(STG.LOCATION_ID),4),0)  AND 
                 IFLIP.CONCEPT_CD=TRIM(STG.CONCEPT_CD)