SELECT
    CASE WHEN INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY = - 1 THEN
        ROW_NUMBER() OVER (ORDER BY INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY, ITEM_ID, CONCEPT_CD, LOCATION_ID) + COALESCE(MAX_INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY, 0)
        ELSE INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY
    END AS INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY,
    LOCATION_KEY,
    LOCATION_ID,
    LOCATION_DESC,
    COALESCE(LOCATION_TYPE_CD, case when VIRTUAL_WAREHOUSE_KEY <> -1 then 'W' else null end) as LOCATION_TYPE_CD,
    CONCEPT_CD,
    ITEM_KEY,
    ITEM_ID,
    MARKET_CD,
    INV_FCST_ITEM_PLACEHOLDER_KEY,
    INV_FCST_ITEM_PLACEHOLDER_ID,
    VIRTUAL_WAREHOUSE_KEY,
    VIRTUAL_WAREHOUSE_ID,
    VIRTUAL_WAREHOUSE_NM,
    SHIP_NODE_KEY,
    SHIP_NODE_ID,
    FIRST_EFFECTIVE_TS,
    LAST_EFFECTIVE_TS,
    PARENT_ITEM_PLACEHOLDER_CD,
    ITEM_PLACEHOLDER_DESC,
    ITEM_PLACEHOLDER_DEPT_DESC,
    ALLOCATION_STRATEGY_CD,
    ALLOCATION_STRATEGY_TYPE_CD,
    MATERIAL_EXCEPTIONS_DESC,
    PRESENTATION_PRIORITY_DESC,
    DEMAND_TYPE_CD,
    CURVE_ASSIGNMENT_SIZE_DESC,
    PRODUCT_MODEL_DESC,
    RETREND_METHOD_CD,
    USE_RETREND_FLAG,
    LOCATION_CLUSTER_SET,
    LOCATION_CLUSTER,
    LOCATION_STRATEGY_DESC,
    PRESENTATION_MAX_NBR,
    MIN_STOCK_PER_SIZE_NBR,
    SITE_ELIGIBLE_FLAG,
    INVENTORY_SOURCE_SELECTION_DESC,
    PRIORITY_SEQUENCE_DESC,
    SELL_THROUGH_TARGET_PCT,  
    SALES_CURVE_SELECTION_DESC,
    HOLD_BACK_PCT, 
    ALLOCATION_STATUS_DESC, 
    SETTING_SOURCE_DESC,
    ALLOW_RESERVATION_FLAG,
    SALES_PLAN_BASIS_DESC,
    TEMPORAL_PLAN_DESC,
    GROUP_STRATEGY_FLAG,
    STORE_EXPECTED_QTY,
    INSERT_TS,
    UPDATE_TS 
 FROM STG_TEMP_INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY
 CROSS JOIN (
   SELECT
       MAX(INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY) AS MAX_INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY
   FROM
      L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY
   WHERE
      INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY <> - 1
  ) TGT_MAX