-- Databricks notebook source
-- DBTITLE 1,Upload Config
/FileStore/tables/config/je/AllocationStrategyItemSite/AllocationStrategyItemSite_dq_check.json
/FileStore/tables/config/je/AllocationStrategyItemSite/AllocationStrategyItemSite_FL_IL_config.json
/FileStore/tables/config/je/AllocationStrategyItemSite/AllocationStrategyItemSite_transform_l1_l2.json

-- COMMAND ----------

-- DBTITLE 1,Upload SQL

/FileStore/tables/sql/je/AllocationStrategyItemSite/AllocationStrategyItemSite_delete_data_fl.sql
/FileStore/tables/sql/je/AllocationStrategyItemSite/AllocationStrategyItemSite_FL_merge_into_sf.sql
/FileStore/tables/sql/je/AllocationStrategyItemSite/AllocationStrategyItemSite_IL_merge_into_sf.sql
/FileStore/tables/sql/je/AllocationStrategyItemSite/AllocationStrategyItemSite_lookup.sql
/FileStore/tables/sql/je/AllocationStrategyItemSite/AllocationStrategyItemSite_merge_into_ndp.sql
/FileStore/tables/sql/je/AllocationStrategyItemSite/AllocationStrategyItemSite_surrogate_key_gen.sql

-- COMMAND ----------

-- DBTITLE 1,Create new Target Table

CREATE TABLE `L2_ANALYTICS_TABLES`.`INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY` (
  `INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY` BIGINT NOT NULL,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `LOCATION_DESC` STRING,
  `LOCATION_TYPE_CD` STRING,
  `CONCEPT_CD` STRING NOT NULL,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `VIRTUAL_WAREHOUSE_ID` STRING,
  `VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `LAST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `ALLOCATION_STRATEGY_CD` STRING,
  `ALLOCATION_STRATEGY_TYPE_CD` STRING,
  `MATERIAL_EXCEPTIONS_DESC` STRING,
  `PRESENTATION_PRIORITY_DESC` STRING,
  `DEMAND_TYPE_CD` STRING,
  `CURVE_ASSIGNMENT_SIZE_DESC` STRING,
  `PRODUCT_MODEL_DESC` STRING,
  `RETREND_METHOD_CD` STRING,
  `USE_RETREND_FLAG` STRING,
  `LOCATION_CLUSTER_SET` STRING,
  `LOCATION_CLUSTER` STRING,
  `LOCATION_STRATEGY_DESC` STRING,
  `PRESENTATION_MAX_NBR` INT,
  `MIN_STOCK_PER_SIZE_NBR` INT,
  `SITE_ELIGIBLE_FLAG` STRING,
  `INVENTORY_SOURCE_SELECTION_DESC` STRING,
  `PRIORITY_SEQUENCE_DESC` STRING,
  `SELL_THROUGH_TARGET_PCT` DECIMAL(15,4),
  `SALES_CURVE_SELECTION_DESC` STRING,
  `HOLD_BACK_PCT` DECIMAL(15,4),
  `ALLOCATION_STATUS_DESC` STRING,
  `SETTING_SOURCE_DESC` STRING,
  `ALLOW_RESERVATION_FLAG` STRING,
  `SALES_PLAN_BASIS_DESC` STRING,
  `TEMPORAL_PLAN_DESC` STRING,
  `GROUP_STRATEGY_FLAG` STRING,
  `STORE_EXPECTED_QTY` INT,
  `INSERT_TS` TIMESTAMP NOT NULL,
  `UPDATE_TS` TIMESTAMP NOT NULL)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/analytics/je/AllocationStrategyItemSite' ) PARTITIONED BY (UPDATE_TS) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);



-- COMMAND ----------

-- DBTITLE 1,Create New Stage Table
CREATE TABLE `L2_STAGE`.`INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_STG` (
  `INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY` BIGINT NOT NULL,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `LOCATION_DESC` STRING,
  `LOCATION_TYPE_CD` STRING,
  `CONCEPT_CD` STRING NOT NULL,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `VIRTUAL_WAREHOUSE_ID` STRING,
  `VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `LAST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `ALLOCATION_STRATEGY_CD` STRING,
  `ALLOCATION_STRATEGY_TYPE_CD` STRING,
  `MATERIAL_EXCEPTIONS_DESC` STRING,
  `PRESENTATION_PRIORITY_DESC` STRING,
  `DEMAND_TYPE_CD` STRING,
  `CURVE_ASSIGNMENT_SIZE_DESC` STRING,
  `PRODUCT_MODEL_DESC` STRING,
  `RETREND_METHOD_CD` STRING,
  `USE_RETREND_FLAG` STRING,
  `LOCATION_CLUSTER_SET` STRING,
  `LOCATION_CLUSTER` STRING,
  `LOCATION_STRATEGY_DESC` STRING,
  `PRESENTATION_MAX_NBR` INT,
  `MIN_STOCK_PER_SIZE_NBR` INT,
  `SITE_ELIGIBLE_FLAG` STRING,
  `INVENTORY_SOURCE_SELECTION_DESC` STRING,
  `PRIORITY_SEQUENCE_DESC` STRING,
  `SELL_THROUGH_TARGET_PCT` DECIMAL(15,4),
  `SALES_CURVE_SELECTION_DESC` STRING,
  `HOLD_BACK_PCT` DECIMAL(15,4),
  `ALLOCATION_STATUS_DESC` STRING,
  `SETTING_SOURCE_DESC` STRING,
  `ALLOW_RESERVATION_FLAG` STRING,
  `SALES_PLAN_BASIS_DESC` STRING,
  `TEMPORAL_PLAN_DESC` STRING,
  `GROUP_STRATEGY_FLAG` STRING,
  `STORE_EXPECTED_QTY` INT,
  `INSERT_TS` TIMESTAMP NOT NULL,
  `UPDATE_TS` TIMESTAMP NOT NULL)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/stage/je/AllocationStrategyItemSite_stg' ) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true); 

-- COMMAND ----------

CREATE OR REPLACE  VIEW L2_ANALYTICS.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY
AS SELECT * FROM L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY WHERE LAST_EFFECTIVE_TS LIKE '%9999%';

CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_HIST
AS SELECT * FROM L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY;

-- COMMAND ----------

refresh  L2_ANALYTICS.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY;

-- COMMAND ----------

-- DBTITLE 1,Snowflake
create or replace TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY" (
	INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_KEY NUMBER(38,0) NOT NULL,
	LOCATION_KEY NUMBER(38,0),
	LOCATION_ID VARCHAR(16777216),
	LOCATION_DESC VARCHAR(16777216),
	LOCATION_TYPE_CD VARCHAR(16777216),
	CONCEPT_CD VARCHAR(16777216) NOT NULL,
	ITEM_KEY NUMBER(38,0),
	ITEM_ID VARCHAR(16777216),
	MARKET_CD VARCHAR(16777216),
	INV_FCST_ITEM_PLACEHOLDER_KEY NUMBER(38,0),
	INV_FCST_ITEM_PLACEHOLDER_ID VARCHAR(16777216),
	VIRTUAL_WAREHOUSE_KEY NUMBER(38,0),
	VIRTUAL_WAREHOUSE_ID VARCHAR(16777216),
	VIRTUAL_WAREHOUSE_NM VARCHAR(16777216),
	SHIP_NODE_KEY NUMBER(38,0),
	SHIP_NODE_ID VARCHAR(16777216),
	FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	PARENT_ITEM_PLACEHOLDER_CD VARCHAR(16777216),
	ITEM_PLACEHOLDER_DESC VARCHAR(16777216),
	ITEM_PLACEHOLDER_DEPT_DESC VARCHAR(16777216),
	ALLOCATION_STRATEGY_CD VARCHAR(16777216),
	ALLOCATION_STRATEGY_TYPE_CD VARCHAR(16777216),
	MATERIAL_EXCEPTIONS_DESC VARCHAR(16777216),
	PRESENTATION_PRIORITY_DESC VARCHAR(16777216),
	DEMAND_TYPE_CD VARCHAR(16777216),
	CURVE_ASSIGNMENT_SIZE_DESC VARCHAR(16777216),
	PRODUCT_MODEL_DESC VARCHAR(16777216),
	RETREND_METHOD_CD VARCHAR(16777216),
	USE_RETREND_FLAG VARCHAR(16777216),
	LOCATION_CLUSTER_SET VARCHAR(16777216),
	LOCATION_CLUSTER VARCHAR(16777216),
	LOCATION_STRATEGY_DESC VARCHAR(16777216),
	PRESENTATION_MAX_NBR NUMBER(38,0),
	MIN_STOCK_PER_SIZE_NBR NUMBER(38,0),
	SITE_ELIGIBLE_FLAG VARCHAR(16777216),
	INVENTORY_SOURCE_SELECTION_DESC VARCHAR(16777216),
	PRIORITY_SEQUENCE_DESC VARCHAR(16777216),
	SELL_THROUGH_TARGET_PCT NUMBER(15,4),
	SALES_CURVE_SELECTION_DESC VARCHAR(16777216),
	HOLD_BACK_PCT NUMBER(15,4),
	ALLOCATION_STATUS_DESC VARCHAR(16777216),
	SETTING_SOURCE_DESC VARCHAR(16777216),
	ALLOW_RESERVATION_FLAG VARCHAR(16777216),
	SALES_PLAN_BASIS_DESC VARCHAR(16777216),
	TEMPORAL_PLAN_DESC VARCHAR(16777216),
	GROUP_STRATEGY_FLAG VARCHAR(16777216),
	STORE_EXPECTED_QTY NUMBER(38,0),
	INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
);

-- COMMAND ----------

CREATE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY 
AS SELECT * FROM PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY WHERE LAST_EFFECTIVE_TS LIKE '%9999%';

CREATE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY_HIST
AS SELECT * FROM PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_ALLOC_STRATEGY;

-- COMMAND ----------

-- DBTITLE 1,INTER_SITE_PROJECTED_DEMAND
-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/InterSiteDemandItemSiteWeek/InterSiteDemandItemSiteWeek_FL_IL_config.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/InterSiteDemandItemSiteWeek/bkp_04082022/InterSiteDemandItemSiteWeek_FL_IL_config.json',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/InterSiteDemandItemSiteWeek/InterSiteDemandItemSiteWeek_transform_l1_l2.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/InterSiteDemandItemSiteWeek/bkp_04082022/InterSiteDemandItemSiteWeek_transform_l1_l2.json',True);

-- COMMAND ----------

--Upload config File in git to dbfs:/FileStore/tables/config/je/InterSiteDemandItemSiteWeek/

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/InterSiteDemandItemSiteWeek_IL_merge_into_sf.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/bkp_04082022/InterSiteDemandItemSiteWeek_IL_merge_into_sf.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/InterSiteDemandItemSiteWeek_merge_into_ndp.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/bkp_04082022/InterSiteDemandItemSiteWeek_merge_into_ndp.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/InterSiteDemandItemSiteWeek_surrogate_key_gen.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/bkp_04082022/InterSiteDemandItemSiteWeek_surrogate_key_gen.sql',True);

-- COMMAND ----------

--Upload sql files to dbfs:/FileStore/tables/sql/je/InterSiteDemandItemSiteWeek/ path

-- COMMAND ----------

CREATE TABLE l2_analytics_tables.INV_FCST_INTER_SITE_DEMAND_20220411
 DEEP CLONE l2_analytics_tables.INV_FCST_INTER_SITE_DEMAND 
LOCATION 'dbfs:/mnt/data/governed/l2/bkp/bkp042022/analytics/je/InterSiteDemandItemSiteWeek_20220411'


-- COMMAND ----------

-- DBTITLE 1,Replace Stage Table

CREATE OR REPLACE TABLE `L2_STAGE`.`INV_FCST_INTER_SITE_DEMAND_STG` (
  `INV_FCST_INTER_SITE_DEMAND_KEY` BIGINT,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `LOCATION_TYPE_CD` STRING,
  `CONCEPT_CD` STRING,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `FROM_VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `FROM_VIRTUAL_WAREHOUSE_ID` STRING,
  `FROM_VIRTUAL_WAREHOUSE_NM` STRING,
  `TO_VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `TO_VIRTUAL_WAREHOUSE_ID` STRING,
  `TO_VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP,
  `LAST_EFFECTIVE_TS` TIMESTAMP,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `ORDER_QTY` INT,
  `ORDER_DT` DATE,
  `ESTIMATED_DELIVERY_DT` DATE,
  `INSERT_TS` TIMESTAMP,
  `UPDATE_TS` TIMESTAMP)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/analytics/stage/je/InterSiteDemandItemSiteWeek_stg' ) PARTITIONED BY (UPDATE_TS) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);


-- COMMAND ----------

select count(*) from `L2_ANALYTICS_TABLES`.`INV_FCST_INTER_SITE_DEMAND`

-- COMMAND ----------

select count(*) from l2_analytics_tables.INV_FCST_INTER_SITE_DEMAND_20220411

-- COMMAND ----------

drop table `L2_ANALYTICS_TABLES`.`INV_FCST_INTER_SITE_DEMAND`

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.rm('dbfs:/mnt/data/governed/l2/analytics/je/InterSiteDemandItemSiteWeek',True)

-- COMMAND ----------

-- DBTITLE 1,Replace Target Table

CREATE TABLE `L2_ANALYTICS_TABLES`.`INV_FCST_INTER_SITE_DEMAND` (
  `INV_FCST_INTER_SITE_DEMAND_KEY` BIGINT  NOT NULL,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `LOCATION_TYPE_CD` STRING,
  `CONCEPT_CD` STRING,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `FROM_VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `FROM_VIRTUAL_WAREHOUSE_ID` STRING,
  `FROM_VIRTUAL_WAREHOUSE_NM` STRING,
  `TO_VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `TO_VIRTUAL_WAREHOUSE_ID` STRING,
  `TO_VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `LAST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `ORDER_QTY` INT,
  `ORDER_DT` DATE,
  `ESTIMATED_DELIVERY_DT` DATE,
  `INSERT_TS` TIMESTAMP NOT NULL,
  `UPDATE_TS` TIMESTAMP NOT NULL)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/analytics/je/InterSiteDemandItemSiteWeek' ) PARTITIONED BY (UPDATE_TS) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);


-- COMMAND ----------


INSERT INTO `L2_ANALYTICS_TABLES`.`INV_FCST_INTER_SITE_DEMAND` SELECT 
  A.INV_FCST_INTER_SITE_DEMAND_KEY AS INV_FCST_INTER_SITE_DEMAND_KEY,
  A.LOCATION_KEY AS LOCATION_KEY,
  LPAD(TRIM(CAST(A.LOCATION_ID AS STRING)),GREATEST(LENGTH(A.LOCATION_ID),4),0) AS LOCATION_ID,
  A.LOCATION_TYPE_CD AS LOCATION_TYPE_CD,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.MARKET_CD AS MARKET_CD,
  CAST(-1 AS BIGINT) AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  NULL AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.FROM_VIRTUAL_WAREHOUSE_KEY AS FROM_VIRTUAL_WAREHOUSE_KEY,
  A.FROM_VIRTUAL_WAREHOUSE_ID AS FROM_VIRTUAL_WAREHOUSE_ID,
  A.FROM_VIRTUAL_WAREHOUSE_NM AS FROM_VIRTUAL_WAREHOUSE_NM,
  A.TO_VIRTUAL_WAREHOUSE_KEY AS TO_VIRTUAL_WAREHOUSE_KEY,
  A.TO_VIRTUAL_WAREHOUSE_ID AS TO_VIRTUAL_WAREHOUSE_ID,
  A.TO_VIRTUAL_WAREHOUSE_NM AS TO_VIRTUAL_WAREHOUSE_NM,
  A.SHIP_NODE_KEY AS SHIP_NODE_KEY,
  A.SHIP_NODE_ID AS SHIP_NODE_ID,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  NULL AS PARENT_ITEM_PLACEHOLDER_CD,
  NULL AS ITEM_PLACEHOLDER_DESC,
  NULL AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.ORDER_QTY AS ORDER_QTY,
  A.ORDER_DT AS ORDER_DT,
  A.ESTIMATED_DELIVERY_DT AS ESTIMATED_DELIVERY_DT,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
FROM l2_analytics_tables.INV_FCST_INTER_SITE_DEMAND_20220411 A

-- COMMAND ----------

-- DBTITLE 1,Refresh Delta Views
CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_INTER_SITE_DEMAND AS 
 select * from L2_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND  WHERE LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000';
CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_INTER_SITE_DEMAND_HIST AS select * from L2_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND ;

-- COMMAND ----------

-- DBTITLE 1,Snowflake
drop table "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INV_FCST_INTER_SITE_DEMAND_STAGE"

-- COMMAND ----------

CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_INTER_SITE_DEMAND_20220411" CLONE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_INTER_SITE_DEMAND";

-- COMMAND ----------

select * from "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_INTER_SITE_DEMAND_20220411"

-- COMMAND ----------

drop table "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_INTER_SITE_DEMAND"

-- COMMAND ----------

create or replace TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_INTER_SITE_DEMAND" (
	INV_FCST_INTER_SITE_DEMAND_KEY NUMBER(38,0) NOT NULL,
	LOCATION_KEY NUMBER(38,0),
	LOCATION_ID VARCHAR(16777216),
	LOCATION_TYPE_CD VARCHAR(16777216),
	CONCEPT_CD VARCHAR(16777216) NOT NULL,
	ITEM_KEY NUMBER(38,0),
	ITEM_ID VARCHAR(16777216),
	MARKET_CD VARCHAR(16777216),
	INV_FCST_ITEM_PLACEHOLDER_KEY NUMBER(38,0),
	INV_FCST_ITEM_PLACEHOLDER_ID VARCHAR(16777216),
	FROM_VIRTUAL_WAREHOUSE_KEY NUMBER(38,0),
	FROM_VIRTUAL_WAREHOUSE_ID VARCHAR(16777216),
	FROM_VIRTUAL_WAREHOUSE_NM VARCHAR(16777216),
	TO_VIRTUAL_WAREHOUSE_KEY NUMBER(38,0),
	TO_VIRTUAL_WAREHOUSE_ID VARCHAR(16777216),
	TO_VIRTUAL_WAREHOUSE_NM VARCHAR(16777216),
	SHIP_NODE_KEY NUMBER(38,0),
	SHIP_NODE_ID VARCHAR(16777216),
	FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	PARENT_ITEM_PLACEHOLDER_CD VARCHAR(16777216),
	ITEM_PLACEHOLDER_DESC VARCHAR(16777216),
	ITEM_PLACEHOLDER_DEPT_DESC VARCHAR(16777216),
	ORDER_QTY NUMBER(38,0),
	ORDER_DT DATE,
	ESTIMATED_DELIVERY_DT DATE,
	INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
);

-- COMMAND ----------

insert into PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND SELECT 
  A.INV_FCST_INTER_SITE_DEMAND_KEY AS INV_FCST_INTER_SITE_DEMAND_KEY,
  A.LOCATION_KEY AS LOCATION_KEY,
  LPAD(TRIM(CAST(A.LOCATION_ID AS STRING)),GREATEST(LENGTH(A.LOCATION_ID),4),0) AS LOCATION_ID,
  A.LOCATION_TYPE_CD AS LOCATION_TYPE_CD,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.MARKET_CD AS MARKET_CD,
  CAST(-1 AS BIGINT) AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  NULL AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.FROM_VIRTUAL_WAREHOUSE_KEY AS FROM_VIRTUAL_WAREHOUSE_KEY,
  A.FROM_VIRTUAL_WAREHOUSE_ID AS FROM_VIRTUAL_WAREHOUSE_ID,
  A.FROM_VIRTUAL_WAREHOUSE_NM AS FROM_VIRTUAL_WAREHOUSE_NM,
  A.TO_VIRTUAL_WAREHOUSE_KEY AS TO_VIRTUAL_WAREHOUSE_KEY,
  A.TO_VIRTUAL_WAREHOUSE_ID AS TO_VIRTUAL_WAREHOUSE_ID,
  A.TO_VIRTUAL_WAREHOUSE_NM AS TO_VIRTUAL_WAREHOUSE_NM,
  A.SHIP_NODE_KEY AS SHIP_NODE_KEY,
  A.SHIP_NODE_ID AS SHIP_NODE_ID,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  NULL AS PARENT_ITEM_PLACEHOLDER_CD,
  NULL AS ITEM_PLACEHOLDER_DESC,
  NULL AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.ORDER_QTY AS ORDER_QTY,
  A.ORDER_DT AS ORDER_DT,
  A.ESTIMATED_DELIVERY_DT AS ESTIMATED_DELIVERY_DT,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS 
from "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_INTER_SITE_DEMAND_20220411" A 

-- COMMAND ----------

CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_INTER_SITE_DEMAND AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND WHERE LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';
CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_INTER_SITE_DEMAND_HIST AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND ;

-- COMMAND ----------

-- DBTITLE 1,Item Site Attr CEA
-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/ItemSiteAttributeCEA/ItemSiteAttributeCEA_FL_IL_config.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/ItemSiteAttributeCEA/bkp_04082022/ItemSiteAttributeCEA_FL_IL_config.json',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/ItemSiteAttributeCEA/ItemSiteAttributeCEA_transform_l1_l2.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/ItemSiteAttributeCEA/bkp_04082022/ItemSiteAttributeCEA_transform_l1_l2.json',True);

-- COMMAND ----------

--Upload config files to /FileStore/tables/config/je/ItemSiteAttributeCEA/

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/ItemSiteAttributeCEA/ItemSiteAttributeCEA_IL_merge_into_sf.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/ItemSiteAttributeCEA/bkp_04082022/ItemSiteAttributeCEA_IL_merge_into_sf.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/ItemSiteAttributeCEA/ItemSiteAttributeCEA_merge_into_ndp.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/ItemSiteAttributeCEA/bkp_04082022/ItemSiteAttributeCEA_merge_into_ndp.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/ItemSiteAttributeCEA/ItemSiteAttributeCEA_surrogate_key_gen.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/ItemSiteAttributeCEA/bkp_04082022/ItemSiteAttributeCEA_surrogate_key_gen.sql',True);

-- COMMAND ----------

--Upload config files to /FileStore/tables/sql/je/ItemSiteAttributeCEA/

-- COMMAND ----------

CREATE TABLE l2_analytics_tables.inv_fcst_item_site_attr_cea_20220411
 DEEP CLONE l2_analytics_tables.inv_fcst_item_site_attr_cea 
LOCATION 'dbfs:/mnt/data/governed/l2/bkp/bkp042022/analytics/je/ItemSiteAttributeCEA_20220411'


-- COMMAND ----------

select count(*) from l2_analytics_tables.inv_fcst_item_site_attr_cea_20220411

-- COMMAND ----------

select count(*) from l2_analytics_tables.inv_fcst_item_site_attr_cea

-- COMMAND ----------

drop table l2_analytics_tables.inv_fcst_item_site_attr_cea

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.rm('dbfs:/mnt/data/governed/l2/analytics/je/ItemSiteAttributeCEA',True)

-- COMMAND ----------


CREATE OR REPLACE TABLE `l2_stage`.`inv_fcst_item_site_attr_cea_stg` (
  `INV_FCST_ITEM_SITE_ATTR_CEA_KEY` BIGINT NOT NULL,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `LOCATION_TYPE_CD` STRING,
  `CONCEPT_CD` STRING NOT NULL,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `VIRTUAL_WAREHOUSE_ID` STRING,
  `VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `LAST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `ITEM_SITE_ATTR_NM` STRING,
  `ITEM_SITE_ATTR_VAL` STRING,
  `INSERT_TS` TIMESTAMP NOT NULL,
  `UPDATE_TS` TIMESTAMP NOT NULL)
USING delta
LOCATION 'dbfs:/mnt/data/governed/l2/stage/je/ItemSiteAttributeCEA_STG'


-- COMMAND ----------


CREATE TABLE `l2_analytics_tables`.`inv_fcst_item_site_attr_cea` (
  `INV_FCST_ITEM_SITE_ATTR_CEA_KEY` BIGINT NOT NULL,
  `LOCATION_KEY` BIGINT,
  `LOCATION_ID` STRING,
  `LOCATION_TYPE_CD` STRING,
  `CONCEPT_CD` STRING NOT NULL,
  `ITEM_KEY` BIGINT,
  `ITEM_ID` STRING,
  `MARKET_CD` STRING,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `VIRTUAL_WAREHOUSE_ID` STRING,
  `VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `LAST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `ITEM_SITE_ATTR_NM` STRING,
  `ITEM_SITE_ATTR_VAL` STRING,
  `INSERT_TS` TIMESTAMP NOT NULL,
  `UPDATE_TS` TIMESTAMP NOT NULL)
USING delta OPTIONS ( path 'dbfs:/mnt/data/governed/l2/analytics/je/ItemSiteAttributeCEA' ) PARTITIONED BY (UPDATE_TS) TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);


-- COMMAND ----------


INSERT INTO `l2_analytics_tables`.`inv_fcst_item_site_attr_cea` SELECT 
  A.INV_FCST_ITEM_SITE_ATTR_CEA_KEY AS INV_FCST_ITEM_SITE_ATTR_CEA_KEY,
  A.LOCATION_KEY AS LOCATION_KEY,
  LPAD(TRIM(CAST(A.LOCATION_ID AS STRING)),GREATEST(LENGTH(A.LOCATION_ID),4),0) AS LOCATION_ID,
  A.LOCATION_TYPE_CD AS LOCATION_TYPE_CD,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.MARKET_CD AS MARKET_CD,
  CAST(-1 AS BIGINT) AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  NULL AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.VIRTUAL_WAREHOUSE_KEY AS VIRTUAL_WAREHOUSE_KEY,
  A.VIRTUAL_WAREHOUSE_ID AS VIRTUAL_WAREHOUSE_ID,
  A.VIRTUAL_WAREHOUSE_NM AS VIRTUAL_WAREHOUSE_NM,
  A.SHIP_NODE_KEY AS SHIP_NODE_KEY,
  A.SHIP_NODE_ID AS SHIP_NODE_ID,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  NULL AS PARENT_ITEM_PLACEHOLDER_CD,
  NULL AS ITEM_PLACEHOLDER_DESC,
  NULL AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.ITEM_SITE_ATTR_NM AS ITEM_SITE_ATTR_NM,
  A.ITEM_SITE_ATTR_VAL AS ITEM_SITE_ATTR_VAL,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
FROM l2_analytics_tables.inv_fcst_item_site_attr_cea_20220411 A

-- COMMAND ----------

CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_ITEM_SITE_ATTR_CEA AS 
 select * from L2_ANALYTICS_TABLES.INV_FCST_ITEM_SITE_ATTR_CEA  WHERE LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000';
CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_ITEM_SITE_ATTR_CEA_HIST AS select * from L2_ANALYTICS_TABLES.INV_FCST_ITEM_SITE_ATTR_CEA ;

-- COMMAND ----------

-- DBTITLE 1,Snowflake
drop table "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA_STAGE"

-- COMMAND ----------

CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA_20220411" CLONE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA";

-- COMMAND ----------

select * from "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA_20220411"

-- COMMAND ----------

drop table "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA"

-- COMMAND ----------

create or replace TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA" (
	INV_FCST_ITEM_SITE_ATTR_CEA_KEY NUMBER(38,0) NOT NULL,
	LOCATION_KEY NUMBER(38,0),
	LOCATION_ID VARCHAR(16777216),
	LOCATION_TYPE_CD VARCHAR(16777216),
	CONCEPT_CD VARCHAR(16777216) NOT NULL,
	ITEM_KEY NUMBER(38,0),
	ITEM_ID VARCHAR(16777216),
	MARKET_CD VARCHAR(16777216),
	INV_FCST_ITEM_PLACEHOLDER_KEY NUMBER(38,0),
	INV_FCST_ITEM_PLACEHOLDER_ID VARCHAR(16777216),
	VIRTUAL_WAREHOUSE_KEY NUMBER(38,0),
	VIRTUAL_WAREHOUSE_ID VARCHAR(16777216),
	VIRTUAL_WAREHOUSE_NM VARCHAR(16777216),
	SHIP_NODE_KEY NUMBER(38,0),
	SHIP_NODE_ID VARCHAR(16777216),
	FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	PARENT_ITEM_PLACEHOLDER_CD VARCHAR(16777216),
	ITEM_PLACEHOLDER_DESC VARCHAR(16777216),
	ITEM_PLACEHOLDER_DEPT_DESC VARCHAR(16777216),
	ITEM_SITE_ATTR_NM VARCHAR(16777216),
	ITEM_SITE_ATTR_VAL VARCHAR(16777216),
	INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
);

-- COMMAND ----------

insert into PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_ITEM_SITE_ATTR_CEA SELECT 
  A.INV_FCST_ITEM_SITE_ATTR_CEA_KEY AS INV_FCST_ITEM_SITE_ATTR_CEA_KEY,
  A.LOCATION_KEY AS LOCATION_KEY,
  LPAD(TRIM(CAST(A.LOCATION_ID AS STRING)),GREATEST(LENGTH(A.LOCATION_ID),4),0) AS LOCATION_ID,
  A.LOCATION_TYPE_CD AS LOCATION_TYPE_CD,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.MARKET_CD AS MARKET_CD,
  CAST(-1 AS BIGINT) AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  NULL AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.VIRTUAL_WAREHOUSE_KEY AS VIRTUAL_WAREHOUSE_KEY,
  A.VIRTUAL_WAREHOUSE_ID AS VIRTUAL_WAREHOUSE_ID,
  A.VIRTUAL_WAREHOUSE_NM AS VIRTUAL_WAREHOUSE_NM,
  A.SHIP_NODE_KEY AS SHIP_NODE_KEY,
  A.SHIP_NODE_ID AS SHIP_NODE_ID,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  NULL AS PARENT_ITEM_PLACEHOLDER_CD,
  NULL AS ITEM_PLACEHOLDER_DESC,
  NULL AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.ITEM_SITE_ATTR_NM AS ITEM_SITE_ATTR_NM,
  A.ITEM_SITE_ATTR_VAL AS ITEM_SITE_ATTR_VAL,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
from "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_SITE_ATTR_CEA_20220411" A 

-- COMMAND ----------

-- DBTITLE 1,Views
CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_ITEM_SITE_ATTR_CEA AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_ITEM_SITE_ATTR_CEA WHERE LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';
CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_ITEM_SITE_ATTR_CEA_HIST AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_ITEM_SITE_ATTR_CEA ;

-- COMMAND ----------

-- DBTITLE 1,Item Site Group
-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/itemSiteGroup/itemSiteGroup_FL_IL_config.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/itemSiteGroup/bkp_04082022/itemSiteGroup_FL_IL_config.json',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/itemSiteGroup/itemSiteGroup_IL_transform_l1_l2.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/itemSiteGroup/bkp_04082022/itemSiteGroup_IL_transform_l1_l2.json',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/config/je/itemSiteGroup/itemSiteGroup_FL_transform_l1_l2.json',
-- MAGIC               'dbfs:/FileStore/tables/config/je/itemSiteGroup/bkp_04082022/itemSiteGroup_FL_transform_l1_l2.json',True);

-- COMMAND ----------

--Upload config json files to path dbfs:/FileStore/tables/config/je/ItemSiteAttributeCEA/

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/itemSiteGroup/itemSiteGroup_IL_merge_into_sf.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/itemSiteGroup/bkp_04082022/itemSiteGroup_IL_merge_into_sf.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/itemSiteGroup/itemSiteGroup_merge_into_ndp.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/itemSiteGroup/bkp_04082022/itemSiteGroup_merge_into_ndp.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/itemSiteGroup/itemSiteGroup_surrogate_key_gen.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/itemSiteGroup/bkp_04082022/itemSiteGroup_surrogate_key_gen.sql',True);
-- MAGIC 
-- MAGIC dbutils.fs.mv('dbfs:/FileStore/tables/sql/je/itemSiteGroup/itemSiteGroup_lookup.sql',
-- MAGIC               'dbfs:/FileStore/tables/sql/je/itemSiteGroup/bkp_04082022/itemSiteGroup_lookup.sql',True);

-- COMMAND ----------

CREATE TABLE L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP_20220411
 DEEP CLONE L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP 
LOCATION 'dbfs:/mnt/data/governed/l2/bkp/bkp042022/analytics/je/itemSiteGroup_20220411'


-- COMMAND ----------

select count(*) from l2_analytics_tables.INV_FCST_LOCATION_ITEM_GROUP_20220411

-- COMMAND ----------

select count(*) from l2_analytics_tables.INV_FCST_LOCATION_ITEM_GROUP

-- COMMAND ----------

drop table l2_analytics_tables.INV_FCST_LOCATION_ITEM_GROUP

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.rm('dbfs:/mnt/data/governed/l2/analytics/je/itemSiteGroup',True)

-- COMMAND ----------

DROP TABLE `l2_stage`.`inv_fcst_location_item_group_stg`

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.fs.rm('dbfs:/user/hive/warehouse/databases/L2_STAGE.db/inv_fcst_location_item_group_stg',True)

-- COMMAND ----------


CREATE TABLE `l2_analytics_tables`.`inv_fcst_location_item_group` (
  `INV_FCST_LOCATION_ITEM_GROUP_KEY` BIGINT NOT NULL,
  `CONCEPT_CD` STRING NOT NULL,
  `LOCATION_KEY` BIGINT NOT NULL,
  `LOCATION_ID` STRING NOT NULL,
  `ITEM_KEY` BIGINT NOT NULL,
  `ITEM_ID` STRING NOT NULL,
  `MARKET_CD` STRING NOT NULL,
  `INV_FCST_ITEM_PLACEHOLDER_KEY` BIGINT,
  `INV_FCST_ITEM_PLACEHOLDER_ID` STRING,
  `VIRTUAL_WAREHOUSE_KEY` BIGINT,
  `VIRTUAL_WAREHOUSE_ID` STRING,
  `VIRTUAL_WAREHOUSE_NM` STRING,
  `SHIP_NODE_KEY` BIGINT,
  `SHIP_NODE_ID` STRING,
  `FIRST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `LAST_EFFECTIVE_TS` TIMESTAMP NOT NULL,
  `PARENT_ITEM_PLACEHOLDER_CD` STRING,
  `ITEM_PLACEHOLDER_DESC` STRING,
  `ITEM_PLACEHOLDER_DEPT_DESC` STRING,
  `INV_GROUP_NM` STRING,
  `INV_GROUP_VAL` STRING,
  `INSERT_TS` TIMESTAMP NOT NULL,
  `UPDATE_TS` TIMESTAMP NOT NULL)
USING delta
PARTITIONED BY (UPDATE_TS)
LOCATION 'dbfs:/mnt/data/governed/l2/analytics/je/itemSiteGroup'


-- COMMAND ----------


INSERT INTO `L2_ANALYTICS_TABLES`.`inv_fcst_location_item_group` SELECT 
  A.INV_FCST_LOCATION_ITEM_GROUP_KEY AS INV_FCST_LOCATION_ITEM_GROUP_KEY,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.LOCATION_KEY AS LOCATION_KEY,
  LPAD(TRIM(CAST(A.LOCATION_ID AS STRING)),GREATEST(LENGTH(A.LOCATION_ID),4),0) AS LOCATION_ID,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.MARKET_CD AS MARKET_CD,
  L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_KEY AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_ID AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.VIRTUAL_WAREHOUSE_KEY AS VIRTUAL_WAREHOUSE_KEY,
  A.VIRTUAL_WAREHOUSE_ID AS VIRTUAL_WAREHOUSE_ID,
  A.VIRTUAL_WAREHOUSE_NM AS VIRTUAL_WAREHOUSE_NM,
  A.SHIP_NODE_KEY AS SHIP_NODE_KEY,
  A.SHIP_NODE_ID AS SHIP_NODE_ID,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  L2_PH_ITEM.PARENT_ITEM_PLACEHOLDER_CD AS PARENT_ITEM_PLACEHOLDER_CD,
  L2_PH_ITEM.ITEM_PLACEHOLDER_DESC AS ITEM_PLACEHOLDER_DESC,
  L2_PH_ITEM.ITEM_PLACEHOLDER_DEPT_DESC AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.INV_GROUP_NM AS INV_GROUP_NM,
  A.INV_GROUP_VAL AS INV_GROUP_VAL,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
FROM L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP_20220411 A
LEFT OUTER JOIN
(select INV_FCST_ITEM_PLACEHOLDER_KEY,INV_FCST_ITEM_PLACEHOLDER_ID,PARENT_ITEM_PLACEHOLDER_CD,ITEM_PLACEHOLDER_DESC,ITEM_PLACEHOLDER_DEPT_DESC from  delta.`dbfs:/mnt/data/governed/l2/analytics/je/placeholderitem` where last_effective_ts='9999-12-31T23:59:59.000+0000')L2_PH_ITEM 
on TRIM(CAST(A.ITEM_ID AS STRING))=trim(L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_ID)  

-- COMMAND ----------

CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_LOCATION_ITEM_GROUP AS 
 select * from L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP  WHERE LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000';
CREATE OR REPLACE VIEW L2_ANALYTICS.INV_FCST_LOCATION_ITEM_GROUP_HIST AS select * from L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP ;

-- COMMAND ----------

-- DBTITLE 1,Snowflake
drop table "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INV_FCST_LOCATION_ITEM_GROUP_STAGE"

-- COMMAND ----------

CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP_20220411" CLONE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP";

-- COMMAND ----------

select count(*) from  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP_20220411" 
select count(*) from  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP" 

-- COMMAND ----------

drop table "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP" 

-- COMMAND ----------

create or replace TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP"  (
	INV_FCST_LOCATION_ITEM_GROUP_KEY NUMBER(38,0) NOT NULL,
	CONCEPT_CD VARCHAR(16777216) NOT NULL,
	LOCATION_KEY NUMBER(38,0) NOT NULL,
	LOCATION_ID VARCHAR(16777216) NOT NULL,
	ITEM_KEY NUMBER(38,0) NOT NULL,
	ITEM_ID VARCHAR(16777216) NOT NULL,
	MARKET_CD VARCHAR(16777216),
	INV_FCST_ITEM_PLACEHOLDER_KEY NUMBER(38,0),
	INV_FCST_ITEM_PLACEHOLDER_ID VARCHAR(16777216),
	VIRTUAL_WAREHOUSE_KEY NUMBER(38,0),
	VIRTUAL_WAREHOUSE_ID VARCHAR(16777216),
	VIRTUAL_WAREHOUSE_NM VARCHAR(16777216),
	SHIP_NODE_KEY NUMBER(38,0),
	SHIP_NODE_ID VARCHAR(16777216),
	FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
	PARENT_ITEM_PLACEHOLDER_CD VARCHAR(16777216),
	ITEM_PLACEHOLDER_DESC VARCHAR(16777216),
	ITEM_PLACEHOLDER_DEPT_DESC VARCHAR(16777216),
	INV_GROUP_NM VARCHAR(16777216),
	INV_GROUP_VAL VARCHAR(16777216),
	INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
	UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
);

-- COMMAND ----------


insert into "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP" SELECT 
  A.INV_FCST_LOCATION_ITEM_GROUP_KEY AS INV_FCST_LOCATION_ITEM_GROUP_KEY,
  A.CONCEPT_CD AS CONCEPT_CD,
  A.LOCATION_KEY AS LOCATION_KEY,
  LPAD(TRIM(CAST(A.LOCATION_ID AS STRING)),GREATEST(LENGTH(A.LOCATION_ID),4),0) AS LOCATION_ID,
  A.ITEM_KEY AS ITEM_KEY,
  A.ITEM_ID AS ITEM_ID,
  A.MARKET_CD AS MARKET_CD,
  L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_KEY AS INV_FCST_ITEM_PLACEHOLDER_KEY,
  L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_ID AS INV_FCST_ITEM_PLACEHOLDER_ID,
  A.VIRTUAL_WAREHOUSE_KEY AS VIRTUAL_WAREHOUSE_KEY,
  A.VIRTUAL_WAREHOUSE_ID AS VIRTUAL_WAREHOUSE_ID,
  A.VIRTUAL_WAREHOUSE_NM AS VIRTUAL_WAREHOUSE_NM,
  A.SHIP_NODE_KEY AS SHIP_NODE_KEY,
  A.SHIP_NODE_ID AS SHIP_NODE_ID,
  A.FIRST_EFFECTIVE_TS AS FIRST_EFFECTIVE_TS,
  A.LAST_EFFECTIVE_TS AS LAST_EFFECTIVE_TS,
  L2_PH_ITEM.PARENT_ITEM_PLACEHOLDER_CD AS PARENT_ITEM_PLACEHOLDER_CD,
  L2_PH_ITEM.ITEM_PLACEHOLDER_DESC AS ITEM_PLACEHOLDER_DESC,
  L2_PH_ITEM.ITEM_PLACEHOLDER_DEPT_DESC AS ITEM_PLACEHOLDER_DEPT_DESC,
  A.INV_GROUP_NM AS INV_GROUP_NM,
  A.INV_GROUP_VAL AS INV_GROUP_VAL,
  A.INSERT_TS AS INSERT_TS,
  A.UPDATE_TS AS UPDATE_TS
FROM "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP_20220411" A
LEFT OUTER JOIN
(select INV_FCST_ITEM_PLACEHOLDER_KEY,INV_FCST_ITEM_PLACEHOLDER_ID,PARENT_ITEM_PLACEHOLDER_CD,ITEM_PLACEHOLDER_DESC,ITEM_PLACEHOLDER_DEPT_DESC from  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_ITEM_PLACEHOLDER" where last_effective_ts='9999-12-31 23:59:59.000')L2_PH_ITEM 
on TRIM(CAST(A.ITEM_ID AS STRING))=trim(L2_PH_ITEM.INV_FCST_ITEM_PLACEHOLDER_ID)


-- COMMAND ----------

CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_LOCATION_ITEM_GROUP AS 
select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP WHERE LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';

CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.INV_FCST_LOCATION_ITEM_GROUP_HIST AS select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP ;
