SELECT
    CASE WHEN GLOBAL_PO_INVOICE_LINK_KEY = 0 THEN
           ROW_NUMBER() OVER (ORDER BY ORIGINAL_PO_INVOICE_HEADER_ID,ORIGINAL_PO_INVOICE_LINE_ID,APPLIED_PO_INVOICE_ID,APPLIED_PO_INVOICE_LINE_ID,LINK_TYPE_CD,INVENTORY_NBR) + COALESCE(MAX_GLOBAL_PO_INVOICE_LINK_KEY, 0)
         ELSE GLOBAL_PO_INVOICE_LINK_KEY
    END AS GLOBAL_PO_INVOICE_LINK_KEY,
          ORIGINAL_PO_INVOICE_HEADER_KEY,
          ORIGINAL_PO_INVOICE_HEADER_ID,
          ORIGINAL_PO_INVOICE_LINE_KEY,
          ORIGINAL_PO_INVOICE_LINE_ID,
          APPLIED_PO_INVOICE_HEADER_KEY,
          APPLIED_PO_INVOICE_ID,
          APPLIED_PO_INVOICE_LINE_KEY,
          APPLIED_PO_INVOICE_LINE_ID,
          FIRST_EFFECTIVE_TS,
          LAST_EFFECTIVE_TS,
          LINKED_AMT,
          FOREIGN_LINKED_AMT,
          LINKED_QTY,
          DISCOUNT_FLAG,
          LINK_TYPE_CD,
          LINK_TYPE_DESC,
          INVENTORY_NBR,
          ORIGINAL_POSTED_DT,
          APPLIED_POSTED_DT,
          INSERT_TS,
          UPDATE_TS
 FROM STG_TEMP_GLOBAL_PO_INVOICE_LINK
 CROSS JOIN (
   SELECT
       MAX(GLOBAL_PO_INVOICE_LINK_KEY) AS MAX_GLOBAL_PO_INVOICE_LINK_KEY
   FROM
      L2_ANALYTICS_TABLES.GLOBAL_PO_INVOICE_LINK
   WHERE
      GLOBAL_PO_INVOICE_LINK_KEY <> - 1
  ) TGT_MAX