/*  
****************************************************************** 
 
** Author         : Columbia - COL-3806 
** Create Date    : February, 2020 
** Purpose        : Apply transformations 
             
****************************************************************** 
 
** Source Table   : L2_STAGE.ORDER_RTL_STG 
** Target Table   : L2_ANALYTICS_TABLES.ORDER_HEADER  
** Lookup         :  
  
** Transformations  : Load data from POSLog-Stage to Order-Header 
           
           
****************************************************************** 
************************* Change History ************************* 
****************************************************************** 
 
** Change   Date        Author    Description    
**  --      ----------  --------  -------------------------------- 
**  01      02/10/2020  COL-3806  SQL file created 
**  02		06/10/2020  COL-4170  Enhancement by hard coding source_system 
**  03      09/26/2020  VLG-583   ORIG_ORDER_ID for VPS                 
**  04      10/13/2020  COL-4482  Model Factory- Gift Receipt Flag in POSLog 
**  05      01/08/2021  COL-4480  Retail demand data in Snowflake
**  06     	04/06/2021  COL-5092  Customer_key - carryover value 
								  from previous data version 
**  07     	05/21/2021  NLE-5664  Added Membership_level_cd column as part of 
								  adding to OH from Sterling OH
** 08		06/08/2021 SEPIK      Added COLUMNS as part of adding to OH from Sterling OH

** 09       07/23/2021 SUT-160    Added Columns as part of adding to OH from Sterling OH
								  
******************************************************************  
*/  

/* 
** Source Table   : L2_ANALYTICS.ORDER_HEADER 
** Target View    : ORDER_HEADER_STG1_VIEW1 
 
** Identify subset of ORDER_HEADER for ORDER_HEADER_KEY and CDC 
** 
*/

CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_STG1_VIEW1 AS    
( 
	SELECT * FROM  
	L2_ANALYTICS.ORDER_HEADER   
	WHERE ORDER_DT IN (SELECT ORDER_DT FROM L2_STAGE.ORDER_RTL_STG  GROUP BY ORDER_DT)  
	AND SOURCE_SYSTEM IN ( 'REDIRON_POSLOG', 'NCR_POSLOG' ) 
);  


/* 
** Source Table   : L2_ANALYTICS.ORDER_HEADER 
** Target View    : ORDER_HEADER_LINK_STG1_VIEW1 
 
** Identify subset of ORDER_HEADER for deriving LINKED_ORDER_HEADER_KEY 
** 
*/

CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_LINK_STG1_VIEW1 AS    
( 
	SELECT * FROM   
	L2_ANALYTICS.ORDER_HEADER      
	WHERE ORDER_DT IN ( SELECT LINKED_ORDER_DT FROM L2_STAGE.ORDER_RTL_STG WHERE LINKED_ORDER_DT IS NOT NULL  GROUP BY LINKED_ORDER_DT)    
	AND SOURCE_SYSTEM IN ( 'REDIRON_POSLOG', 'NCR_POSLOG' )  
);  

/* 
** Source Table   : L2_ANALYTICS.ORDER_LINE 
** Target View    : ORDER_LINE_STG1_VIEW1 
 
** Identify subset of ORDER_LINE for ORDER_LINE_KEY and CDC
** 
*/

CREATE OR REPLACE TEMPORARY VIEW ORDER_LINE_STG1_VIEW1 AS    
( 
	SELECT * FROM  L2_ANALYTICS.ORDER_LINE     
	WHERE ORDER_DT IN (SELECT ORDER_DT FROM  L2_STAGE.ORDER_RTL_STG  GROUP BY ORDER_DT)    
	AND SOURCE_SYSTEM IN ( 'REDIRON_POSLOG', 'NCR_POSLOG' )  
); 	 
	
 
/* 
** Source Table   : L2_STAGE.ORDER_RTL_STG   
** Target View    : ORDER_STG1_VIEW1_PVOID 
 
** Identify POST_VOID transactions from L2_STAGE.ORDER_RTL_STG  
** 
*/

CREATE OR REPLACE TEMPORARY VIEW ORDER_STG1_VIEW1_PVOID AS    
( 
	SELECT  
		LINKED_ORDER_HEADER_ID 
	FROM L2_STAGE.ORDER_RTL_STG      
	WHERE TXN_TYPE_CD = 'POST_VOID'  
		AND LINKED_ORDER_HEADER_ID IS NOT NULL  
	GROUP BY  LINKED_ORDER_HEADER_ID   
); 


 
/* 
** Source Table   : L2_STAGE.ORDER_RTL_STG  
** Target View    : ORDER_STG1_VIEW1 
 
** Apply transformations to L2_STAGE.ORDER_RTL_STG 
** Identify CDC records for Header and Line 
** Void primary transactions in same batch ( for POST_VOID )
*/ 

CREATE OR REPLACE TEMPORARY VIEW ORDER_STG1_VIEW1 AS   
( 
	SELECT 
		COALESCE(HEADER.ORDER_HEADER_KEY, 0 ) AS ORDER_HEADER_KEY, 
		COALESCE(LINE.ORDER_LINE_KEY, 0 ) AS ORDER_LINE_KEY, 
		STG.ORDER_HEADER_ID, 
		STG.ORDER_LINE_ID,   
		STG.ORDER_DT,   
		STG.SOURCE_SYSTEM, 
		STG.LOCATION_KEY, 
		STG.LOCATION_ID, 
		STG.POS_WORKSTATION_ID, 
		STG.POS_WORKSTATION_SEQ_NBR, 
		STG.PRIME_LINE_SEQ_NBR,   
		STG.LINKED_ORDER_HEADER_ID, 
		STG.LINKED_ORDER_DT,   
		STG.CONCEPT_CD,
		STG.MARKET_CD,              /* Added as part SEPIK changes */
		CASE  
			WHEN STG_PVOID.LINKED_ORDER_HEADER_ID IS NOT NULL  THEN 'VOIDED'   
			ELSE STG.TXN_TYPE_CD  
		END AS TXN_TYPE_CD, 
		STG.CURRENCY_CD, 
		STG.ITEM_KEY, 
		STG.ORDER_ITEM_ID, 
		STG.ORDER_ITEM_TYPE_CD, 
		STG.ORDER_ITEM_NAME, 
		STG.GIFT_REGISTRY_ID, 
		STG.ORDER_LINE_TYPE, 
		STG.ORDER_QTY, 
		STG.ORIG_ORDER_QTY,     
		STG.ACT_SALE_UNIT_PRICE_AMT, 
		STG.REG_SALE_UNIT_PRICE_AMT, 
		STG.EXTENDED_AMT, 
		STG.EXTENDED_DISCOUNT_AMT, 
		STG.LINE_TAX_AMT, 
		STG.TAXABLE_AMT, 
		STG.GIFT_CARD_AMT, 
		STG.LINE_TOTAL_AMT, 
		STG.DONATION_AMT, 
		STG.ASSOCIATE_ID, 
		STG.ENTRY_METHOD, 
		STG.VOID_FLAG, 
		STG.GIFT_FLAG, 
		STG.RETURN_LINKED_ORDER_DT, 
		STG.RETURN_LINKED_ORDER_HEADER_ID, 
		STG.RETURN_ACTION_CD, 
		STG.RETURN_ACTION, 
		STG.RETURN_REASON_CD, 
		STG.RETURN_REASON_DESC, 
		STG.SHIP_TO_FIRST_NAME, 
		STG.SHIP_TO_MIDDLE_NAME, 
		STG.SHIP_TO_LAST_NAME, 
		STG.SHIP_TO_ADDRESS_LINE_1, 
		STG.SHIP_TO_ADDRESS_LINE_2, 
		STG.SHIP_TO_CITY, 
		STG.SHIP_TO_STATE_OR_PROV, 
		STG.SHIP_TO_POSTAL_CD, 
		STG.SHIP_TO_COUNTRY, 
		STG.SHIP_TO_EMAIL_ADDRESS, 
		STG.SHIP_TO_PHONE_NBR, 
		STG.LOYALTY_ACCOUNT_ID,    
		STG.BILL_TO_EMAIL_ADDRESS,    
		STG.TRADE_ID,    
		STG.OPERATOR_ID,   
		STG.CANCEL_FLAG,   
		STG.TRAINING_MODE_FLAG,    
		STG.TXN_BEGIN_TS,    
		STG.TXN_END_TS,    
		STG.RECEIPT_PREFERENCE,    
		STG.GROSS_AMT,    
		STG.NET_AMT,    
		STG.TAX_AMT,      
		STG.FIRST_EFFECTIVE_TS,  
		STG.LAST_EFFECTIVE_TS,  
		STG.INSERT_TS,    
		STG.UPDATE_TS,  
		HEADER.CUSTOMER_ID, 
		HEADER.CUSTOMER_KEY, 
		CASE  
			WHEN HEADER.ORDER_HEADER_KEY IS NULL    
			OR STG.LOCATION_KEY <> HEADER.LOCATION_KEY    
			OR STG.CONCEPT_CD <> HEADER.CONCEPT_CD    
			OR CASE WHEN STG_PVOID.LINKED_ORDER_HEADER_ID IS NOT NULL  THEN 'VOIDED'   ELSE STG.TXN_TYPE_CD END  <> HEADER.TXN_TYPE_CD      
			OR STG.CURRENCY_CD <> HEADER.CURRENCY_CD    
			OR COALESCE(STG.LINKED_ORDER_HEADER_ID, '0') <> COALESCE(HEADER.LINKED_ORDER_HEADER_ID, '0')    
			OR COALESCE(STG.BILL_TO_EMAIL_ADDRESS, '0') <> COALESCE(HEADER.BILL_TO_EMAIL_ADDRESS, '0')    
			OR COALESCE(STG.LOYALTY_ACCOUNT_ID, '0') <> COALESCE(HEADER.LOYALTY_ACCOUNT_ID, '0')    
			OR COALESCE(STG.TRADE_ID,'0') <> COALESCE(HEADER.TRADE_ID,'0')   
			OR COALESCE(STG.OPERATOR_ID, '0') <> COALESCE(HEADER.OPERATOR_ID, '0')    
			OR COALESCE(STG.CANCEL_FLAG, '0') <> COALESCE(HEADER.CANCEL_FLAG, '0')    
			OR COALESCE(STG.TRAINING_MODE_FLAG, '0') <> COALESCE(HEADER.TRAINING_MODE_FLAG, '0')    
			OR COALESCE(STG.RECEIPT_PREFERENCE, '0') <> COALESCE(HEADER.RECEIPT_PREFERENCE, '0')    
			OR COALESCE(STG.GROSS_AMT, 0.0) <> COALESCE(HEADER.GROSS_AMT, 0.0)    
			OR COALESCE(STG.NET_AMT, 0.0) <> COALESCE(HEADER.NET_AMT, 0.0)    
			OR COALESCE(STG.TAX_AMT, 0.0) <> COALESCE(HEADER.TAX_AMT, 0.0)   THEN 'I' 
			ELSE 'X' 
		END AS HEADER_INC_IND, 
		CASE  
			WHEN STG.PRIME_LINE_SEQ_NBR IS NULL OR STG.ORDER_LINE_TYPE IS NULL   THEN 'X'  
			WHEN LINE.ORDER_LINE_KEY IS NULL    
			OR HEADER.ORDER_HEADER_KEY <> LINE.ORDER_HEADER_KEY    
			OR COALESCE(STG.RETURN_LINKED_ORDER_HEADER_ID, '0') <> COALESCE(LINE.LINKED_ORDER_HEADER_ID, '0')   
			OR STG.ITEM_KEY <> LINE.ITEM_KEY    
			OR STG.ORDER_ITEM_ID <> LINE.ORDER_ITEM_ID    
			OR COALESCE( STG.ORDER_ITEM_TYPE_CD , '0' )  <>  COALESCE( LINE.ORDER_ITEM_TYPE_CD , '0' ) 
			OR COALESCE( STG.ORDER_ITEM_NAME , '0' )  <>  COALESCE( LINE.ORDER_ITEM_NAME , '0' )  
			OR COALESCE( STG.GIFT_REGISTRY_ID  ,0)  <>  COALESCE( LINE.GIFT_REGISTRY_ID  ,0)  
			OR COALESCE( STG.ORDER_LINE_TYPE  ,'0')  <>   LINE.ORDER_LINE_TYPE  
			OR COALESCE( STG.ORDER_QTY  ,0)  <>  COALESCE( LINE.ORDER_QTY  ,0)  
			OR COALESCE( STG.ACT_SALE_UNIT_PRICE_AMT  ,0.0)  <>  COALESCE( LINE.ACT_SALE_UNIT_PRICE_AMT  ,0.0)  
			OR COALESCE( STG.REG_SALE_UNIT_PRICE_AMT  ,0.0)  <>  COALESCE( LINE.REG_SALE_UNIT_PRICE_AMT  ,0.0)  
			OR COALESCE( STG.EXTENDED_AMT  ,0.0)  <>  COALESCE( LINE.EXTENDED_AMT  ,0.0)  
			OR COALESCE( STG.EXTENDED_DISCOUNT_AMT  ,0.0)  <>  COALESCE( LINE.EXTENDED_DISCOUNT_AMT  ,0.0) 
			OR COALESCE( STG.LINE_TAX_AMT  ,0.0)  <>  COALESCE( LINE.TAX_AMT  ,0.0)  
			OR COALESCE( STG.TAXABLE_AMT  ,0.0)  <>  COALESCE( LINE.TAXABLE_AMT  ,0.0)  
			OR COALESCE( STG.GIFT_CARD_AMT  ,0.0)  <>  COALESCE( LINE.GIFT_CARD_AMT  ,0.0)  
			OR COALESCE( STG.LINE_TOTAL_AMT  ,0.0)  <>  COALESCE( LINE.LINE_TOTAL_AMT  ,0.0) 
			OR COALESCE( STG.DONATION_AMT  ,0.0)  <>  COALESCE( LINE.DONATION_AMT  ,0.0) 
			OR COALESCE( STG.ASSOCIATE_ID , '0' )  <>  COALESCE( LINE.ASSOCIATE_ID , '0' ) 
			OR COALESCE( STG.ENTRY_METHOD , '0' )  <>  COALESCE( LINE.ENTRY_METHOD , '0' )  
			OR COALESCE( STG.VOID_FLAG , '0' )  <>  COALESCE( LINE.VOID_FLAG , '0' ) 
			OR COALESCE( STG.GIFT_FLAG , '0' )  <>  COALESCE( LINE.GIFT_FLAG , '0' ) 
			OR COALESCE( STG.RETURN_ACTION_CD , '0' )  <>  COALESCE( LINE.RETURN_ACTION_CD , '0' )   
			OR COALESCE( STG.RETURN_ACTION , '0' )  <>  COALESCE( LINE.RETURN_ACTION , '0' ) 
			OR COALESCE( STG.RETURN_REASON_CD , '0' )  <>  COALESCE( LINE.RETURN_REASON_CD , '0' )  
			OR COALESCE( STG.RETURN_REASON_DESC , '0' )  <>  COALESCE( LINE.RETURN_REASON_DESC , '0' )  
			OR COALESCE( STG.SHIP_TO_FIRST_NAME , '0' )  <>  COALESCE( LINE.SHIP_TO_FIRST_NAME , '0' )  
			OR COALESCE( STG.SHIP_TO_MIDDLE_NAME , '0' )  <>  COALESCE( LINE.SHIP_TO_MIDDLE_NAME , '0' ) 
			OR COALESCE( STG.SHIP_TO_LAST_NAME , '0' )  <>  COALESCE( LINE.SHIP_TO_LAST_NAME , '0' )  
			OR COALESCE( STG.SHIP_TO_ADDRESS_LINE_1 , '0' )  <>  COALESCE( LINE.SHIP_TO_ADDRESS_LINE_1 , '0' )  
			OR COALESCE( STG.SHIP_TO_ADDRESS_LINE_2 , '0' )  <>  COALESCE( LINE.SHIP_TO_ADDRESS_LINE_2 , '0' ) 
			OR COALESCE( STG.SHIP_TO_CITY , '0' )  <>  COALESCE( LINE.SHIP_TO_CITY , '0' )  
			OR COALESCE( STG.SHIP_TO_STATE_OR_PROV , '0' )  <>  COALESCE( LINE.SHIP_TO_STATE_OR_PROV , '0' ) 
			OR COALESCE( STG.SHIP_TO_POSTAL_CD , '0' )  <>  COALESCE( LINE.SHIP_TO_POSTAL_CD , '0' ) 
			OR COALESCE( STG.SHIP_TO_COUNTRY , '0' )  <>  COALESCE( LINE.SHIP_TO_COUNTRY , '0' )  
			OR COALESCE( STG.SHIP_TO_EMAIL_ADDRESS , '0' )  <>  COALESCE( LINE.SHIP_TO_EMAIL_ADDRESS , '0' ) 
			OR COALESCE( STG.SHIP_TO_PHONE_NBR , '0' )  <>  COALESCE( LINE.SHIP_TO_PHONE_NBR , '0' )    
			THEN 'I' 
			ELSE 'X' 
		END AS LINE_INC_IND 
	FROM  L2_STAGE.ORDER_RTL_STG  STG 
	LEFT OUTER JOIN  ORDER_STG1_VIEW1_PVOID STG_PVOID    
		ON  STG.ORDER_HEADER_ID = STG_PVOID.LINKED_ORDER_HEADER_ID     
	LEFT OUTER JOIN ORDER_HEADER_STG1_VIEW1  HEADER    
		ON  STG.ORDER_DT = HEADER.ORDER_DT     
		AND  STG.ORDER_HEADER_ID = HEADER.ORDER_HEADER_ID     
	LEFT OUTER JOIN ORDER_LINE_STG1_VIEW1  LINE 
		ON  STG.ORDER_DT = LINE.ORDER_DT    
		AND  STG.ORDER_LINE_ID = LINE.ORDER_LINE_ID      
); 

/* 
** Source View   : ORDER_STG1_VIEW1  
** Target View   :   ORDER_STG1_VIEW2
  
** Filter CDC records for Header and Line 
**  
*/  

CREATE OR REPLACE TEMPORARY VIEW ORDER_STG1_VIEW2 AS    
(  
	SELECT * FROM ORDER_STG1_VIEW1   
	WHERE HEADER_INC_IND= 'I' OR LINE_INC_IND = 'I' 
);  


/* 
** Source View   : ORDER_STG1_VIEW2  
** Target View   :   
  
** CACHE table ORDER_STG1_VIEW2  
**  
*/  

CACHE TABLE ORDER_STG1_VIEW2;  

/* 
** Source View   : ORDER_STG1_VIEW2  
** Target View   : ORDER_HEADER_STG1_VIEW1 
 
** Fetch only Header-CDC records and Group-By 
**  
*/ 

CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_STG1_VIEW1 AS   
(  
	SELECT  
		ORDER_HEADER_KEY, 
		ORDER_HEADER_ID, 
		ORDER_DT, 
		SOURCE_SYSTEM, 
		LOCATION_KEY, 
		LOCATION_ID, 
		POS_WORKSTATION_ID, 
		POS_WORKSTATION_SEQ_NBR, 
		LINKED_ORDER_HEADER_ID, 
		LINKED_ORDER_DT, 
		CONCEPT_CD,
		MARKET_CD,                       /* Added as part SEPIK changes */
		TXN_TYPE_CD, 
		CURRENCY_CD, 
		LOYALTY_ACCOUNT_ID, 
		BILL_TO_EMAIL_ADDRESS, 
		TRADE_ID, 
		OPERATOR_ID, 
		CANCEL_FLAG, 
		TRAINING_MODE_FLAG, 
		TXN_BEGIN_TS, 
		TXN_END_TS, 
		RECEIPT_PREFERENCE, 
		GROSS_AMT, 
		NET_AMT, 
		TAX_AMT, 
		FIRST_EFFECTIVE_TS, 
		LAST_EFFECTIVE_TS, 
		INSERT_TS, 
		UPDATE_TS, 
		CUSTOMER_ID, 
		CUSTOMER_KEY  
	FROM ORDER_STG1_VIEW2  
	WHERE HEADER_INC_IND = 'I' 
	GROUP BY  
		ORDER_HEADER_KEY, 
		ORDER_HEADER_ID, 
		ORDER_DT, 
		SOURCE_SYSTEM, 
		LOCATION_KEY, 
		LOCATION_ID, 
		POS_WORKSTATION_ID, 
		POS_WORKSTATION_SEQ_NBR, 
		LINKED_ORDER_HEADER_ID, 
		LINKED_ORDER_DT, 
		CONCEPT_CD,
		MARKET_CD,                           /* Added as part SEPIK changes */
		TXN_TYPE_CD, 
		CURRENCY_CD, 
		LOYALTY_ACCOUNT_ID, 
		BILL_TO_EMAIL_ADDRESS, 
		TRADE_ID, 
		OPERATOR_ID, 
		CANCEL_FLAG, 
		TRAINING_MODE_FLAG, 
		TXN_BEGIN_TS, 
		TXN_END_TS, 
		RECEIPT_PREFERENCE, 
		GROSS_AMT, 
		NET_AMT, 
		TAX_AMT, 
		FIRST_EFFECTIVE_TS, 
		LAST_EFFECTIVE_TS, 
		INSERT_TS,  
		UPDATE_TS,  
		CUSTOMER_ID, 
		CUSTOMER_KEY   	 
 ) ; 
 
/* 
** Source View   : ORDER_HEADER_STG1_VIEW1  
** Target View   : ORDER_HEADER_STG1_VIEW2 
 
** Surrogate key generation 
**  
*/ 

CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_STG1_VIEW2 AS   
( 
	SELECT  
		CASE  
			WHEN STG1_VIEW1.ORDER_HEADER_KEY = 0 THEN  
				ROW_NUMBER() OVER ( ORDER BY STG1_VIEW1.ORDER_HEADER_KEY, STG1_VIEW1.ORDER_HEADER_ID ) + MAX_ORDER_HEADER_KEY 
			ELSE STG1_VIEW1.ORDER_HEADER_KEY   
		END AS ORDER_HEADER_KEY,  
		STG1_VIEW1.ORDER_HEADER_ID,
		STG1_VIEW1.ORDER_DT, 
		STG1_VIEW1.SOURCE_SYSTEM, 
		STG1_VIEW1.LOCATION_KEY, 
		STG1_VIEW1.LOCATION_ID, 
		STG1_VIEW1.POS_WORKSTATION_ID, 
		STG1_VIEW1.POS_WORKSTATION_SEQ_NBR, 
		STG1_VIEW1.LINKED_ORDER_HEADER_ID, 
		STG1_VIEW1.LINKED_ORDER_DT, 
		STG1_VIEW1.CONCEPT_CD,
		STG1_VIEW1.MARKET_CD,                       /* Added as part SEPIK changes */
		STG1_VIEW1.TXN_TYPE_CD, 
		STG1_VIEW1.CURRENCY_CD, 
		STG1_VIEW1.LOYALTY_ACCOUNT_ID, 
		STG1_VIEW1.BILL_TO_EMAIL_ADDRESS, 
		STG1_VIEW1.TRADE_ID, 
		STG1_VIEW1.OPERATOR_ID, 
		STG1_VIEW1.CANCEL_FLAG, 
		STG1_VIEW1.TRAINING_MODE_FLAG, 
		STG1_VIEW1.TXN_BEGIN_TS, 
		STG1_VIEW1.TXN_END_TS, 
		STG1_VIEW1.RECEIPT_PREFERENCE, 
		STG1_VIEW1.GROSS_AMT, 
		STG1_VIEW1.NET_AMT, 
		STG1_VIEW1.TAX_AMT, 
		STG1_VIEW1.FIRST_EFFECTIVE_TS, 
		STG1_VIEW1.LAST_EFFECTIVE_TS, 
		STG1_VIEW1.INSERT_TS, 
		STG1_VIEW1.UPDATE_TS, 
		STG1_VIEW1.CUSTOMER_ID,  
		STG1_VIEW1.CUSTOMER_KEY 	  	
	FROM ORDER_HEADER_STG1_VIEW1 STG1_VIEW1 
	CROSS JOIN   
		(   
			SELECT    
				COALESCE(MAX(ORDER_HEADER_KEY),0) AS MAX_ORDER_HEADER_KEY    
			FROM L2_ANALYTICS_TABLES.ORDER_HEADER
		) HEADER_MAX   
);  



/* 
** Source View   : ORDER_HEADER_STG1_VIEW2  
** Target View   :   
  
** CACHE table ORDER_HEADER_STG1_VIEW2  
**  
*/ 

CACHE TABLE ORDER_HEADER_STG1_VIEW2;  

 
/* 
** Source View   : ORDER_HEADER_STG1_VIEW2  
** Target View   : ORDER_HEADER_STG1_VIEW3 
 
** Linked Order Header Key derivation 
** Null column mapping  
*/ 

CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_STG1_VIEW3 AS   
( 
	SELECT  
		STG1_VIEW2.ORDER_HEADER_KEY,  
		STG1_VIEW2.ORDER_HEADER_ID, 
		STG1_VIEW2.SOURCE_SYSTEM, 
		NULL AS ORDER_ID, 
		NULL AS ORIG_ORDER_ID,
		NULL AS EXCHANGE_ORDER_ID,         /* Added as part SEPIK changes */
		STG1_VIEW2.LOCATION_KEY,
		STG1_VIEW2.LOCATION_ID,
		NULL AS HOUSEHOLD_KEY,              /* Added as part SEPIK changes */
        NULL AS HOUSEHOLD_ID,               /* Added as part SEPIK changes */
		STG1_VIEW2.CONCEPT_CD, 
		NULL AS DTC_ENTRY_TYPE_CD, 
		STG1_VIEW2.TXN_TYPE_CD,
		NULL AS PAYMENT_STATUS_CD,           /* Added as part SEPIK changes */
		STG1_VIEW2.CURRENCY_CD, 
		STG1_VIEW2.LINKED_ORDER_HEADER_ID, 
		CASE   
			WHEN STG1_VIEW2.LINKED_ORDER_HEADER_ID IS NULL THEN NULL  
			ELSE COALESCE(HEADER.ORDER_HEADER_KEY, STG1_VIEW2_1.ORDER_HEADER_KEY, -1)   
		END AS LINKED_ORDER_HEADER_KEY, 
		STG1_VIEW2.POS_WORKSTATION_ID, 
		STG1_VIEW2.POS_WORKSTATION_SEQ_NBR, 
		NULL AS RTC_LOCATION_KEY,     
		NULL AS RTC_LOCATION_ID,
		STG1_VIEW2.ORDER_DT,
		STG1_VIEW2.LINKED_ORDER_DT, 
		NULL AS LOYALTY_ACCOUNT_KEY,  
		STG1_VIEW2.LOYALTY_ACCOUNT_ID,
		STG1_VIEW2.BILL_TO_EMAIL_ADDRESS,
		CAST(COALESCE(STG1_VIEW2.CUSTOMER_KEY, -1 ) AS BIGINT)  AS CUSTOMER_KEY,    
		STG1_VIEW2.CUSTOMER_ID,
		NULL AS EMPLOYEE_ID,             /* Added as part SEPIK changes */
		NULL AS MATCH_METHOD_CD,   
		STG1_VIEW2.FIRST_EFFECTIVE_TS, 
		STG1_VIEW2.LAST_EFFECTIVE_TS, 
		NULL AS BILL_TO_FIRST_NAME,   
		NULL AS BILL_TO_MIDDLE_NAME,   
		NULL AS BILL_TO_LAST_NAME,   
		NULL AS BILL_TO_ADDRESS_LINE_1,   
		NULL AS BILL_TO_ADDRESS_LINE_2,   
		NULL AS BILL_TO_CITY,   
		NULL AS BILL_TO_STATE_OR_PROV_CD,   
		NULL AS BILL_TO_POSTAL_CD,   
		NULL AS BILL_TO_COUNTRY,
		NULL AS BILL_TO_PHONE_NBR,  
		STG1_VIEW2.TRADE_ID,
		NULL AS ORDER_TYPE_CD,
		NULL AS CUSTOMER_TYPE_CD, 
		NULL AS MEMBERSHIP_LEVEL_CD,  /* Added as part Nile changes */
        NULL AS SUBORDERS_CNT,    /* SUTLEJ CHANGE */
		STG1_VIEW2.MARKET_CD,    /* Added as part SEPIK changes */
		NULL AS STORE_ORDER_SOURCE,  
		STG1_VIEW2.OPERATOR_ID,
		STG1_VIEW2.CANCEL_FLAG, 
		STG1_VIEW2.TRAINING_MODE_FLAG,
		NULL AS REGISTRY_ORDER_FLAG,        /* Added as part SEPIK changes */
        NULL AS DRAFT_ORDER_FLAG,           /* Added as part SEPIK changes */
        NULL AS ORDER_PURPOSE,              /* Added as part SEPIK changes */
        NULL AS SOURCE_CODE_DISCOUNT_AMT,      /* SUTLEJ CHANGE */										   
        NULL AS GIFTWRAP_WAIVED_FLAG,              /* SUTLEJ CHANGE */		   
        NULL AS SHIPPING_WAIVED_FLAG,              /* SUTLEJ CHANGE */										   
        NULL AS CATALOG_NM,                                  /* SUTLEJ CHANGE */							  
        NULL AS CATALOG_YEAR,                             /* SUTLEJ CHANGE */							   
        NULL AS REGISTRY_ID,                                /* SUTLEJ CHANGE */							  
        NULL AS ORDER_SOURCE_TYPE_CD,               /* SUTLEJ CHANGE */								   
        NULL AS GIFT_FLAG,                                    /* SUTLEJ CHANGE */							  
        NULL AS WAREHOUSE_SITE_CD,                    /* SUTLEJ CHANGE */								   
        NULL AS PAPER_FLAG,                                  /* SUTLEJ CHANGE */							  
        NULL AS STORE_ASSOCIATE_NM,                  /* SUTLEJ CHANGE */								   
        NULL AS TENTATIVE_REFUND_AMT,              /* SUTLEJ CHANGE */									   
        NULL AS CONTACT_FLAG,                              /* SUTLEJ CHANGE */								
        NULL AS RETURN_CARRIER,                          /* SUTLEJ CHANGE */							   
        NULL AS REGISTRY_TYPE_CD,                      /* SUTLEJ CHANGE */
		STG1_VIEW2.TXN_BEGIN_TS,
		STG1_VIEW2.TXN_END_TS,
		NULL AS RETURN_TYPE_CD,  /* Added as part SEPIK changes */
        NULL AS RETURN_DELIVERY_HUB,    /* Added as part SEPIK changes */
        NULL AS RETURN_MANAGING_HUB,  /* Added as part SEPIK changes */
        NULL AS RETURN_CARRIER_CD,  /* Added as part SEPIK changes */
        NULL AS RETURN_METHOD_CD,   /* Added as part SEPIK changes */
		STG1_VIEW2.RECEIPT_PREFERENCE, 
		STG1_VIEW2.GROSS_AMT, 
		STG1_VIEW2.NET_AMT, 
		STG1_VIEW2.TAX_AMT,
		NULL AS DOCUMENT_TYPE_CD,  /* Added as part SEPIK changes */
        NULL AS REFUND_POLICY,    /* Added as part SEPIK changes */
		STG1_VIEW2.INSERT_TS, 
		STG1_VIEW2.UPDATE_TS	 
	FROM ORDER_HEADER_STG1_VIEW2 STG1_VIEW2 
	LEFT OUTER JOIN ORDER_HEADER_STG1_VIEW2 STG1_VIEW2_1   
		ON  STG1_VIEW2.LINKED_ORDER_HEADER_ID = STG1_VIEW2_1.ORDER_HEADER_ID     
	LEFT OUTER JOIN ORDER_HEADER_LINK_STG1_VIEW1  HEADER    
		ON  STG1_VIEW2.LINKED_ORDER_DT = HEADER.ORDER_DT    
		AND  STG1_VIEW2.LINKED_ORDER_HEADER_ID = HEADER.ORDER_HEADER_ID    
	
);  

/* 
** Source View   : ORDER_HEADER_STG1_VIEW3  
** Target View   : ORDER_HEADER_STG1_VIEW3_VOID 
 
** VOID existing transaction in Header 
**   
*/ 


CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_STG1_VIEW3_VOID AS 
(   
	SELECT   
		HEADER.ORDER_HEADER_KEY AS ORDER_HEADER_KEY,   
		HEADER.ORDER_HEADER_ID,   
		HEADER.SOURCE_SYSTEM,   
		HEADER.ORDER_ID,   
		HEADER.ORIG_ORDER_ID,
		HEADER.EXCHANGE_ORDER_ID,         /* Added as part SEPIK changes */
		HEADER.LOCATION_KEY,  
		HEADER.LOCATION_ID,
		HEADER.HOUSEHOLD_KEY,              /* Added as part SEPIK changes */
		HEADER.HOUSEHOLD_ID,               /* Added as part SEPIK changes */
		HEADER.CONCEPT_CD,  
		HEADER.DTC_ENTRY_TYPE_CD, 
		'VOIDED' AS TXN_TYPE_CD,
		HEADER.PAYMENT_STATUS_CD,           /* Added as part SEPIK changes */
		HEADER.CURRENCY_CD,   
		HEADER.LINKED_ORDER_HEADER_ID,  
		HEADER.LINKED_ORDER_HEADER_KEY, 
		HEADER.POS_WORKSTATION_ID,    
		HEADER.POS_WORKSTATION_SEQ_NBR,   
		HEADER.RTC_LOCATION_KEY,   
		HEADER.RTC_LOCATION_ID,   
		HEADER.ORDER_DT,   
		NULL AS LINKED_ORDER_DT,   
		HEADER.LOYALTY_ACCOUNT_KEY,   
		HEADER.LOYALTY_ACCOUNT_ID, 
		HEADER.BILL_TO_EMAIL_ADDRESS,  
		CAST(COALESCE(HEADER.CUSTOMER_KEY, -1 ) AS BIGINT) AS CUSTOMER_KEY,   
		HEADER.CUSTOMER_ID,
		HEADER.EMPLOYEE_ID,             /* Added as part SEPIK changes */
		HEADER.MATCH_METHOD_CD,   
		STG1_VIEW3_PVOID.FIRST_EFFECTIVE_TS,   
		STG1_VIEW3_PVOID.LAST_EFFECTIVE_TS,   
		HEADER.BILL_TO_FIRST_NAME,   
		HEADER.BILL_TO_MIDDLE_NAME,   
		HEADER.BILL_TO_LAST_NAME,   
		HEADER.BILL_TO_ADDRESS_LINE_1,   
		HEADER.BILL_TO_ADDRESS_LINE_2,   
		HEADER.BILL_TO_CITY,   
		HEADER.BILL_TO_STATE_OR_PROV_CD,   
		HEADER.BILL_TO_POSTAL_CD,   
		HEADER.BILL_TO_COUNTRY,   	 
		HEADER.BILL_TO_PHONE_NBR,   
		HEADER.TRADE_ID,   
		HEADER.ORDER_TYPE_CD,   
		HEADER.CUSTOMER_TYPE_CD,
		HEADER.MEMBERSHIP_LEVEL_CD, /* Added as part Nile changes */
        HEADER.SUBORDERS_CNT,   /* SUTLEJ CHANGE */
		HEADER.MARKET_CD,    /* Added as part SEPIK changes */
		HEADER.STORE_ORDER_SOURCE,   
		HEADER.OPERATOR_ID,   
		HEADER.CANCEL_FLAG,   
		HEADER.TRAINING_MODE_FLAG,
		HEADER.REGISTRY_ORDER_FLAG,        /* Added as part SEPIK changes */
		HEADER.DRAFT_ORDER_FLAG,           /* Added as part SEPIK changes */
		HEADER.ORDER_PURPOSE,              /* Added as part SEPIK changes */
        HEADER.SOURCE_CODE_DISCOUNT_AMT,      /* SUTLEJ CHANGE */										   
        HEADER.GIFTWRAP_WAIVED_FLAG,              /* SUTLEJ CHANGE */		   
        HEADER.SHIPPING_WAIVED_FLAG,              /* SUTLEJ CHANGE */										   
        HEADER.CATALOG_NM,                                  /* SUTLEJ CHANGE */							  
        HEADER.CATALOG_YEAR,                             /* SUTLEJ CHANGE */							   
        HEADER.REGISTRY_ID,                                /* SUTLEJ CHANGE */							  
        HEADER.ORDER_SOURCE_TYPE_CD,               /* SUTLEJ CHANGE */								   
        HEADER.GIFT_FLAG,                                    /* SUTLEJ CHANGE */							  
        HEADER.WAREHOUSE_SITE_CD,                    /* SUTLEJ CHANGE */								   
        HEADER.PAPER_FLAG,                                  /* SUTLEJ CHANGE */							  
        HEADER.STORE_ASSOCIATE_NM,                  /* SUTLEJ CHANGE */								   
        HEADER.TENTATIVE_REFUND_AMT,              /* SUTLEJ CHANGE */									   
        HEADER.CONTACT_FLAG,                              /* SUTLEJ CHANGE */								
        HEADER.RETURN_CARRIER,                          /* SUTLEJ CHANGE */							   
        HEADER.REGISTRY_TYPE_CD,                      /* SUTLEJ CHANGE */
		HEADER.TXN_BEGIN_TS,   
		HEADER.TXN_END_TS,
		HEADER.RETURN_TYPE_CD,  /* Added as part SEPIK changes */
		HEADER.RETURN_DELIVERY_HUB,    /* Added as part SEPIK changes */
		HEADER.RETURN_MANAGING_HUB,  /* Added as part SEPIK changes */
		HEADER.RETURN_CARRIER_CD,  /* Added as part SEPIK changes */
		HEADER.RETURN_METHOD_CD,   /* Added as part SEPIK changes */
		HEADER.RECEIPT_PREFERENCE,
		HEADER.GROSS_AMT,   
		HEADER.NET_AMT,   
		HEADER.TAX_AMT,   
		HEADER.DOCUMENT_TYPE_CD,  /* Added as part SEPIK changes */
		HEADER.REFUND_POLICY,    /* Added as part SEPIK changes */
		STG1_VIEW3_PVOID.INSERT_TS,   
		STG1_VIEW3_PVOID.UPDATE_TS  
	FROM 
		(  
			SELECT 
				STG1_VIEW31.*  
			FROM ORDER_HEADER_STG1_VIEW3 STG1_VIEW31  
			LEFT ANTI JOIN ORDER_HEADER_STG1_VIEW3 STG1_VIEW32  
				ON STG1_VIEW31.LINKED_ORDER_HEADER_ID = STG1_VIEW32.ORDER_HEADER_ID  
			WHERE  
				STG1_VIEW31.TXN_TYPE_CD = 'POST_VOID'   
				AND STG1_VIEW31.LINKED_ORDER_HEADER_ID IS NOT NULL  
		) STG1_VIEW3_PVOID  
	LEFT OUTER JOIN ORDER_HEADER_LINK_STG1_VIEW1  HEADER  
		ON  STG1_VIEW3_PVOID.LINKED_ORDER_DT = HEADER.ORDER_DT 	
		AND STG1_VIEW3_PVOID.LINKED_ORDER_HEADER_ID = HEADER.ORDER_HEADER_ID     
	WHERE 
		HEADER.TXN_TYPE_CD <> 'VOIDED' 
		AND HEADER.ORDER_HEADER_KEY IS NOT NULL  
);


/* 
** Source View   : ORDER_HEADER_STG1_VIEW3 , ORDER_HEADER_STG1_VIEW3_VOID
** Target View   : ORDER_HEADER_STG1_VIEW4 
 
** Merge current batch and, existing/voided header data 
**   
*/ 

CREATE OR REPLACE TEMPORARY VIEW ORDER_HEADER_STG1_VIEW4 AS 
(      
	SELECT * FROM ORDER_HEADER_STG1_VIEW3  
	UNION 
	SELECT * FROM ORDER_HEADER_STG1_VIEW3_VOID 
);  
 
/* Insert overwrite to Stage table  */

INSERT OVERWRITE TABLE L2_STAGE.ORDER_RTL_HEADER_STG (select * from ORDER_HEADER_STG1_VIEW4);

/* 
** Source View   : ORDER_HEADER_STG1_VIEW4
** Target View   : L2_ANALYTICS_TABLES.ORDER_HEADER 
 
** Final Merge to Order_Header table
**   
*/ 

MERGE INTO L2_ANALYTICS_TABLES.ORDER_HEADER  HEADER USING  
(  
	SELECT STG_1.ORDER_HEADER_KEY AS MERGE_KEY, STG_1.* FROM L2_STAGE.ORDER_RTL_HEADER_STG STG_1  
	UNION  
	SELECT NULL AS MERGE_KEY, STG_2.* FROM L2_STAGE.ORDER_RTL_HEADER_STG STG_2  
) STG   
	ON  STG.ORDER_DT = HEADER.ORDER_DT   
	AND HEADER.SOURCE_SYSTEM IN ( 'REDIRON_POSLOG', 'NCR_POSLOG' )
	/* AND HEADER.ORDER_DT IN (SELECT ORDER_DT FROM L2_STAGE.ORDER_RTL_STG    GROUP BY ORDER_DT)  */ 
	AND HEADER.ORDER_HEADER_KEY = STG.MERGE_KEY  
WHEN MATCHED AND HEADER.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' THEN  
	UPDATE SET  
		LAST_EFFECTIVE_TS = FROM_UNIXTIME(CAST(STG.FIRST_EFFECTIVE_TS AS LONG) - 1),   
		UPDATE_TS = STG.UPDATE_TS   
WHEN NOT MATCHED AND MERGE_KEY IS NULL THEN  
	INSERT (  
		ORDER_HEADER_KEY,   
		ORDER_HEADER_ID,   
		SOURCE_SYSTEM,   
		ORDER_ID,  
		ORIG_ORDER_ID,
		EXCHANGE_ORDER_ID,            /* Added as part SEPIK changes */
		LOCATION_KEY,   
		LOCATION_ID,
		HOUSEHOLD_KEY,                 /* Added as part SEPIK changes */
		HOUSEHOLD_ID,                   /* Added as part SEPIK changes */
		CONCEPT_CD,  
		DTC_ENTRY_TYPE_CD, 
		TXN_TYPE_CD,
		PAYMENT_STATUS_CD,           /* Added as part SEPIK changes */
		CURRENCY_CD,   
		LINKED_ORDER_HEADER_KEY,   
		LINKED_ORDER_HEADER_ID,   
		POS_WORKSTATION_ID,   
		POS_WORKSTATION_SEQ_NBR,   
		RTC_LOCATION_KEY,   
		RTC_LOCATION_ID,   
		ORDER_DT,   
		LOYALTY_ACCOUNT_KEY,   
		LOYALTY_ACCOUNT_ID,   
		CUSTOMER_KEY,   
		CUSTOMER_ID,
		EMPLOYEE_ID,             /* Added as part SEPIK changes */
		MATCH_METHOD_CD,   
		FIRST_EFFECTIVE_TS,   
		LAST_EFFECTIVE_TS,   
		BILL_TO_FIRST_NAME, 
		BILL_TO_MIDDLE_NAME,   
		BILL_TO_LAST_NAME,  
		BILL_TO_ADDRESS_LINE_1,   
		BILL_TO_ADDRESS_LINE_2,   
		BILL_TO_CITY,  
		BILL_TO_STATE_OR_PROV_CD,   
		BILL_TO_POSTAL_CD,  
		BILL_TO_COUNTRY,  
		BILL_TO_EMAIL_ADDRESS,  
		BILL_TO_PHONE_NBR,  
		TRADE_ID,  
		ORDER_TYPE_CD,  
		CUSTOMER_TYPE_CD,
        MEMBERSHIP_LEVEL_CD,  /*Added as part Nile changes  */
        SUBORDERS_CNT,  /* SUTLEJ CHANGE */
        MARKET_CD,    /* Added as part SEPIK changes */
		STORE_ORDER_SOURCE,  
		OPERATOR_ID,  
		CANCEL_FLAG,   
		TRAINING_MODE_FLAG,
		REGISTRY_ORDER_FLAG,        /* Added as part SEPIK changes */
		DRAFT_ORDER_FLAG,           /* Added as part SEPIK changes */
		ORDER_PURPOSE,              /* Added as part SEPIK changes */
        SOURCE_CODE_DISCOUNT_AMT,      /* SUTLEJ CHANGE */										   
        GIFTWRAP_WAIVED_FLAG,              /* SUTLEJ CHANGE */		   
        SHIPPING_WAIVED_FLAG,              /* SUTLEJ CHANGE */										   
        CATALOG_NM,                                  /* SUTLEJ CHANGE */							  
        CATALOG_YEAR,                             /* SUTLEJ CHANGE */							   
        REGISTRY_ID,                                /* SUTLEJ CHANGE */							  
        ORDER_SOURCE_TYPE_CD,               /* SUTLEJ CHANGE */								   
        GIFT_FLAG,                                    /* SUTLEJ CHANGE */							  
        WAREHOUSE_SITE_CD,                    /* SUTLEJ CHANGE */								   
        PAPER_FLAG,                                  /* SUTLEJ CHANGE */							  
        STORE_ASSOCIATE_NM,                  /* SUTLEJ CHANGE */								   
        TENTATIVE_REFUND_AMT,              /* SUTLEJ CHANGE */									   
        CONTACT_FLAG,                              /* SUTLEJ CHANGE */								
        RETURN_CARRIER,                          /* SUTLEJ CHANGE */							   
        REGISTRY_TYPE_CD,                      /* SUTLEJ CHANGE */
		TXN_BEGIN_TS,  
		TXN_END_TS,
		RETURN_TYPE_CD,  /* Added as part SEPIK changes */
		RETURN_DELIVERY_HUB,    /* Added as part SEPIK changes */
		RETURN_MANAGING_HUB,  /* Added as part SEPIK changes */
		RETURN_CARRIER_CD,  /* Added as part SEPIK changes */
		RETURN_METHOD_CD,   /* Added as part SEPIK changes */
		RECEIPT_PREFERENCE,
		GROSS_AMT,  
		NET_AMT,  
		TAX_AMT,
		DOCUMENT_TYPE_CD,  /* Added as part SEPIK changes */
		REFUND_POLICY,    /* Added as part SEPIK changes */
		INSERT_TS,  
		UPDATE_TS  
	) VALUES (  
		STG.ORDER_HEADER_KEY,  
		STG.ORDER_HEADER_ID,  
		STG.SOURCE_SYSTEM,  
		STG.ORDER_ID,  
		STG.ORIG_ORDER_ID,
		STG.EXCHANGE_ORDER_ID,            /* Added as part SEPIK changes */
		STG.LOCATION_KEY,  
		STG.LOCATION_ID,
		STG.HOUSEHOLD_KEY,                 /* Added as part SEPIK changes */
		STG.HOUSEHOLD_ID,                   /* Added as part SEPIK changes */
		STG.CONCEPT_CD,  
		STG.DTC_ENTRY_TYPE_CD,
		STG.TXN_TYPE_CD,
		STG.PAYMENT_STATUS_CD,           /* Added as part SEPIK changes */
		STG.CURRENCY_CD,  
		STG.LINKED_ORDER_HEADER_KEY,   
		STG.LINKED_ORDER_HEADER_ID,  
		STG.POS_WORKSTATION_ID,  
		STG.POS_WORKSTATION_SEQ_NBR,  
		STG.RTC_LOCATION_KEY,  
		STG.RTC_LOCATION_ID,  
		STG.ORDER_DT,  
		STG.LOYALTY_ACCOUNT_KEY,  
		STG.LOYALTY_ACCOUNT_ID,  
		STG.CUSTOMER_KEY,  
		STG.CUSTOMER_ID,
		STG.EMPLOYEE_ID,             /* Added as part SEPIK changes */
		STG.MATCH_METHOD_CD,  
		STG.FIRST_EFFECTIVE_TS,  
		STG.LAST_EFFECTIVE_TS,  
		STG.BILL_TO_FIRST_NAME,  
		STG.BILL_TO_MIDDLE_NAME,  
		STG.BILL_TO_LAST_NAME,  
		STG.BILL_TO_ADDRESS_LINE_1,  
		STG.BILL_TO_ADDRESS_LINE_2,  
		STG.BILL_TO_CITY,  
		STG.BILL_TO_STATE_OR_PROV_CD,  
		STG.BILL_TO_POSTAL_CD,  
		STG.BILL_TO_COUNTRY,  
		STG.BILL_TO_EMAIL_ADDRESS,  
		STG.BILL_TO_PHONE_NBR,  
		STG.TRADE_ID,  
		STG.ORDER_TYPE_CD,  
		STG.CUSTOMER_TYPE_CD, 
		STG.MEMBERSHIP_LEVEL_CD,  /*Added as part Nile changes  */
        STG.SUBORDERS_CNT,   /* SUTLEJ CHANGE */
		STG.MARKET_CD,        /* Added as part SEPIK changes */
		STG.STORE_ORDER_SOURCE,  
		STG.OPERATOR_ID,  
		STG.CANCEL_FLAG,  
		STG.TRAINING_MODE_FLAG,
		STG.REGISTRY_ORDER_FLAG,        /* Added as part SEPIK changes */
		STG.DRAFT_ORDER_FLAG,           /* Added as part SEPIK changes */
		STG.ORDER_PURPOSE,              /* Added as part SEPIK changes */
        STG.SOURCE_CODE_DISCOUNT_AMT,      /* SUTLEJ CHANGE */										   
        STG.GIFTWRAP_WAIVED_FLAG,              /* SUTLEJ CHANGE */		   
        STG.SHIPPING_WAIVED_FLAG,              /* SUTLEJ CHANGE */										   
        STG.CATALOG_NM,                                  /* SUTLEJ CHANGE */							  
        STG.CATALOG_YEAR,                             /* SUTLEJ CHANGE */							   
        STG.REGISTRY_ID,                                /* SUTLEJ CHANGE */							  
        STG.ORDER_SOURCE_TYPE_CD,               /* SUTLEJ CHANGE */								   
        STG.GIFT_FLAG,                                    /* SUTLEJ CHANGE */							  
        STG.WAREHOUSE_SITE_CD,                    /* SUTLEJ CHANGE */								   
        STG.PAPER_FLAG,                                  /* SUTLEJ CHANGE */							  
        STG.STORE_ASSOCIATE_NM,                  /* SUTLEJ CHANGE */								   
        STG.TENTATIVE_REFUND_AMT,              /* SUTLEJ CHANGE */									   
        STG.CONTACT_FLAG,                              /* SUTLEJ CHANGE */								
        STG.RETURN_CARRIER,                          /* SUTLEJ CHANGE */							   
        STG.REGISTRY_TYPE_CD,                      /* SUTLEJ CHANGE */
		STG.TXN_BEGIN_TS,  
		STG.TXN_END_TS,
		STG.RETURN_TYPE_CD,  /* Added as part SEPIK changes */
		STG.RETURN_DELIVERY_HUB,    /* Added as part SEPIK changes */
		STG.RETURN_MANAGING_HUB,  /* Added as part SEPIK changes */
		STG.RETURN_CARRIER_CD,  /* Added as part SEPIK changes */
		STG.RETURN_METHOD_CD,   /* Added as part SEPIK changes */
		STG.RECEIPT_PREFERENCE,  
		STG.GROSS_AMT,  
		STG.NET_AMT,  
		STG.TAX_AMT,
		STG.DOCUMENT_TYPE_CD,  /* Added as part SEPIK changes */
		STG.REFUND_POLICY,    /* Added as part SEPIK changes */
		STG.INSERT_TS,  
		STG.UPDATE_TS 
	)
