-- Databricks notebook source
CUSTOMER:
DROP TABLE IF EXISTS "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."CUSTOMER_ORDER_HEADER_STG"

RJ:
DROP TABLE IF EXISTS "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."RJ_ORDER_HEADER_STG"

DROP TABLE IF EXISTS "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE"

SSP:

DROP TABLE IF EXISTS "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."ORDER_RTL_LINE_STG"

DROP TABLE IF EXISTS "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."ORDER_RTL_HEADER_STG"

DTC:

DROP TABLE IF EXISTS "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."ORDER_HEADER_STAGE"

DROP TABLE IF EXISTS "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."ORDER_LINE_STAGE"
