-- Databricks notebook source
-- DBTITLE 1,Pause following ppln triggers:
/* 
ORDER_HEADER_DMDIV_AGG_L2_SNOWFLAKE.ORDER_HEADER_DMDIV_AGG  (Completes by 11am in mrng)

a.TIMEBASED_DTC_INGEST_DECOUPLE Give advisory that 11am run will be skipped on deployment day
a.HOURLY_ORDER_POSLOG_L2
b.DAILY_OPTIMIZE_ORDER_LOC_ITM
c.DAILY_RMS_STR_SLS                                        
d.DAILY_RJ_ORDER_L1_INGEST 
e.DAILY_CUSTOMER_ORDER_HEADER_INGEST_L2_SNOWFLAKE
f.SALESFLASH_AGGREGATION (runs at midnight. If around this time, pause this)
g.DAILY_PKMS_HUB_FULFILLMENT_L1_L2_SNOWFLAKE
h.DAILY_PKMS_DC_FULFILLMENT_L1_L2_SNOWFLAKE
i. HOURLY_CHEETAH_EXTRACT (trigger name)

*/



-- COMMAND ----------

CREATE TABLE L2_ANALYTICS_TABLES.ORDER_HEADER_BKP_20210810
USING DELTA
LOCATION 'dbfs:/mnt/data/governed/l2/backup/20210810/ORDER_HEADER_bkp'
AS
SELECT * FROM L2_ANALYTICS_TABLES.ORDER_HEADER
;


-- COMMAND ----------

SELECT COUNT(*) FROM L2_ANALYTICS_TABLES.ORDER_HEADER_BKP_20210810

-- COMMAND ----------

-- MAGIC %scala
-- MAGIC spark.sql("DROP TABLE IF EXISTS L2_ANALYTICS_TABLES.ORDER_HEADER")

-- COMMAND ----------

CREATE TABLE L2_ANALYTICS_TABLES.ORDER_HEADER ( 
ORDER_HEADER_KEY INT NOT NULL
, ORDER_HEADER_ID STRING NOT NULL
, SOURCE_SYSTEM STRING NOT NULL
, ORDER_ID STRING
, ORIG_ORDER_ID STRING
, EXCHANGE_ORDER_ID STRING --SEPIK CHANGE
, ORDER_TYPE_CD STRING --SEPIK COLUMN ORDER CHANGE
, ORDER_DT DATE NOT NULL         --SEPIK COLUMN ORDER CHANGE
, LOCATION_KEY INT NOT NULL
, LOCATION_ID STRING NOT NULL
, HOUSEHOLD_KEY INT     --SEPIK CHANGE
, HOUSEHOLD_ID STRING    --SEPIK CHANGE
, DTC_ENTRY_TYPE_CD STRING
, TXN_TYPE_CD STRING NOT NULL
, PAYMENT_STATUS_CD STRING    --SEPIK CHANGE
, CONCEPT_CD STRING NOT NULL
, CURRENCY_CD STRING NOT NULL
, LINKED_ORDER_HEADER_KEY INT
, LINKED_ORDER_HEADER_ID STRING
, POS_WORKSTATION_ID STRING
, POS_WORKSTATION_SEQ_NBR INT
, RTC_LOCATION_KEY INT
, RTC_LOCATION_ID STRING
, LOYALTY_ACCOUNT_KEY INT
, LOYALTY_ACCOUNT_ID STRING    --CCR FIELD
, CUSTOMER_KEY BIGINT
, CUSTOMER_ID STRING
, EMPLOYEE_ID STRING        --SEPIK CHANGE
, MATCH_METHOD_CD STRING
, FIRST_EFFECTIVE_TS TIMESTAMP NOT NULL
, LAST_EFFECTIVE_TS TIMESTAMP NOT NULL
, BILL_TO_FIRST_NAME STRING
, BILL_TO_MIDDLE_NAME STRING
, BILL_TO_LAST_NAME STRING
, BILL_TO_ADDRESS_LINE_1 STRING
, BILL_TO_ADDRESS_LINE_2 STRING
, BILL_TO_CITY STRING
, BILL_TO_STATE_OR_PROV_CD STRING
, BILL_TO_POSTAL_CD STRING
, BILL_TO_COUNTRY STRING
, BILL_TO_EMAIL_ADDRESS STRING
, BILL_TO_PHONE_NBR STRING
, TRADE_ID STRING
, CUSTOMER_TYPE_CD STRING
, MEMBERSHIP_LEVEL_CD STRING
, SUBORDERS_CNT INT            --SUTLEJ CHANGE
, MARKET_CD STRING             --SEPIK CHANGE
, STORE_ORDER_SOURCE STRING
, OPERATOR_ID STRING
, CANCEL_FLAG STRING
, TRAINING_MODE_FLAG STRING
, REGISTRY_ORDER_FLAG STRING        --SEPIK CHANGE
, DRAFT_ORDER_FLAG STRING          --SEPIK CHANGE
, ORDER_PURPOSE STRING              --SEPIK CHANGE
, SOURCE_CODE_DISCOUNT_AMT DECIMAL(15,2)                  --SUTLEJ 																		   
, GIFTWRAP_WAIVED_FLAG STRING                             --SUTLEJ															   
, SHIPPING_WAIVED_FLAG STRING                             --SUTLEJ																 
, CATALOG_NM STRING                                       --SUTLEJ															   
, CATALOG_YEAR STRING                                     --SUTLEJ 
, REGISTRY_ID STRING                                      --SUTLEJ															   
, ORDER_SOURCE_TYPE_CD STRING                             --SUTLEJ															   
, GIFT_FLAG STRING                                        --SUTLEJ															   
, WAREHOUSE_SITE_CD STRING                                --SUTLEJ															   
, PAPER_FLAG STRING                                       --SUTLEJ															   
, STORE_ASSOCIATE_NM STRING                               --SUTLEJ															   
, TENTATIVE_REFUND_AMT STRING                             --SUTLEJ															   
, CONTACT_FLAG STRING                                     --SUTLEJ																
, RETURN_CARRIER STRING                                   --SUTLEJ															   
, REGISTRY_TYPE_CD STRING                                 --SUTLEJ
, TXN_BEGIN_TS TIMESTAMP NOT NULL
, TXN_END_TS TIMESTAMP NOT NULL
, RETURN_TYPE_CD STRING              --SEPIK CHANGE
, RETURN_DELIVERY_HUB STRING         --SEPIK CHANGE
, RETURN_MANAGING_HUB STRING         --SEPIK CHANGE
, RETURN_CARRIER_CD STRING           --SEPIK CHANGE
, RETURN_METHOD_CD STRING            --SEPIK CHANGE
, RECEIPT_PREFERENCE STRING
, GROSS_AMT DECIMAL(15,2)
, NET_AMT DECIMAL(15,2)
, TAX_AMT DECIMAL(15,2)
, DOCUMENT_TYPE_CD STRING        --SEPIK CHANGE
, REFUND_POLICY STRING            --SEPIK CHANGE
, INSERT_TS TIMESTAMP NOT NULL
, UPDATE_TS TIMESTAMP NOT NULL)  USING delta 
PARTITIONED BY (ORDER_DT, SOURCE_SYSTEM) 
LOCATION 'dbfs:/mnt/data/governed/l2/analytics/order/header'
--ok
--All null constraints added and fulfilled without deviations

-- COMMAND ----------

INSERT INTO L2_ANALYTICS_TABLES.ORDER_HEADER SELECT 
ORDER_HEADER_KEY 
, trim(ORDER_HEADER_ID) 
, SOURCE_SYSTEM 
, ORDER_ID 
, ORIG_ORDER_ID 
, EXCHANGE_ORDER_ID  
, ORDER_TYPE_CD  
, ORDER_DT          
, LOCATION_KEY 
, LOCATION_ID 
, HOUSEHOLD_KEY      
, HOUSEHOLD_ID     
, DTC_ENTRY_TYPE_CD 
, TXN_TYPE_CD 
, PAYMENT_STATUS_CD     
, CONCEPT_CD 
, CURRENCY_CD 
, LINKED_ORDER_HEADER_KEY 
, LINKED_ORDER_HEADER_ID 
, POS_WORKSTATION_ID 
, POS_WORKSTATION_SEQ_NBR 
, RTC_LOCATION_KEY 
, RTC_LOCATION_ID 
, LOYALTY_ACCOUNT_KEY 
, LOYALTY_ACCOUNT_ID --CCR CHANGE
, CUSTOMER_KEY 
, CUSTOMER_ID 
, EMPLOYEE_ID         
, MATCH_METHOD_CD 
, FIRST_EFFECTIVE_TS 
, LAST_EFFECTIVE_TS 
, BILL_TO_FIRST_NAME 
, BILL_TO_MIDDLE_NAME 
, BILL_TO_LAST_NAME 
, BILL_TO_ADDRESS_LINE_1 
, BILL_TO_ADDRESS_LINE_2 
, BILL_TO_CITY 
, BILL_TO_STATE_OR_PROV_CD 
, BILL_TO_POSTAL_CD 
, BILL_TO_COUNTRY 
, BILL_TO_EMAIL_ADDRESS 
, BILL_TO_PHONE_NBR 
, TRADE_ID 
, CUSTOMER_TYPE_CD 
, MEMBERSHIP_LEVEL_CD
, NULL AS SUBORDERS_CNT            --SUTLEJ CHANGE 
, MARKET_CD              
, STORE_ORDER_SOURCE 
, OPERATOR_ID 
, CANCEL_FLAG 
, TRAINING_MODE_FLAG 
, REGISTRY_ORDER_FLAG         
, DRAFT_ORDER_FLAG           
, ORDER_PURPOSE
,  NULL AS SOURCE_CODE_DISCOUNT_AMT                          --SUTLEJ 																		   
,  NULL AS GIFTWRAP_WAIVED_FLAG                              --SUTLEJ															   
,  NULL AS SHIPPING_WAIVED_FLAG                              --SUTLEJ																 
,  NULL AS CATALOG_NM                                        --SUTLEJ															   
,  NULL AS CATALOG_YEAR                                      --SUTLEJ 
,  NULL AS REGISTRY_ID                                       --SUTLEJ															   
,  NULL AS ORDER_SOURCE_TYPE_CD                              --SUTLEJ															   
,  NULL AS GIFT_FLAG                                         --SUTLEJ															   
,  NULL AS WAREHOUSE_SITE_CD                                 --SUTLEJ															   
,  NULL AS PAPER_FLAG                                        --SUTLEJ															   
,  NULL AS STORE_ASSOCIATE_NM                                --SUTLEJ															   
,  NULL AS TENTATIVE_REFUND_AMT                              --SUTLEJ															   
,  NULL AS CONTACT_FLAG                                      --SUTLEJ																
,  NULL AS RETURN_CARRIER                                    --SUTLEJ															   
,  NULL AS REGISTRY_TYPE_CD                                  --SUTLEJ             
, TXN_BEGIN_TS 
, TXN_END_TS 
, RETURN_TYPE_CD               
, RETURN_DELIVERY_HUB          
, RETURN_MANAGING_HUB          
, RETURN_CARRIER_CD            
, RETURN_METHOD_CD             
, RECEIPT_PREFERENCE 
, GROSS_AMT 
, NET_AMT 
, TAX_AMT 
, DOCUMENT_TYPE_CD         
, REFUND_POLICY             
, INSERT_TS 
, UPDATE_TS 
FROM L2_ANALYTICS_TABLES.ORDER_HEADER_BKP_20210810

-- COMMAND ----------

SELECT COUNT(*) FROM L2_ANALYTICS_TABLES.ORDER_HEADER

-- COMMAND ----------

CREATE OR REPLACE VIEW L2_ANALYTICS.ORDER_HEADER AS SELECT * FROM  L2_ANALYTICS_TABLES.ORDER_HEADER WHERE  LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000+0000';
--CREATE OR REPLACE VIEW L2_ANALYTICS.ORDER_HEADER_HIST AS SELECT * FROM  L2_ANALYTICS_TABLES.ORDER_HEADER ;

-- COMMAND ----------

CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER_BKP_20210810"

AS 
SELECT * FROM "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER"

-- COMMAND ----------

 DROP TABLE IF EXISTS "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER"

-- COMMAND ----------

CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER"(
ORDER_HEADER_KEY INT NOT NULL
, ORDER_HEADER_ID STRING NOT NULL 
, SOURCE_SYSTEM STRING NOT NULL 
, ORDER_ID STRING
, ORIG_ORDER_ID STRING
, EXCHANGE_ORDER_ID STRING
, ORDER_TYPE_CD STRING
, ORDER_DT DATE NOT NULL
, LOCATION_KEY INT NOT NULL 
, LOCATION_ID STRING NOT NULL
, HOUSEHOLD_KEY INT
, HOUSEHOLD_ID STRING
, DTC_ENTRY_TYPE_CD STRING
, TXN_TYPE_CD STRING NOT NULL
, PAYMENT_STATUS_CD STRING
, CONCEPT_CD STRING NOT NULL
, CURRENCY_CD STRING NOT NULL
, LINKED_ORDER_HEADER_KEY INT
, LINKED_ORDER_HEADER_ID STRING
, POS_WORKSTATION_ID STRING
, POS_WORKSTATION_SEQ_NBR INT
, RTC_LOCATION_KEY INT 
, RTC_LOCATION_ID STRING
, LOYALTY_ACCOUNT_KEY INT
, LOYALTY_ACCOUNT_ID STRING --CCR CHANGE
, CUSTOMER_KEY INT
, CUSTOMER_ID STRING
, EMPLOYEE_ID STRING
, MATCH_METHOD_CD STRING
, FIRST_EFFECTIVE_TS TIMESTAMP NOT NULL 
, LAST_EFFECTIVE_TS TIMESTAMP NOT NULL
, BILL_TO_FIRST_NAME STRING
, BILL_TO_MIDDLE_NAME STRING
, BILL_TO_LAST_NAME STRING
, BILL_TO_ADDRESS_LINE_1 STRING
, BILL_TO_ADDRESS_LINE_2 STRING
, BILL_TO_CITY STRING
, BILL_TO_STATE_OR_PROV_CD STRING
, BILL_TO_POSTAL_CD STRING
, BILL_TO_COUNTRY STRING
, BILL_TO_EMAIL_ADDRESS STRING
, BILL_TO_PHONE_NBR STRING
, TRADE_ID STRING
, CUSTOMER_TYPE_CD STRING
, MEMBERSHIP_LEVEL_CD STRING
, SUBORDERS_CNT INT           --SUTLEJ CHANGE
, MARKET_CD STRING
, STORE_ORDER_SOURCE STRING
, OPERATOR_ID STRING
, CANCEL_FLAG STRING
, TRAINING_MODE_FLAG STRING
, REGISTRY_ORDER_FLAG STRING
, DRAFT_ORDER_FLAG STRING
, ORDER_PURPOSE STRING
, SOURCE_CODE_DISCOUNT_AMT DECIMAL(15,2)                  --SUTLEJ 																		   
, GIFTWRAP_WAIVED_FLAG STRING                             --SUTLEJ															   
, SHIPPING_WAIVED_FLAG STRING                             --SUTLEJ																 
, CATALOG_NM STRING                                       --SUTLEJ															   
, CATALOG_YEAR STRING                                     --SUTLEJ 
, REGISTRY_ID STRING                                      --SUTLEJ															   
, ORDER_SOURCE_TYPE_CD STRING                             --SUTLEJ															   
, GIFT_FLAG STRING                                        --SUTLEJ															   
, WAREHOUSE_SITE_CD STRING                                --SUTLEJ															   
, PAPER_FLAG STRING                                       --SUTLEJ															   
, STORE_ASSOCIATE_NM STRING                               --SUTLEJ															   
, TENTATIVE_REFUND_AMT STRING                             --SUTLEJ															   
, CONTACT_FLAG STRING                                     --SUTLEJ																
, RETURN_CARRIER STRING                                   --SUTLEJ															   
, REGISTRY_TYPE_CD STRING                                 --SUTLEJ
, TXN_BEGIN_TS TIMESTAMP NOT NULL
, TXN_END_TS TIMESTAMP NOT NULL
, RETURN_TYPE_CD STRING
, RETURN_DELIVERY_HUB STRING
, RETURN_MANAGING_HUB STRING
, RETURN_CARRIER_CD STRING
, RETURN_METHOD_CD STRING
, RECEIPT_PREFERENCE STRING
, GROSS_AMT DECIMAL(15,2)
, NET_AMT DECIMAL(15,2)
, TAX_AMT DECIMAL(15,2)
, DOCUMENT_TYPE_CD STRING
, REFUND_POLICY STRING
, INSERT_TS TIMESTAMP NOT NULL
, UPDATE_TS TIMESTAMP NOT NULL )
cluster by (ORDER_DT, SOURCE_SYSTEM)

-- COMMAND ----------

INSERT INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER"
SELECT 
ORDER_HEADER_KEY 
, trim(ORDER_HEADER_ID) 
, SOURCE_SYSTEM 
, ORDER_ID 
, ORIG_ORDER_ID 
, EXCHANGE_ORDER_ID  
, ORDER_TYPE_CD  
, ORDER_DT          
, LOCATION_KEY 
, LOCATION_ID 
, HOUSEHOLD_KEY      
, HOUSEHOLD_ID     
, DTC_ENTRY_TYPE_CD 
, TXN_TYPE_CD 
, PAYMENT_STATUS_CD     
, CONCEPT_CD 
, CURRENCY_CD 
, LINKED_ORDER_HEADER_KEY 
, LINKED_ORDER_HEADER_ID 
, POS_WORKSTATION_ID 
, POS_WORKSTATION_SEQ_NBR 
, RTC_LOCATION_KEY 
, RTC_LOCATION_ID 
, LOYALTY_ACCOUNT_KEY 
, LOYALTY_ACCOUNT_ID --CCR CHANGE
, CUSTOMER_KEY 
, CUSTOMER_ID 
, EMPLOYEE_ID         
, MATCH_METHOD_CD 
, FIRST_EFFECTIVE_TS 
, LAST_EFFECTIVE_TS 
, BILL_TO_FIRST_NAME 
, BILL_TO_MIDDLE_NAME 
, BILL_TO_LAST_NAME 
, BILL_TO_ADDRESS_LINE_1 
, BILL_TO_ADDRESS_LINE_2 
, BILL_TO_CITY 
, BILL_TO_STATE_OR_PROV_CD 
, BILL_TO_POSTAL_CD 
, BILL_TO_COUNTRY 
, BILL_TO_EMAIL_ADDRESS 
, BILL_TO_PHONE_NBR 
, TRADE_ID 
, CUSTOMER_TYPE_CD 
, MEMBERSHIP_LEVEL_CD 
, NULL AS SUBORDERS_CNT       --SUTLEJ CHANGE
, MARKET_CD              
, STORE_ORDER_SOURCE 
, OPERATOR_ID 
, CANCEL_FLAG 
, TRAINING_MODE_FLAG 
, REGISTRY_ORDER_FLAG         
, DRAFT_ORDER_FLAG           
, ORDER_PURPOSE
,  NULL AS SOURCE_CODE_DISCOUNT_AMT                          --SUTLEJ 																		   
,  NULL AS GIFTWRAP_WAIVED_FLAG                              --SUTLEJ															   
,  NULL AS SHIPPING_WAIVED_FLAG                              --SUTLEJ																 
,  NULL AS CATALOG_NM                                        --SUTLEJ															   
,  NULL AS CATALOG_YEAR                                      --SUTLEJ 
,  NULL AS REGISTRY_ID                                       --SUTLEJ															   
,  NULL AS ORDER_SOURCE_TYPE_CD                              --SUTLEJ															   
,  NULL AS GIFT_FLAG                                         --SUTLEJ															   
,  NULL AS WAREHOUSE_SITE_CD                                 --SUTLEJ															   
,  NULL AS PAPER_FLAG                                        --SUTLEJ															   
,  NULL AS STORE_ASSOCIATE_NM                                --SUTLEJ															   
,  NULL AS TENTATIVE_REFUND_AMT                              --SUTLEJ															   
,  NULL AS CONTACT_FLAG                                      --SUTLEJ																
,  NULL AS RETURN_CARRIER                                    --SUTLEJ															   
,  NULL AS REGISTRY_TYPE_CD                                  --SUTLEJ                
, TXN_BEGIN_TS 
, TXN_END_TS 
, RETURN_TYPE_CD               
, RETURN_DELIVERY_HUB          
, RETURN_MANAGING_HUB          
, RETURN_CARRIER_CD            
, RETURN_METHOD_CD             
, RECEIPT_PREFERENCE 
, GROSS_AMT 
, NET_AMT 
, TAX_AMT 
, DOCUMENT_TYPE_CD         
, REFUND_POLICY             
, INSERT_TS 
, UPDATE_TS 
FROM "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER_BKP_20210810"

-- COMMAND ----------

CREATE OR REPLACE VIEW "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS"."ORDER_HEADER" AS SELECT * FROM  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_HEADER" WHERE  LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';
--CREATE OR REPLACE VIEW "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS"."ORDER_HEADER_HIST" AS SELECT * FROM  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS"."ORDER_HEADER" ;

-- COMMAND ----------

CREATE TABLE L2_ANALYTICS_TABLES.ORDER_LINE_BKP_20210810
USING DELTA
LOCATION 'dbfs:/mnt/data/governed/l2/backup/20210810/ORDER_LINE_bkp'
AS
SELECT * FROM L2_ANALYTICS_TABLES.ORDER_LINE
;

-- COMMAND ----------

SELECT COUNT(*) FROM L2_ANALYTICS_TABLES.ORDER_LINE_BKP_20210810
--SHIFT BOTH THESE BKP stmts down

-- COMMAND ----------

-- MAGIC %scala
-- MAGIC 
-- MAGIC //dbutils.fs.mkdirs("dbfs:/mnt/data/governed/l2/analytics/order/line")

-- COMMAND ----------

-- MAGIC %scala
-- MAGIC dbutils.fs.rm("dbfs:/mnt/data/governed/l2/analytics/order/line",true)

-- COMMAND ----------

-- MAGIC %sql
-- MAGIC drop table L2_ANALYTICS_TABLES.ORDER_LINE

-- COMMAND ----------


/* ORIGINAL CODE with proper null constraints*/
/*CREATE TABLE L2_ANALYTICS_TABLES.ORDER_LINE ( --change sql path below
  ORDER_LINE_KEY BIGINT NOT NULL
, ORDER_LINE_ID STRING NOT NULL
, ORDER_HEADER_KEY INT NOT NULL
, CHAINED_FROM_ORDER_HEADER_KEY BIGINT  --SEPIK
, CHAINED_FROM_ORDER_HEADER_ID  STRING              --SEPIK
, CHAINED_FROM_ORDER_LINE_KEY   BIGINT       --SEPIK
, CHAINED_FROM_ORDER_LINE_ID    STRING             --SEPIK
, SOURCE_SYSTEM STRING NOT NULL
, ORDER_DT DATE NOT NULL  --REARRANGED THIS FIELD TO BRING THEM TOGETHER
, ORDER_LINE_TYPE string NOT NULL --REARRANGED THIS FIELD TO BRING THEM TOGETHER
, PRIME_LINE_SEQ_NBR INT NOT NULL
, SUB_LINE_SEQ_NBR INT
, LINKED_ORDER_HEADER_KEY INT
, LINKED_ORDER_HEADER_ID STRING
, LINKED_ORDER_LINE_KEY BIGINT
, LINKED_ORDER_LINE_ID STRING
, ITEM_KEY INT NOT NULL
, ORDER_ITEM_ID STRING NOT NULL
, ORDER_ITEM_TYPE_CD STRING
, ORDER_ITEM_NAME STRING
, GIFT_REGISTRY_KEY INT
, GIFT_REGISTRY_ID STRING
, FIRST_EFFECTIVE_TS TIMESTAMP
, LAST_EFFECTIVE_TS TIMESTAMP
, UPC_CD STRING
, KIT_CD STRING
, KIT_QTY INT
, PRODUCT_LINE STRING
, BUNDLE_PARENT_ORDER_LINE_ID STRING
, ORDER_QTY INT
, ORIG_ORDER_QTY INT
, ACT_SALE_UNIT_PRICE_AMT DECIMAL(15,2)
, REG_SALE_UNIT_PRICE_AMT DECIMAL(15,2)
, EXTENDED_AMT DECIMAL(15,2)
, EXTENDED_DISCOUNT_AMT DECIMAL(15,2)
, TAX_AMT DECIMAL(15,2)
, TAXABLE_AMT DECIMAL(15,2)
, GIFT_CARD_AMT DECIMAL(15,2)
, GIFTWRAP_CHARGE_AMT DECIMAL(15,2)
, LINE_TOTAL_AMT DECIMAL(15,2)
, MERCHANDISE_CHARGE_AMT DECIMAL(15,2)
, MONO_PZ_CHARGE_AMT DECIMAL(15,2)
, MISC_CHARGE_AMT DECIMAL(15,2)
, SHIPPING_HANDLING_CHARGE_AMT DECIMAL(15,2)
, SHIPPING_SURCHARGE_AMT DECIMAL(15,2)
, DONATION_AMT DECIMAL(15,2)
, ASSOCIATE_ID STRING
, ENTRY_METHOD STRING
, GIFT_MESSAGE STRING
, VOID_FLAG STRING
, REPO_FLAG STRING
, TAXABLE_FLAG STRING
, PICKABLE_FLAG STRING
, GIFT_FLAG STRING
, HOLD_FLAG STRING
, HOLD_REASON STRING
, ORIG_BACKORDER_FLAG STRING
, SUBORDER_COMPLEXITY_GROUP_ID STRING --SUTLEJ CHANGE
, DELIVERY_CHOICE STRING
, MODIFICATION_REASON_CD STRING
, MODIFICATION_REASON_CD_DESC STRING
, RETURN_ACTION_CD STRING
, RETURN_ACTION STRING
, RETURN_REASON_CD STRING
, RETURN_REASON_DESC STRING
, RETURN_SUB_REASON_CD STRING
, SHIP_TO_FIRST_NAME STRING
, SHIP_TO_MIDDLE_NAME STRING
, SHIP_TO_LAST_NAME STRING
, SHIP_TO_ADDRESS_LINE_1 STRING
, SHIP_TO_ADDRESS_LINE_2 STRING
, SHIP_TO_CITY STRING
, SHIP_TO_STATE_OR_PROV STRING
, SHIP_TO_POSTAL_CD STRING
, SHIP_TO_COUNTRY STRING
, SHIP_TO_EMAIL_ADDRESS STRING
, SHIP_TO_PHONE_NBR STRING
, DELIVERY_METHOD   STRING                -- SEPIK
, FULFILLMENT_TYPE  STRING                -- SEPIK
, DTC_SUBORDER_NBR  INT                   -- SEPIK
, ADDITIONAL_LINE_TYPE_CD STRING               -- SEPIK
, ORIG_CONFIRMED_QTY INT                  -- SEPIK
, RESKU_FLAG CHAR(1)              -- SEPIK
, CONSOLIDATOR_ADDRESS_CD STRING
, MERGE_NODE_CD STRING
, SHIP_NODE_CD STRING
, RECEIVING_NODE_CD STRING
, LEVEL_OF_SERVICE STRING
, CARRIER_SERVICE_CD STRING
, CARRIER_CD STRING
, ACCESS_POINT_CD STRING
, ACCESS_POINT_ID STRING
, ACCESS_POINT_NM STRING
, MINIMUM_SHIP_DT DATE
, REQUESTED_SHIP_DT DATE
, REQUESTED_DELIVERY_DT DATE
, EARLIEST_SCHEDULE_DT DATE
, EARLIEST_DELIVERY_DT DATE
, PROMISED_APPT_END_DT DATE
, SPLIT_QTY INT
, SHIPPED_QTY INT
, FILL_QTY INT
, WEIGHTED_AVG_COST DECIMAL(15,2)
, DIRECT_SHIP_FLAG STRING
, UNIT_COST DECIMAL(15,2)
, LABOR_COST DECIMAL(15,2)
, LABOR_SKU STRING
, CUSTOMER_LEVEL_OF_SERVICE STRING
, RETURN_POLICY	                STRING               -- SEPIK
, RETURN_POLICY_CHECK_OVERRIDE_FLAG CHAR(1)       -- SEPIK
, PRODUCT_AVAILABILITY_DT   DATE               -- SEPIK
, ECDD_OVERRIDDEN_FLAG      CHAR(1)            -- SEPIK
, ECDD_INVOKED_FLAG         CHAR(1)            -- SEPIK
, VAS_GIFT_WRAP_CD		 STRING			   -- SEPIK
, VAS_MONO_FLAG     CHAR(1)  --SEPIK
, VAS_PZ_FLAG		CHAR(1)  --SEPIK
, BO_NOTIFICATION_NBR	INT
, INSERT_TS TIMESTAMP NOT NULL
, UPDATE_TS TIMESTAMP NOT NULL) 
USING delta PARTITIONED BY (ORDER_DT, SOURCE_SYSTEM) 
LOCATION 'dbfs:/mnt/data/governed/l2/analytics/order/line'*/

-- COMMAND ----------

desc formatted L2_ANALYTICS_TABLES.ORDER_LINE

-- COMMAND ----------

-- MAGIC %sql
-- MAGIC CREATE TABLE L2_ANALYTICS_TABLES.ORDER_LINE ( 
-- MAGIC   ORDER_LINE_KEY BIGINT NOT NULL
-- MAGIC , ORDER_LINE_ID STRING NOT NULL
-- MAGIC , ORDER_HEADER_KEY INT NOT NULL
-- MAGIC , CHAINED_FROM_ORDER_HEADER_KEY BIGINT  --SEPIK
-- MAGIC , CHAINED_FROM_ORDER_HEADER_ID  STRING              --SEPIK
-- MAGIC , CHAINED_FROM_ORDER_LINE_KEY   BIGINT       --SEPIK
-- MAGIC , CHAINED_FROM_ORDER_LINE_ID    STRING             --SEPIK
-- MAGIC , SOURCE_SYSTEM STRING NOT NULL
-- MAGIC , ORDER_DT DATE NOT NULL  --REARRANGED THIS FIELD TO BRING THEM TOGETHER
-- MAGIC , ORDER_LINE_TYPE string  --REARRANGED THIS FIELD TO BRING THEM TOGETHER
-- MAGIC , PRIME_LINE_SEQ_NBR INT
-- MAGIC , SUB_LINE_SEQ_NBR INT
-- MAGIC , LINKED_ORDER_HEADER_KEY INT
-- MAGIC , LINKED_ORDER_HEADER_ID STRING
-- MAGIC , LINKED_ORDER_LINE_KEY BIGINT
-- MAGIC , LINKED_ORDER_LINE_ID STRING
-- MAGIC , ITEM_KEY INT 
-- MAGIC , ORDER_ITEM_ID STRING NOT NULL
-- MAGIC , ORDER_ITEM_TYPE_CD STRING
-- MAGIC , ORDER_ITEM_NAME STRING
-- MAGIC , GIFT_REGISTRY_KEY INT
-- MAGIC , GIFT_REGISTRY_ID STRING
-- MAGIC , FIRST_EFFECTIVE_TS TIMESTAMP
-- MAGIC , LAST_EFFECTIVE_TS TIMESTAMP
-- MAGIC , UPC_CD STRING
-- MAGIC , KIT_CD STRING
-- MAGIC , KIT_QTY INT
-- MAGIC , PRODUCT_LINE STRING
-- MAGIC , BUNDLE_PARENT_ORDER_LINE_ID STRING
-- MAGIC , ORDER_QTY INT
-- MAGIC , ORIG_ORDER_QTY INT
-- MAGIC , ACT_SALE_UNIT_PRICE_AMT DECIMAL(15,2)
-- MAGIC , REG_SALE_UNIT_PRICE_AMT DECIMAL(15,2)
-- MAGIC , EXTENDED_AMT DECIMAL(15,2)
-- MAGIC , EXTENDED_DISCOUNT_AMT DECIMAL(15,2)
-- MAGIC , TAX_AMT DECIMAL(15,2)
-- MAGIC , TAXABLE_AMT DECIMAL(15,2)
-- MAGIC , GIFT_CARD_AMT DECIMAL(15,2)
-- MAGIC , GIFTWRAP_CHARGE_AMT DECIMAL(15,2)
-- MAGIC , LINE_TOTAL_AMT DECIMAL(15,2)
-- MAGIC , MERCHANDISE_CHARGE_AMT DECIMAL(15,2)
-- MAGIC , MONO_PZ_CHARGE_AMT DECIMAL(15,2)
-- MAGIC , MISC_CHARGE_AMT DECIMAL(15,2)
-- MAGIC , SHIPPING_HANDLING_CHARGE_AMT DECIMAL(15,2)
-- MAGIC , SHIPPING_SURCHARGE_AMT DECIMAL(15,2)
-- MAGIC , DONATION_AMT DECIMAL(15,2)
-- MAGIC , ASSOCIATE_ID STRING
-- MAGIC , ENTRY_METHOD STRING
-- MAGIC , GIFT_MESSAGE STRING
-- MAGIC , VOID_FLAG STRING
-- MAGIC , REPO_FLAG STRING
-- MAGIC , TAXABLE_FLAG STRING
-- MAGIC , PICKABLE_FLAG STRING
-- MAGIC , GIFT_FLAG STRING
-- MAGIC , HOLD_FLAG STRING
-- MAGIC , HOLD_REASON STRING
-- MAGIC , ORIG_BACKORDER_FLAG STRING
-- MAGIC , SUBORDER_COMPLEXITY_GROUP_ID STRING --SUTLEJ CHANGE
-- MAGIC , DELIVERY_CHOICE STRING
-- MAGIC , MODIFICATION_REASON_CD STRING
-- MAGIC , MODIFICATION_REASON_CD_DESC STRING
-- MAGIC , RETURN_ACTION_CD STRING
-- MAGIC , RETURN_ACTION STRING
-- MAGIC , RETURN_REASON_CD STRING
-- MAGIC , RETURN_REASON_DESC STRING
-- MAGIC , RETURN_SUB_REASON_CD STRING
-- MAGIC , SHIP_TO_FIRST_NAME STRING
-- MAGIC , SHIP_TO_MIDDLE_NAME STRING
-- MAGIC , SHIP_TO_LAST_NAME STRING
-- MAGIC , SHIP_TO_ADDRESS_LINE_1 STRING
-- MAGIC , SHIP_TO_ADDRESS_LINE_2 STRING
-- MAGIC , SHIP_TO_CITY STRING
-- MAGIC , SHIP_TO_STATE_OR_PROV STRING
-- MAGIC , SHIP_TO_POSTAL_CD STRING
-- MAGIC , SHIP_TO_COUNTRY STRING
-- MAGIC , SHIP_TO_EMAIL_ADDRESS STRING
-- MAGIC , SHIP_TO_PHONE_NBR STRING
-- MAGIC , DELIVERY_METHOD   STRING                -- SEPIK
-- MAGIC , FULFILLMENT_TYPE  STRING                -- SEPIK
-- MAGIC , DTC_SUBORDER_NBR  INT                   -- SEPIK
-- MAGIC , ADDITIONAL_LINE_TYPE_CD STRING               -- SEPIK
-- MAGIC , ORIG_CONFIRMED_QTY INT                  -- SEPIK
-- MAGIC , RESKU_FLAG CHAR(1)              -- SEPIK
-- MAGIC , CONSOLIDATOR_ADDRESS_CD STRING
-- MAGIC , MERGE_NODE_CD STRING
-- MAGIC , SHIP_NODE_CD STRING
-- MAGIC , RECEIVING_NODE_CD STRING
-- MAGIC , LEVEL_OF_SERVICE STRING
-- MAGIC , CARRIER_SERVICE_CD STRING
-- MAGIC , CARRIER_CD STRING
-- MAGIC , ACCESS_POINT_CD STRING
-- MAGIC , ACCESS_POINT_ID STRING
-- MAGIC , ACCESS_POINT_NM STRING
-- MAGIC , MINIMUM_SHIP_DT DATE
-- MAGIC , REQUESTED_SHIP_DT DATE
-- MAGIC , REQUESTED_DELIVERY_DT DATE
-- MAGIC , EARLIEST_SCHEDULE_DT DATE
-- MAGIC , EARLIEST_DELIVERY_DT DATE
-- MAGIC , PROMISED_APPT_END_DT DATE
-- MAGIC , SPLIT_QTY INT
-- MAGIC , SHIPPED_QTY INT
-- MAGIC , FILL_QTY INT
-- MAGIC , WEIGHTED_AVG_COST DECIMAL(15,2)
-- MAGIC , DIRECT_SHIP_FLAG STRING
-- MAGIC , UNIT_COST DECIMAL(15,2)
-- MAGIC , LABOR_COST DECIMAL(15,2)
-- MAGIC , LABOR_SKU STRING
-- MAGIC , CUSTOMER_LEVEL_OF_SERVICE STRING
-- MAGIC , RETURN_POLICY	                STRING               -- SEPIK
-- MAGIC , RETURN_POLICY_CHECK_OVERRIDE_FLAG CHAR(1)       -- SEPIK
-- MAGIC , PRODUCT_AVAILABILITY_DT   DATE               -- SEPIK
-- MAGIC , ECDD_OVERRIDDEN_FLAG      CHAR(1)            -- SEPIK
-- MAGIC , ECDD_INVOKED_FLAG         CHAR(1)            -- SEPIK
-- MAGIC , VAS_GIFT_WRAP_CD		 STRING			   -- SEPIK
-- MAGIC , VAS_MONO_FLAG     CHAR(1)  --SEPIK
-- MAGIC , VAS_PZ_FLAG		CHAR(1)  --SEPIK
-- MAGIC , BO_NOTIFICATION_NBR	INT
-- MAGIC , INSERT_TS TIMESTAMP NOT NULL
-- MAGIC , UPDATE_TS TIMESTAMP NOT NULL) 
-- MAGIC USING delta PARTITIONED BY (ORDER_DT, SOURCE_SYSTEM) 
-- MAGIC LOCATION 'dbfs:/mnt/data/governed/l2/analytics/order/line'
-- MAGIC 
-- MAGIC --null constraints removed for item_key,prim_line_seq_nbr,order_line_type

-- COMMAND ----------

INSERT INTO L2_ANALYTICS_TABLES.ORDER_LINE 
SELECT 
  ORDER_LINE_KEY
, trim(ORDER_LINE_ID) 
, ORDER_HEADER_KEY 
, CHAINED_FROM_ORDER_HEADER_KEY   --SEPIK
, CHAINED_FROM_ORDER_HEADER_ID                --SEPIK
, CHAINED_FROM_ORDER_LINE_KEY          --SEPIK
, trim(CHAINED_FROM_ORDER_LINE_ID)                 --SEPIK
, SOURCE_SYSTEM 
, ORDER_DT   --REARRANGED THIS FIELD TO BRING THEM TOGETHER
, trim(ORDER_LINE_TYPE)  --REARRANGED THIS FIELD TO BRING THEM TOGETHER
, PRIME_LINE_SEQ_NBR 
, SUB_LINE_SEQ_NBR 
, LINKED_ORDER_HEADER_KEY 
, LINKED_ORDER_HEADER_ID 
, LINKED_ORDER_LINE_KEY 
, trim(LINKED_ORDER_LINE_ID) 
, ITEM_KEY 
, ORDER_ITEM_ID 
, ORDER_ITEM_TYPE_CD 
, ORDER_ITEM_NAME 
, GIFT_REGISTRY_KEY 
, GIFT_REGISTRY_ID 
, FIRST_EFFECTIVE_TS 
, LAST_EFFECTIVE_TS 
, UPC_CD 
, KIT_CD 
, KIT_QTY 
, PRODUCT_LINE 
, BUNDLE_PARENT_ORDER_LINE_ID 
, ORDER_QTY 
, ORIG_ORDER_QTY 
, ACT_SALE_UNIT_PRICE_AMT 
, REG_SALE_UNIT_PRICE_AMT 
, EXTENDED_AMT 
, EXTENDED_DISCOUNT_AMT 
, TAX_AMT 
, TAXABLE_AMT 
, GIFT_CARD_AMT 
, GIFTWRAP_CHARGE_AMT 
, LINE_TOTAL_AMT 
, MERCHANDISE_CHARGE_AMT 
, MONO_PZ_CHARGE_AMT 
, MISC_CHARGE_AMT 
, SHIPPING_HANDLING_CHARGE_AMT 
, SHIPPING_SURCHARGE_AMT 
, DONATION_AMT 
, ASSOCIATE_ID 
, ENTRY_METHOD 
, GIFT_MESSAGE 
, VOID_FLAG 
, REPO_FLAG 
, TAXABLE_FLAG 
, PICKABLE_FLAG 
, GIFT_FLAG 
, HOLD_FLAG 
, HOLD_REASON 
, ORIG_BACKORDER_FLAG  --SULEJ CHANGE
, NULL AS SUBORDER_COMPLEXITY_GROUP_ID --SUTLEJ 
, DELIVERY_CHOICE 
, MODIFICATION_REASON_CD 
, MODIFICATION_REASON_CD_DESC 
, RETURN_ACTION_CD 
, RETURN_ACTION 
, RETURN_REASON_CD 
, RETURN_REASON_DESC 
, RETURN_SUB_REASON_CD 
, SHIP_TO_FIRST_NAME 
, SHIP_TO_MIDDLE_NAME 
, SHIP_TO_LAST_NAME 
, SHIP_TO_ADDRESS_LINE_1 
, SHIP_TO_ADDRESS_LINE_2 
, SHIP_TO_CITY 
, SHIP_TO_STATE_OR_PROV 
, SHIP_TO_POSTAL_CD 
, SHIP_TO_COUNTRY 
, SHIP_TO_EMAIL_ADDRESS 
, SHIP_TO_PHONE_NBR                 
, DELIVERY_METHOD                   -- SEPIK
, FULFILLMENT_TYPE                  -- SEPIK
, DTC_SUBORDER_NBR                     -- SEPIK
, ADDITIONAL_LINE_TYPE_CD                -- SEPIK
, ORIG_CONFIRMED_QTY                   -- SEPIK
, RESKU_FLAG               -- SEPIK
, CONSOLIDATOR_ADDRESS_CD 
, MERGE_NODE_CD 
, SHIP_NODE_CD 
, RECEIVING_NODE_CD 
, LEVEL_OF_SERVICE 
, CARRIER_SERVICE_CD 
, CARRIER_CD 
, ACCESS_POINT_CD 
, ACCESS_POINT_ID 
, ACCESS_POINT_NM 
, MINIMUM_SHIP_DT 
, REQUESTED_SHIP_DT 
, REQUESTED_DELIVERY_DT 
, EARLIEST_SCHEDULE_DT 
, EARLIEST_DELIVERY_DT 
, PROMISED_APPT_END_DT 
, SPLIT_QTY 
, SHIPPED_QTY 
, FILL_QTY 
, WEIGHTED_AVG_COST 
, DIRECT_SHIP_FLAG 
, UNIT_COST 
, LABOR_COST 
, LABOR_SKU 
, CUSTOMER_LEVEL_OF_SERVICE 
, RETURN_POLICY	                               -- SEPIK
, RETURN_POLICY_CHECK_OVERRIDE_FLAG        -- SEPIK
, PRODUCT_AVAILABILITY_DT                  -- SEPIK
, ECDD_OVERRIDDEN_FLAG                  -- SEPIK
, ECDD_INVOKED_FLAG                     -- SEPIK
, VAS_GIFT_WRAP_CD		 			   -- SEPIK
, VAS_MONO_FLAG       --SEPIK
, VAS_PZ_FLAG		  --SEPIK
, BO_NOTIFICATION_NBR	
, INSERT_TS 
, UPDATE_TS 
 FROM delta.`/mnt/data/governed/l2/backup/20210810/ORDER_LINE_bkp`

-- COMMAND ----------

SELECT COUNT(*) FROM L2_ANALYTICS_TABLES.ORDER_LINE

-- COMMAND ----------

CREATE OR REPLACE VIEW L2_ANALYTICS.ORDER_LINE AS SELECT * FROM  L2_ANALYTICS_TABLES.ORDER_LINE WHERE  LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000+0000';
--CREATE OR REPLACE VIEW L2_ANALYTICS.ORDER_LINE_HIST AS SELECT * FROM  L2_ANALYTICS_TABLES.ORDER_LINE ; --
--991580182

-- COMMAND ----------

CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE_BKP_20210810"

AS 
SELECT * FROM "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE"

-- COMMAND ----------

 DROP TABLE IF EXISTS "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE"

-- COMMAND ----------

 CREATE TABLE "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE"( -- REMOVED NULL CONSTRAINT FOR 3 FIELDS, SAME AS IN CREATE L2 STMT
  ORDER_LINE_KEY BIGINT NOT NULL
, ORDER_LINE_ID STRING NOT NULL
, ORDER_HEADER_KEY INT NOT NULL
, CHAINED_FROM_ORDER_HEADER_KEY BIGINT  --SEPIK
, CHAINED_FROM_ORDER_HEADER_ID  STRING              --SEPIK
, CHAINED_FROM_ORDER_LINE_KEY   BIGINT       --SEPIK
, CHAINED_FROM_ORDER_LINE_ID    STRING             --SEPIK
, SOURCE_SYSTEM STRING NOT NULL
, ORDER_DT DATE NOT NULL  
, ORDER_LINE_TYPE string  
, PRIME_LINE_SEQ_NBR INT
, SUB_LINE_SEQ_NBR INT
, LINKED_ORDER_HEADER_KEY INT
, LINKED_ORDER_HEADER_ID STRING
, LINKED_ORDER_LINE_KEY BIGINT
, LINKED_ORDER_LINE_ID STRING
, ITEM_KEY INT
, ORDER_ITEM_ID STRING NOT NULL
, ORDER_ITEM_TYPE_CD STRING
, ORDER_ITEM_NAME STRING
, GIFT_REGISTRY_KEY INT
, GIFT_REGISTRY_ID STRING
, FIRST_EFFECTIVE_TS TIMESTAMP
, LAST_EFFECTIVE_TS TIMESTAMP
, UPC_CD STRING
, KIT_CD STRING
, KIT_QTY INT
, PRODUCT_LINE STRING
, BUNDLE_PARENT_ORDER_LINE_ID STRING
, ORDER_QTY INT
, ORIG_ORDER_QTY INT
, ACT_SALE_UNIT_PRICE_AMT DECIMAL(15,2)
, REG_SALE_UNIT_PRICE_AMT DECIMAL(15,2)
, EXTENDED_AMT DECIMAL(15,2)
, EXTENDED_DISCOUNT_AMT DECIMAL(15,2)
, TAX_AMT DECIMAL(15,2)
, TAXABLE_AMT DECIMAL(15,2)
, GIFT_CARD_AMT DECIMAL(15,2)
, GIFTWRAP_CHARGE_AMT DECIMAL(15,2)
, LINE_TOTAL_AMT DECIMAL(15,2)
, MERCHANDISE_CHARGE_AMT DECIMAL(15,2)
, MONO_PZ_CHARGE_AMT DECIMAL(15,2)
, MISC_CHARGE_AMT DECIMAL(15,2)
, SHIPPING_HANDLING_CHARGE_AMT DECIMAL(15,2)
, SHIPPING_SURCHARGE_AMT DECIMAL(15,2)
, DONATION_AMT DECIMAL(15,2)
, ASSOCIATE_ID STRING
, ENTRY_METHOD STRING
, GIFT_MESSAGE STRING
, VOID_FLAG STRING
, REPO_FLAG STRING
, TAXABLE_FLAG STRING
, PICKABLE_FLAG STRING
, GIFT_FLAG STRING
, HOLD_FLAG STRING
, HOLD_REASON STRING
, ORIG_BACKORDER_FLAG STRING
, SUBORDER_COMPLEXITY_GROUP_ID STRING --SUTLEJ
, DELIVERY_CHOICE STRING
, MODIFICATION_REASON_CD STRING
, MODIFICATION_REASON_CD_DESC STRING
, RETURN_ACTION_CD STRING
, RETURN_ACTION STRING
, RETURN_REASON_CD STRING
, RETURN_REASON_DESC STRING
, RETURN_SUB_REASON_CD STRING
, SHIP_TO_FIRST_NAME STRING
, SHIP_TO_MIDDLE_NAME STRING
, SHIP_TO_LAST_NAME STRING
, SHIP_TO_ADDRESS_LINE_1 STRING
, SHIP_TO_ADDRESS_LINE_2 STRING
, SHIP_TO_CITY STRING
, SHIP_TO_STATE_OR_PROV STRING
, SHIP_TO_POSTAL_CD STRING
, SHIP_TO_COUNTRY STRING
, SHIP_TO_EMAIL_ADDRESS STRING
, SHIP_TO_PHONE_NBR STRING
, DELIVERY_METHOD   STRING                -- SEPIK
, FULFILLMENT_TYPE  STRING                -- SEPIK
, DTC_SUBORDER_NBR  INT                   -- SEPIK
, ADDITIONAL_LINE_TYPE_CD STRING               -- SEPIK
, ORIG_CONFIRMED_QTY INT                  -- SEPIK
, RESKU_FLAG CHAR(1)              -- SEPIK
, CONSOLIDATOR_ADDRESS_CD STRING
, MERGE_NODE_CD STRING
, SHIP_NODE_CD STRING
, RECEIVING_NODE_CD STRING
, LEVEL_OF_SERVICE STRING
, CARRIER_SERVICE_CD STRING
, CARRIER_CD STRING
, ACCESS_POINT_CD STRING
, ACCESS_POINT_ID STRING
, ACCESS_POINT_NM STRING
, MINIMUM_SHIP_DT DATE
, REQUESTED_SHIP_DT DATE
, REQUESTED_DELIVERY_DT DATE
, EARLIEST_SCHEDULE_DT DATE
, EARLIEST_DELIVERY_DT DATE
, PROMISED_APPT_END_DT DATE
, SPLIT_QTY INT
, SHIPPED_QTY INT
, FILL_QTY INT
, WEIGHTED_AVG_COST DECIMAL(15,2)
, DIRECT_SHIP_FLAG STRING
, UNIT_COST DECIMAL(15,2)
, LABOR_COST DECIMAL(15,2)
, LABOR_SKU STRING
, CUSTOMER_LEVEL_OF_SERVICE STRING
, RETURN_POLICY	                STRING               -- SEPIK
, RETURN_POLICY_CHECK_OVERRIDE_FLAG CHAR(1)       -- SEPIK
, PRODUCT_AVAILABILITY_DT   DATE               -- SEPIK
, ECDD_OVERRIDDEN_FLAG      CHAR(1)            -- SEPIK
, ECDD_INVOKED_FLAG         CHAR(1)            -- SEPIK
, VAS_GIFT_WRAP_CD		 STRING			   -- SEPIK
, VAS_MONO_FLAG     CHAR(1)  --SEPIK
, VAS_PZ_FLAG		CHAR(1)  --SEPIK
, BO_NOTIFICATION_NBR	INT
, INSERT_TS TIMESTAMP NOT NULL
, UPDATE_TS TIMESTAMP NOT NULL)
  cluster by (ORDER_DT, SOURCE_SYSTEM);

-- COMMAND ----------

INSERT INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE"
SELECT 
  ORDER_LINE_KEY
, ORDER_LINE_ID 
, ORDER_HEADER_KEY 
, CHAINED_FROM_ORDER_HEADER_KEY   --SEPIK
, CHAINED_FROM_ORDER_HEADER_ID                --SEPIK
, CHAINED_FROM_ORDER_LINE_KEY          --SEPIK
, CHAINED_FROM_ORDER_LINE_ID                 --SEPIK
, SOURCE_SYSTEM 
, ORDER_DT   --REARRANGED THIS FIELD TO BRING THEM TOGETHER
, ORDER_LINE_TYPE  --REARRANGED THIS FIELD TO BRING THEM TOGETHER
, PRIME_LINE_SEQ_NBR 
, SUB_LINE_SEQ_NBR 
, LINKED_ORDER_HEADER_KEY 
, LINKED_ORDER_HEADER_ID 
, LINKED_ORDER_LINE_KEY 
, LINKED_ORDER_LINE_ID 
, ITEM_KEY 
, ORDER_ITEM_ID 
, ORDER_ITEM_TYPE_CD 
, ORDER_ITEM_NAME 
, GIFT_REGISTRY_KEY 
, GIFT_REGISTRY_ID 
, FIRST_EFFECTIVE_TS 
, LAST_EFFECTIVE_TS 
, UPC_CD 
, KIT_CD 
, KIT_QTY 
, PRODUCT_LINE 
, BUNDLE_PARENT_ORDER_LINE_ID 
, ORDER_QTY 
, ORIG_ORDER_QTY 
, ACT_SALE_UNIT_PRICE_AMT 
, REG_SALE_UNIT_PRICE_AMT 
, EXTENDED_AMT 
, EXTENDED_DISCOUNT_AMT 
, TAX_AMT 
, TAXABLE_AMT 
, GIFT_CARD_AMT 
, GIFTWRAP_CHARGE_AMT 
, LINE_TOTAL_AMT 
, MERCHANDISE_CHARGE_AMT 
, MONO_PZ_CHARGE_AMT 
, MISC_CHARGE_AMT 
, SHIPPING_HANDLING_CHARGE_AMT 
, SHIPPING_SURCHARGE_AMT 
, DONATION_AMT 
, ASSOCIATE_ID 
, ENTRY_METHOD 
, GIFT_MESSAGE 
, VOID_FLAG 
, REPO_FLAG 
, TAXABLE_FLAG 
, PICKABLE_FLAG 
, GIFT_FLAG 
, HOLD_FLAG 
, HOLD_REASON 
, ORIG_BACKORDER_FLAG
, NULL AS SUBORDER_COMPLEXITY_GROUP_ID --SUTLEJ 
, DELIVERY_CHOICE 
, MODIFICATION_REASON_CD 
, MODIFICATION_REASON_CD_DESC 
, RETURN_ACTION_CD 
, RETURN_ACTION 
, RETURN_REASON_CD 
, RETURN_REASON_DESC 
, RETURN_SUB_REASON_CD 
, SHIP_TO_FIRST_NAME 
, SHIP_TO_MIDDLE_NAME 
, SHIP_TO_LAST_NAME 
, SHIP_TO_ADDRESS_LINE_1 
, SHIP_TO_ADDRESS_LINE_2 
, SHIP_TO_CITY 
, SHIP_TO_STATE_OR_PROV 
, SHIP_TO_POSTAL_CD 
, SHIP_TO_COUNTRY 
, SHIP_TO_EMAIL_ADDRESS 
, SHIP_TO_PHONE_NBR 
, DELIVERY_METHOD                   -- SEPIK
, FULFILLMENT_TYPE                  -- SEPIK
, DTC_SUBORDER_NBR                     -- SEPIK
, ADDITIONAL_LINE_TYPE_CD                -- SEPIK
, ORIG_CONFIRMED_QTY                   -- SEPIK
, RESKU_FLAG               -- SEPIK
, CONSOLIDATOR_ADDRESS_CD 
, MERGE_NODE_CD 
, SHIP_NODE_CD 
, RECEIVING_NODE_CD 
, LEVEL_OF_SERVICE 
, CARRIER_SERVICE_CD 
, CARRIER_CD 
, ACCESS_POINT_CD 
, ACCESS_POINT_ID 
, ACCESS_POINT_NM 
, MINIMUM_SHIP_DT 
, REQUESTED_SHIP_DT 
, REQUESTED_DELIVERY_DT 
, EARLIEST_SCHEDULE_DT 
, EARLIEST_DELIVERY_DT 
, PROMISED_APPT_END_DT 
, SPLIT_QTY 
, SHIPPED_QTY 
, FILL_QTY 
, WEIGHTED_AVG_COST 
, DIRECT_SHIP_FLAG 
, UNIT_COST 
, LABOR_COST 
, LABOR_SKU 
, CUSTOMER_LEVEL_OF_SERVICE 
, RETURN_POLICY	                               -- SEPIK
, RETURN_POLICY_CHECK_OVERRIDE_FLAG        -- SEPIK
, PRODUCT_AVAILABILITY_DT                  -- SEPIK
, ECDD_OVERRIDDEN_FLAG                  -- SEPIK
, ECDD_INVOKED_FLAG                     -- SEPIK
, VAS_GIFT_WRAP_CD		 			   -- SEPIK
, VAS_MONO_FLAG       --SEPIK
, VAS_PZ_FLAG		  --SEPIK
, BO_NOTIFICATION_NBR	
, INSERT_TS 
, UPDATE_TS 
 FROM "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE_BKP_20210810"

-- COMMAND ----------

CREATE OR REPLACE VIEW "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS"."ORDER_LINE" AS SELECT * FROM  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."ORDER_LINE" WHERE  LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';
--CREATE OR REPLACE VIEW "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS"."ORDER_LINE_HIST" AS SELECT * FROM  "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS"."ORDER_LINE" ;

-- COMMAND ----------

-- DBTITLE 1,Execute this pipeline below:
--Execute this pipe: DTC_DEDUP_L2

-- COMMAND ----------

select count(*) from delta.`/mnt/data/teams/sutlej/oh_hist_dropby20210720`

-- COMMAND ----------

-- DBTITLE 1,Historical Load for OH
-- MAGIC %sql
-- MAGIC MERGE INTO L2_ANALYTICS_TABLES.ORDER_HEADER as OH
-- MAGIC USING delta.`/mnt/data/teams/sutlej/oh_hist_dropby20210720` as OHDC
-- MAGIC ON OH.ORDER_HEADER_ID = OHDC.ORDER_HEADER_ID and OH.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000'
-- MAGIC WHEN MATCHED THEN UPDATE SET OH.LOYALTY_ACCOUNT_ID=OHDC.LOYALTY_ACCOUNT_ID,
-- MAGIC                OH.SOURCE_CODE_DISCOUNT_AMT=OHDC.SOURCE_CODE_DISCOUNT_AMT,
-- MAGIC                OH.GIFTWRAP_WAIVED_FLAG=OHDC.GIFTWRAP_WAIVED_FLAG, 
-- MAGIC                OH.SHIPPING_WAIVED_FLAG=OHDC.SHIPPING_WAIVED_FLAG,
-- MAGIC                OH.CATALOG_NM=OHDC.CATALOG_NM,
-- MAGIC                OH.CATALOG_YEAR=OHDC.CATALOG_YEAR,
-- MAGIC                OH.REGISTRY_ORDER_FLAG=OHDC.REGISTRY_ORDER_FLAG,
-- MAGIC                OH.REGISTRY_ID=OHDC.REGISTRY_ID,
-- MAGIC                OH.REGISTRY_TYPE_CD=OHDC.REGISTRY_TYPE_CD, 
-- MAGIC                OH.SUBORDERS_CNT=OHDC.SUBORDERS_CNT,
-- MAGIC                OH.ORDER_SOURCE_TYPE_CD=OHDC.ORDER_SOURCE_TYPE_CD,
-- MAGIC                OH.GIFT_FLAG=OHDC.GIFT_FLAG, 
-- MAGIC                OH.WAREHOUSE_SITE_CD=OHDC.WAREHOUSE_SITE_CD,
-- MAGIC                OH.PAPER_FLAG=OHDC.PAPER_FLAG, 
-- MAGIC                OH.STORE_ASSOCIATE_NM=OHDC.STORE_ASSOCIATE_NM,
-- MAGIC                OH.TENTATIVE_REFUND_AMT=OHDC.TENTATIVE_REFUND_AMT, 
-- MAGIC                OH.CONTACT_FLAG=OHDC.CONTACT_FLAG,
-- MAGIC                OH.RETURN_CARRIER=OHDC.RETURN_CARRIER,
-- MAGIC                OH.RETURN_DELIVERY_HUB=OHDC.RETURN_DELIVERY_HUB,
-- MAGIC                OH.RETURN_MANAGING_HUB=OHDC.RETURN_MANAGING_HUB

-- COMMAND ----------

select count(*) from delta.`/mnt/data/teams/sutlej/oh_Junehist_dropby20210720`

-- COMMAND ----------

-- DBTITLE 1,Historical Load for OH's previously nulled fields from June 7th 2021 onwards
-- MAGIC %sql
-- MAGIC 
-- MAGIC /* This is to merge the table created with June 2021 data with final OH table, having SEPIK's new fields */
-- MAGIC 
-- MAGIC MERGE INTO L2_ANALYTICS_TABLES.ORDER_HEADER as OH
-- MAGIC USING delta.`/mnt/data/teams/sutlej/oh_Junehist_dropby20210720` as OHDC
-- MAGIC ON OH.ORDER_HEADER_ID = OHDC.ORDER_HEADER_ID and OH.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000'
-- MAGIC WHEN MATCHED THEN UPDATE SET OH.EMPLOYEE_ID = OHDC.EMPLOYEE_ID,
-- MAGIC                OH.RETURN_TYPE_CD = OHDC.RETURN_TYPE_CD,
-- MAGIC                OH.EXCHANGE_ORDER_ID = OHDC.EXCHANGE_ORDER_ID,
-- MAGIC                OH.DRAFT_ORDER_FLAG = OHDC.DRAFT_ORDER_FLAG,
-- MAGIC                OH.RETURN_CARRIER_CD = OHDC.RETURN_CARRIER_CD,
-- MAGIC                OH.RETURN_METHOD_CD = OHDC.RETURN_METHOD_CD,
-- MAGIC                OH.PAYMENT_STATUS_CD = OHDC.PAYMENT_STATUS_CD,
-- MAGIC                OH.REFUND_POLICY = OHDC.REFUND_POLICY,
-- MAGIC                OH.ORDER_PURPOSE = OHDC.ORDER_PURPOSE,
-- MAGIC                OH.LOYALTY_ACCOUNT_ID=OHDC.LOYALTY_ACCOUNT_ID,
-- MAGIC                OH.SOURCE_CODE_DISCOUNT_AMT=OHDC.SOURCE_CODE_DISCOUNT_AMT,
-- MAGIC                OH.GIFTWRAP_WAIVED_FLAG=OHDC.GIFTWRAP_WAIVED_FLAG, 
-- MAGIC                OH.SHIPPING_WAIVED_FLAG=OHDC.SHIPPING_WAIVED_FLAG,
-- MAGIC                OH.CATALOG_NM=OHDC.CATALOG_NM,
-- MAGIC                OH.CATALOG_YEAR=OHDC.CATALOG_YEAR,
-- MAGIC                OH.REGISTRY_ORDER_FLAG=OHDC.REGISTRY_ORDER_FLAG,
-- MAGIC                OH.REGISTRY_ID=OHDC.REGISTRY_ID,
-- MAGIC                OH.REGISTRY_TYPE_CD=OHDC.REGISTRY_TYPE_CD, 
-- MAGIC                OH.SUBORDERS_CNT=OHDC.SUBORDERS_CNT,
-- MAGIC                OH.ORDER_SOURCE_TYPE_CD=OHDC.ORDER_SOURCE_TYPE_CD,
-- MAGIC                OH.GIFT_FLAG=OHDC.GIFT_FLAG, 
-- MAGIC                OH.WAREHOUSE_SITE_CD=OHDC.WAREHOUSE_SITE_CD,
-- MAGIC                OH.PAPER_FLAG=OHDC.PAPER_FLAG, 
-- MAGIC                OH.STORE_ASSOCIATE_NM=OHDC.STORE_ASSOCIATE_NM,
-- MAGIC                OH.TENTATIVE_REFUND_AMT=OHDC.TENTATIVE_REFUND_AMT, 
-- MAGIC                OH.CONTACT_FLAG=OHDC.CONTACT_FLAG,
-- MAGIC                OH.RETURN_CARRIER=OHDC.RETURN_CARRIER,
-- MAGIC                OH.RETURN_DELIVERY_HUB=OHDC.RETURN_DELIVERY_HUB,
-- MAGIC                OH.RETURN_MANAGING_HUB=OHDC.RETURN_MANAGING_HUB
-- MAGIC                

-- COMMAND ----------

select count(*) from delta.`/mnt/data/teams/sutlej/ol_hist_dropby20210720`

-- COMMAND ----------

-- DBTITLE 1,Historical Load for OL 
-- MAGIC %sql
-- MAGIC MERGE INTO L2_ANALYTICS_TABLES.ORDER_LINE as OL
-- MAGIC USING delta.`/mnt/data/teams/sutlej/ol_hist_dropby20210810` as OLDC 
-- MAGIC ON OL.ORDER_LINE_ID = OLDC.ORDER_LINE_ID and OL.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000'
-- MAGIC WHEN MATCHED THEN UPDATE SET OL.DELIVERY_METHOD = OLDC.DELIVERY_METHOD, 
-- MAGIC                OL.FULFILLMENT_TYPE = OLDC.FULFILLMENT_TYPE,
-- MAGIC                OL.DTC_SUBORDER_NBR = OLDC.DTC_SUBORDER_NBR,
-- MAGIC                OL.ORIG_CONFIRMED_QTY = OLDC.ORIG_CONFIRMED_QTY,
-- MAGIC                OL.RESKU_FLAG = OLDC.RESKU_FLAG,
-- MAGIC                OL.RETURN_POLICY = OLDC.RETURN_POLICY,
-- MAGIC                OL.PRODUCT_AVAILABILITY_DT = OLDC.PRODUCT_AVAILABILITY_DT,
-- MAGIC                OL.ECDD_OVERRIDDEN_FLAG = OLDC.ECDD_OVERRIDDEN_FLAG,
-- MAGIC                OL.ECDD_INVOKED_FLAG = OLDC.ECDD_INVOKED_FLAG,
-- MAGIC                OL.ADDITIONAL_LINE_TYPE_CD = OLDC.ADDITIONAL_LINE_TYPE_CD,
-- MAGIC                OL.ORIG_BACKORDER_FLAG = OLDC.ORIG_BACKORDER_FLAG,
-- MAGIC                OL.SUBORDER_COMPLEXITY_GROUP_ID =OLDC.SUBORDER_COMPLEXITY_GROUP_ID,
-- MAGIC                OL.PRODUCT_LINE = OLDC.PRODUCT_LINE,
-- MAGIC                OL.BO_NOTIFICATION_NBR = OLDC.BO_NOTIFICATION_NBR

-- COMMAND ----------

-- DBTITLE 1,Execute both below pipelines simultaneously:
--Execute this Pipeline: ORDER_HEADER_CCPA_INGEST_SNOFLK

-- COMMAND ----------

--Execute this ppln: ORDER_LINE_CCPA_INGEST_SNOFLK

-- COMMAND ----------

--Execute one time script of other pipes

-- COMMAND ----------

-- DBTITLE 1,Upload Updated Ntbk:
--Upload OHOL Ntbk here: /Users/msurnam@wsgc.com/2020/order/DTC_SS/e2e_OrderHeader_OrderLine_SS

-- COMMAND ----------

--Backup SQL script files. Upload new scripts to designated path.

-- COMMAND ----------

-- DBTITLE 1,Release the Triggers that were Paused:
/*
ORDER_HEADER_DMDIV_AGG_L2_SNOWFLAKE.ORDER_HEADER_DMDIV_AGG  (Completes by 11am in mrng)

a.TIMEBASED_DTC_INGEST_DECOUPLE Give advisory that 11am run will be skipped on deployment day
a.HOURLY_ORDER_POSLOG_L2
b.DAILY_OPTIMIZE_ORDER_LOC_ITM
c.DAILY_RMS_STR_SLS                                        
d.DAILY_RJ_ORDER_L1_INGEST 
e.DAILY_CUSTOMER_ORDER_HEADER_INGEST_L2_SNOWFLAKE
f.SALESFLASH_AGGREGATION (runs at midnight. If around this time, pause this)
g.DAILY_PKMS_HUB_FULFILLMENT_L1_L2_SNOWFLAKE
h.DAILY_PKMS_DC_FULFILLMENT_L1_L2_SNOWFLAKE
i. HOURLY_CHEETAH_EXTRACT (trigger name)

*/


--Release these after uploading SQL and running all pplns
