   MERGE INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."LOCATION" TGT USING
    (
   SELECT A.LOCATION_KEY AS MERGE_KEY, A.* FROM "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."FRANCHISE_STORE_HIERARCHY_SF" A
   UNION
   SELECT NULL AS MERGE_KEY, B.* FROM "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."FRANCHISE_STORE_HIERARCHY_SF" B
    )STG  ON TGT.LOCATION_KEY = STG.MERGE_KEY
           WHEN MATCHED AND TGT.LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000' THEN
       UPDATE SET
           LAST_EFFECTIVE_TS = dateadd(SECOND, - 1, STG.FIRST_EFFECTIVE_TS),
         UPDATE_TS = STG.UPDATE_TS
        WHEN NOT MATCHED AND MERGE_KEY IS NULL 
        THEN INSERT(LOCATION_KEY
                    ,LOCATION_ID
                    ,SOURCE_LOCATION_ID
                    ,SOURCE_SYSTEM
                    ,CONCEPT_CD
                    ,CONCEPT_DESC
                    ,DISTRICT_KEY
                    ,DISTRICT_ID
                    ,DISTRICT_DESC
                    ,REGION_KEY
                    ,REGION_ID
                    ,REGION_DESC
                    ,CHANNEL_CD
                    ,CHANNEL_DESC
                    ,COMPANY_CD
                    ,COMPANY_DESC
                    ,LOCATION_TYPE_CD
                    ,COUNTRY_CD
                    ,COUNTRY_SUBDIVISION_CD
                    ,STATE_CD
                    ,CURRENCY_CD
                    ,VIRTUAL_WAREHOUSE_CD
                    ,PHYSICAL_WAREHOUSE_CD
                    ,FIRST_EFFECTIVE_TS
                    ,LAST_EFFECTIVE_TS
                    ,LOCATION_DESC
                    ,DISPLAY_NAME
                    ,MALL_NAME
                    ,SHORT_NAME
                    ,MANAGER_NAME
                    ,ADDRESS_LINE_1
                    ,ADDRESS_LINE_2
                    ,ADDRESS_LINE_3
                    ,CITY
                    ,COUNTY
                    ,POSTAL_CD
                    ,ADDRESS_VERIFICATION_STATUS
                    ,CLASSIFICATION
                    ,LATTITUDE_NBR
                    ,LONGITUDE_NBR
                    ,TIME_ZONE
                    ,PHONE_COUNTRY_CODE
                    ,PHONE_NBR
                    ,PHONE_EXTENSION
                    ,PHONE_TYPE
                    ,EMAIL_ADDRESS
                    ,FAX_COUNTRY_CODE
                    ,FAX_NBR
                    ,FAX_EXTENSION
                    ,PICKUP_LOCATION_CD
                    ,PICKUP_ENABLED_FLAG
                    ,OUTLET_FLAG
                    ,POPUP_FLAG
                    ,STORE_IN_STORE_FLAG
                    ,SHIP_TO_STORE_ENABLED_FLAG
                    ,STOCKHOLD_FLAG
                    ,OPEN_DT
                    ,CLOSE_DT
                    ,TOTAL_AREA
                    ,SELLING_AREA
                    ,LINEAR_DISTANCE
                    ,PROMOTION_ZONE_CD
                    ,PROMOTION_ZONE_DESC
                    ,DEFAULT_WH
                    ,BREAK_PAC_FLAG
                    ,FRANCHISE_CD
                    ,MARKETING_CONCEPT_CD
                    ,INSERT_TS
                    ,UPDATE_TS)
             VALUES(STG.LOCATION_KEY
                     ,STG.LOCATION_ID
                     ,STG.SOURCE_LOCATION_ID
                     ,STG.SOURCE_SYSTEM
                     ,STG.CONCEPT_CD
                     ,STG.CONCEPT_DESC
                     ,STG.DISTRICT_KEY
                     ,STG.DISTRICT_ID
                     ,STG.DISTRICT_DESC
                     ,STG.REGION_KEY
                     ,STG.REGION_ID
                     ,STG.REGION_DESC
                     ,STG.CHANNEL_CD
                     ,STG.CHANNEL_DESC
                     ,STG.COMPANY_CD
                     ,STG.COMPANY_DESC
                     ,STG.LOCATION_TYPE_CD
                     ,STG.COUNTRY_CD
                     ,STG.COUNTRY_SUBDIVISION_CD
                     ,STG.STATE_CD
                     ,STG.CURRENCY_CD
                     ,STG.VIRTUAL_WAREHOUSE_CD
                     ,STG.PHYSICAL_WAREHOUSE_CD
                     ,STG.FIRST_EFFECTIVE_TS
                     ,STG.LAST_EFFECTIVE_TS
                     ,STG.LOCATION_DESC
                     ,STG.DISPLAY_NAME
                     ,STG.MALL_NAME
                     ,STG.SHORT_NAME
                     ,STG.MANAGER_NAME
                     ,STG.ADDRESS_LINE_1
                     ,STG.ADDRESS_LINE_2
                     ,STG.ADDRESS_LINE_3
                     ,STG.CITY
                     ,STG.COUNTY
                     ,STG.POSTAL_CD
                     ,STG.ADDRESS_VERIFICATION_STATUS
                     ,STG.CLASSIFICATION
                     ,STG.LATTITUDE_NBR
                     ,STG.LONGITUDE_NBR
                     ,STG.TIME_ZONE
                     ,STG.PHONE_COUNTRY_CODE
                     ,STG.PHONE_NBR
                     ,STG.PHONE_EXTENSION
                     ,STG.PHONE_TYPE
                     ,STG.EMAIL_ADDRESS
                     ,STG.FAX_COUNTRY_CODE
                     ,STG.FAX_NBR
                     ,STG.FAX_EXTENSION
                     ,STG.PICKUP_LOCATION_CD
                     ,STG.PICKUP_ENABLED_FLAG
                     ,STG.OUTLET_FLAG
                     ,STG.POPUP_FLAG
                     ,STG.STORE_IN_STORE_FLAG
                     ,STG.SHIP_TO_STORE_ENABLED_FLAG
                     ,STG.STOCKHOLD_FLAG
                     ,STG.OPEN_DT
                     ,STG.CLOSE_DT
                     ,STG.TOTAL_AREA
                     ,STG.SELLING_AREA
                     ,STG.LINEAR_DISTANCE
                     ,STG.PROMOTION_ZONE_CD
                     ,STG.PROMOTION_ZONE_DESC
                     ,STG.DEFAULT_WH
                     ,STG.BREAK_PAC_FLAG
                     ,STG.FRANCHISE_CD
                     ,STG.MARKETING_CONCEPT_CD
                     ,STG.INSERT_TS
                     ,STG.UPDATE_TS)                   