--Create Target & Stage Table


/* 

Load config json files to this path:

dbfs:/FileStore/tables/config/rms_upc_barcode/cost_susp_sup_detail_loc/


create or replace table PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE_DETAIL
  ( VENDOR_COST_CHANGE_DETAIL_KEY NUMBER(38,0) NOT NULL,
  VENDOR_COST_CHANGE_KEY NUMBER(38,0) NOT NULL,
  VENDOR_COST_CHANGE_ID VARCHAR(16777216),
  VENDOR_KEY NUMBER(38,0),
  VENDOR_ID VARCHAR(16777216),
  LOCATION_KEY NUMBER(38,0),
  LOCATION_ID VARCHAR(16777216),
  LOCATION_TYPE_CD VARCHAR(16777216),
  CONCEPT_CD VARCHAR(16777216) NOT NULL,
  ITEM_KEY NUMBER(38,0),
  ITEM_ID VARCHAR(16777216),
  ITEM_DEPARTMENT_KEY NUMBER(38,0),
  ITEM_DEPARTMENT_ID VARCHAR(16777216),
  ITEM_DEPARTMENT_DESC VARCHAR(16777216),
  ITEM_DIVISION_KEY NUMBER(38,0),
  ITEM_DIVISION_ID VARCHAR(16777216),
  ITEM_DIVISION_DESC VARCHAR(16777216),
  MARKET_CD VARCHAR(16777216),
  FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
  LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
  ORIGIN_COUNTRY_CD VARCHAR(16777216),
  BRACKET_VALUE_1_AMT NUMBER(15,4),
  BRACKET_UOM_1 VARCHAR(16777216),
  BRACKET_VALUE_2_AMT NUMBER(15,4),
  UNIT_COST_AMT NUMBER(15,4), 
  RECALCULATE_ORDER_FLAG VARCHAR(16777216), 
  DEFAULT_BRACKET_FLAG VARCHAR(16777216),
  VENDOR_DEPT_SEQ_NBR NUMBER(38,0),
  INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
  UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
   );
   
   
      
create or replace table PROD_EDAP_STAGE_DB.PROD_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_STG2
  (VENDOR_COST_CHANGE_DETAIL_KEY NUMBER(38,0) NOT NULL,
  VENDOR_COST_CHANGE_KEY NUMBER(38,0) NOT NULL,
  VENDOR_COST_CHANGE_ID VARCHAR(16777216),
  VENDOR_KEY NUMBER(38,0),
  VENDOR_ID VARCHAR(16777216),
  LOCATION_KEY NUMBER(38,0),
  LOCATION_ID VARCHAR(16777216),  
  LOCATION_TYPE_CD VARCHAR(16777216),
  CONCEPT_CD VARCHAR(16777216) NOT NULL,
  ITEM_KEY NUMBER(38,0),
  ITEM_ID VARCHAR(16777216),
  ITEM_DEPARTMENT_KEY NUMBER(38,0),
  ITEM_DEPARTMENT_ID VARCHAR(16777216),
  ITEM_DEPARTMENT_DESC VARCHAR(16777216),
  ITEM_DIVISION_KEY NUMBER(38,0),
  ITEM_DIVISION_ID VARCHAR(16777216),
  ITEM_DIVISION_DESC VARCHAR(16777216),
  MARKET_CD VARCHAR(16777216),
  FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
  LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
  ORIGIN_COUNTRY_CD VARCHAR(16777216),
  BRACKET_VALUE_1_AMT NUMBER(15,4),
  BRACKET_UOM_1 VARCHAR(16777216),
  BRACKET_VALUE_2_AMT NUMBER(15,4),
  UNIT_COST_AMT NUMBER(15,4), 
  RECALCULATE_ORDER_FLAG VARCHAR(16777216), 
  DEFAULT_BRACKET_FLAG VARCHAR(16777216),
  VENDOR_DEPT_SEQ_NBR NUMBER(38,0),
  INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
  UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL);

   */



insert into PROD_EDAP_L1_DB.PROD_EDAP_L1_TABLES.DATA_PIPELINE_CONFIG 
values (
4,
'UPC_BARCODE',
9,
'UPC_BARCODE_COST_SUSP_SUSP_DETAIL_LOC',
1,
'RMS_COST_SUSP_SUP_DETAIL_LOC_INGEST',
1,
1,
'CREATE OR REPLACE VIEW #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_L1_ASSIGNS
  AS (
  SELECT
      cast(-1 as bigint) as VENDOR_COST_CHANGE_DETAIL_KEY,
      cast(-1 as bigint) as VENDOR_COST_CHANGE_KEY,
      TRIM(to_varchar(COST_CHANGE)) as VENDOR_COST_CHANGE_ID,
      cast(-1 as bigint) as VENDOR_KEY,
      TRIM(to_varchar(SUPPLIER)) as VENDOR_ID,
      cast(-1 as bigint) as LOCATION_KEY,
      LPAD(TRIM(CAST(LOC AS STRING)),GREATEST(LENGTH(LOC),4),0) AS LOCATION_ID,
      TRIM(to_varchar(LOC_TYPE)) as LOCATION_TYPE_CD,
      TRIM(to_varchar(\'NA\')) as CONCEPT_CD,
      cast(-1 as bigint) as ITEM_KEY,
      TRIM(to_varchar(ITEM)) as ITEM_ID,
      cast(-1 as bigint) as ITEM_DEPARTMENT_KEY,
      LPAD(TRIM(CAST(DEPT AS STRING)),GREATEST(LENGTH(DEPT),4),0) as ITEM_DEPARTMENT_ID,
      TRIM(to_varchar(\'NA\')) as ITEM_DEPARTMENT_DESC,
      cast(-1 as bigint) as ITEM_DIVISION_KEY,
      TRIM(to_varchar(\'NA\')) as ITEM_DIVISION_ID,
      TRIM(to_varchar(\'NA\')) as ITEM_DIVISION_DESC,
      TRIM(to_varchar(\'NA\')) as MARKET_CD,
      TO_TIMESTAMP_NTZ(Current_timestamp()) as FIRST_EFFECTIVE_TS,
      TO_TIMESTAMP_NTZ(\'9999-12-31 23:59:59.000\') AS LAST_EFFECTIVE_TS,
      TRIM(to_varchar(ORIGIN_COUNTRY_ID)) as ORIGIN_COUNTRY_CD,
      TRIM(CAST(BRACKET_VALUE1 as NUMBER(15,4))) as BRACKET_VALUE_1_AMT,
      TRIM(to_varchar(BRACKET_UOM1)) as BRACKET_UOM_1,
      TRIM(CAST(BRACKET_VALUE2 as NUMBER(15,4))) as BRACKET_VALUE_2_AMT,
      TRIM(CAST(UNIT_COST as NUMBER(15,4))) as UNIT_COST_AMT,
      TRIM(to_varchar(RECALC_ORD_IND)) as RECALCULATE_ORDER_FLAG,
      TRIM(to_varchar(DEFAULT_BRACKET_IND)) as DEFAULT_BRACKET_FLAG,
      TRIM(CAST(SUP_DEPT_SEQ_NO as NUMBER(38,0))) as VENDOR_DEPT_SEQ_NBR,
      Current_timestamp() as INSERT_TS,
      Current_timestamp() as UPDATE_TS
  FROM #ENV#_EDAP_L1_DB.#ENV#_EDAP_L1_TABLES.L1_RMS_COST_SUSP_SUP_DETAIL_LOC_LANDING
);
  
CREATE OR REPLACE VIEW #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_CDC AS
 (
  SELECT
        COALESCE(TGT.VENDOR_COST_CHANGE_DETAIL_KEY, -1) AS VENDOR_COST_CHANGE_DETAIL_KEY,
      vccd.VENDOR_COST_CHANGE_KEY,
      vccd.VENDOR_COST_CHANGE_ID,
      vccd.VENDOR_KEY,
      vccd.VENDOR_ID,
      vccd.LOCATION_KEY,
      vccd.LOCATION_ID,
      vccd.LOCATION_TYPE_CD,
      vccd.CONCEPT_CD,
      vccd.ITEM_KEY,
      vccd.ITEM_ID,
      vccd.ITEM_DEPARTMENT_KEY,
      vccd.ITEM_DEPARTMENT_ID,
      vccd.ITEM_DEPARTMENT_DESC,
      vccd.ITEM_DIVISION_KEY,
      vccd.ITEM_DIVISION_ID,
      vccd.ITEM_DIVISION_DESC,
      vccd.MARKET_CD,
      vccd.FIRST_EFFECTIVE_TS,
      vccd.LAST_EFFECTIVE_TS,
      vccd.ORIGIN_COUNTRY_CD,
      vccd.BRACKET_VALUE_1_AMT,
      vccd.BRACKET_UOM_1,
      vccd.BRACKET_VALUE_2_AMT,
      vccd.UNIT_COST_AMT,
      vccd.RECALCULATE_ORDER_FLAG,
      vccd.DEFAULT_BRACKET_FLAG,
      vccd.VENDOR_DEPT_SEQ_NBR,
      vccd.INSERT_TS,
      vccd.UPDATE_TS
  FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_L1_ASSIGNS vccd
  LEFT OUTER JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE_DETAIL TGT
    ON TRIM(COALESCE(vccd.VENDOR_COST_CHANGE_ID,\'-1\')) = TRIM(COALESCE(TGT.VENDOR_COST_CHANGE_ID,\'-1\'))
         AND TRIM(COALESCE(vccd.VENDOR_ID,\'-1\')) = TRIM(COALESCE(TGT.VENDOR_ID,\'-1\'))
         AND TRIM(COALESCE(vccd.LOCATION_ID,\'-1\')) = TRIM(COALESCE(TGT.LOCATION_ID,\'-1\'))
         AND TRIM(COALESCE(vccd.ITEM_ID,\'-1\')) = TRIM(COALESCE(TGT.ITEM_ID,\'-1\'))
         AND TGT.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\'
  WHERE COALESCE(vccd.VENDOR_COST_CHANGE_ID,\'\') <> COALESCE(TGT.VENDOR_COST_CHANGE_ID,\'\')
        OR COALESCE(vccd.VENDOR_ID,\'\') <> COALESCE(TGT.VENDOR_ID,\'\')
        OR COALESCE(vccd.LOCATION_ID,\'0\') <> COALESCE(TGT.LOCATION_ID,\'0\')
        OR COALESCE(vccd.BRACKET_VALUE_1_AMT,\'0\') <> COALESCE(TGT.BRACKET_VALUE_1_AMT,\'0\')
        OR COALESCE(vccd.BRACKET_VALUE_2_AMT,\'0\') <> COALESCE(TGT.BRACKET_VALUE_2_AMT,\'0\')
        OR COALESCE(vccd.UNIT_COST_AMT,\'0\') <> COALESCE(TGT.UNIT_COST_AMT,\'0\')
        OR COALESCE(vccd.ITEM_DEPARTMENT_ID,\'0\') <> COALESCE(TGT.ITEM_DEPARTMENT_ID,\'0\')
        OR COALESCE(vccd.VENDOR_DEPT_SEQ_NBR,\'0\') <> COALESCE(TGT.VENDOR_DEPT_SEQ_NBR,\'0\')
        OR COALESCE(vccd.ORIGIN_COUNTRY_CD,\'\') <> COALESCE(TGT.ORIGIN_COUNTRY_CD,\'\')
        OR COALESCE(vccd.ITEM_ID,\'0\') <> COALESCE(TGT.ITEM_ID,\'0\')
        OR COALESCE(vccd.LOCATION_TYPE_CD,\'NA\') <> COALESCE(TGT.LOCATION_TYPE_CD,\'NA\')
        OR COALESCE(vccd.BRACKET_UOM_1,\'NA\') <> COALESCE(TGT.BRACKET_UOM_1,\'NA\')
        OR COALESCE(vccd.RECALCULATE_ORDER_FLAG,\'NA\') <> COALESCE(TGT.RECALCULATE_ORDER_FLAG,\'NA\')
        OR COALESCE(vccd.DEFAULT_BRACKET_FLAG,\'NA\') <> COALESCE(TGT.DEFAULT_BRACKET_FLAG,\'NA\')
   
   );

create or replace table #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_GEN_SK as (
SELECT
  CASE WHEN VENDOR_COST_CHANGE_DETAIL_KEY = - 1 THEN
             ROW_NUMBER() OVER (ORDER BY VENDOR_COST_CHANGE_ID) + COALESCE(MAX_VENDOR_COST_CHANGE_DETAIL_KEY, 0)
           ELSE VENDOR_COST_CHANGE_DETAIL_KEY
    END AS VENDOR_COST_CHANGE_DETAIL_KEY,
      VENDOR_COST_CHANGE_KEY,
      VENDOR_COST_CHANGE_ID,
      VENDOR_KEY,
      VENDOR_ID,
      LOCATION_KEY,
      LOCATION_ID,
      LOCATION_TYPE_CD,
      CONCEPT_CD,
      ITEM_KEY,
      ITEM_ID,
      ITEM_DEPARTMENT_KEY,
      ITEM_DEPARTMENT_ID,
      ITEM_DEPARTMENT_DESC,
      ITEM_DIVISION_KEY,
      ITEM_DIVISION_ID,
      ITEM_DIVISION_DESC,
      MARKET_CD,
      FIRST_EFFECTIVE_TS,
      LAST_EFFECTIVE_TS,
      ORIGIN_COUNTRY_CD,
      BRACKET_VALUE_1_AMT,
      BRACKET_UOM_1,
      BRACKET_VALUE_2_AMT,
      UNIT_COST_AMT,
      RECALCULATE_ORDER_FLAG,
      DEFAULT_BRACKET_FLAG,
      VENDOR_DEPT_SEQ_NBR,
      INSERT_TS,
      UPDATE_TS
 FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_CDC 
 CROSS JOIN (SELECT MAX(VENDOR_COST_CHANGE_DETAIL_KEY) AS MAX_VENDOR_COST_CHANGE_DETAIL_KEY FROM #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE_DETAIL
   WHERE VENDOR_COST_CHANGE_DETAIL_KEY <> - 1) TGT_MAX);

create or replace table #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_JOINS_GEN as
(
select vccd.VENDOR_COST_CHANGE_DETAIL_KEY as VENDOR_COST_CHANGE_DETAIL_KEY,
      vcc.VENDOR_COST_CHANGE_KEY as VENDOR_COST_CHANGE_KEY,
      vccd.VENDOR_COST_CHANGE_ID as VENDOR_COST_CHANGE_ID,
      vdr.VENDOR_KEY as VENDOR_KEY,
      vccd.VENDOR_ID as VENDOR_ID,
      loc.LOCATION_KEY as LOCATION_KEY,
      vccd.LOCATION_ID as LOCATION_ID,
      vccd.LOCATION_TYPE_CD as LOCATION_TYPE_CD,
      itm.CONCEPT_CD as CONCEPT_CD,
      itm.ITEM_KEY as ITEM_KEY,
      vccd.ITEM_ID as ITEM_ID,
      itm.ITEM_DEPARTMENT_KEY as ITEM_DEPARTMENT_KEY,
      vccd.ITEM_DEPARTMENT_ID as ITEM_DEPARTMENT_ID,
      itm.ITEM_DEPARTMENT_DESC as ITEM_DEPARTMENT_DESC,
      itm.ITEM_DIVISION_KEY as ITEM_DIVISION_KEY,
      itm.ITEM_DIVISION_ID as ITEM_DIVISION_ID,
      itm.ITEM_DIVISION_DESC as ITEM_DIVISION_DESC,
      itm.MARKET_CD as MARKET_CD,
      vccd.FIRST_EFFECTIVE_TS as FIRST_EFFECTIVE_TS,
      vccd.LAST_EFFECTIVE_TS as LAST_EFFECTIVE_TS,
      vccd.ORIGIN_COUNTRY_CD as ORIGIN_COUNTRY_CD,
      vccd.BRACKET_VALUE_1_AMT as BRACKET_VALUE_1_AMT,
      vccd.BRACKET_UOM_1 as BRACKET_UOM_1,
      vccd.BRACKET_VALUE_2_AMT as BRACKET_VALUE_2_AMT,
      vccd.UNIT_COST_AMT as UNIT_COST_AMT,
      vccd.RECALCULATE_ORDER_FLAG as RECALCULATE_ORDER_FLAG,
      vccd.DEFAULT_BRACKET_FLAG as DEFAULT_BRACKET_FLAG,
      vccd.VENDOR_DEPT_SEQ_NBR as VENDOR_DEPT_SEQ_NBR,
      vccd.INSERT_TS as INSERT_TS,
      vccd.UPDATE_TS as UPDATE_TS      
from #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_GEN_SK vccd 
 LEFT JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE vcc on vcc.VENDOR_COST_CHANGE_ID = vccd.VENDOR_COST_CHANGE_ID and vcc.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\'
 LEFT JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR vdr on vdr.VENDOR_ID = vccd.VENDOR_ID and vdr.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\'
 LEFT JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.LOCATION loc on loc.LOCATION_ID = vccd.LOCATION_ID and loc.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\'
 LEFT JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.ITEM itm on itm.ITEM_ID = vccd.ITEM_ID and itm.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\' and itm.MARKET_CD= \'USA\'
);


 INSERT OVERWRITE INTO #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_STG2
  SELECT 
      VENDOR_COST_CHANGE_DETAIL_KEY,
      VENDOR_COST_CHANGE_KEY,
      VENDOR_COST_CHANGE_ID,
      VENDOR_KEY,
      VENDOR_ID,
      LOCATION_KEY,
      LOCATION_ID,
      LOCATION_TYPE_CD,
      CONCEPT_CD,
      ITEM_KEY,
      ITEM_ID,
      ITEM_DEPARTMENT_KEY,
      ITEM_DEPARTMENT_ID,
      ITEM_DEPARTMENT_DESC,
      ITEM_DIVISION_KEY,
      ITEM_DIVISION_ID,
      ITEM_DIVISION_DESC,
      MARKET_CD,
      FIRST_EFFECTIVE_TS,
      LAST_EFFECTIVE_TS,
      ORIGIN_COUNTRY_CD,
      BRACKET_VALUE_1_AMT,
      BRACKET_UOM_1,
      BRACKET_VALUE_2_AMT,
      UNIT_COST_AMT,
      RECALCULATE_ORDER_FLAG,
      DEFAULT_BRACKET_FLAG,
      VENDOR_DEPT_SEQ_NBR,
      INSERT_TS,
      UPDATE_TS   
  FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_JOINS_GEN;
  
  MERGE INTO #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE_DETAIL TARGET 
 USING ( 
     SELECT STG.VENDOR_COST_CHANGE_DETAIL_KEY AS MERGE_KEY, STG.*
     FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_STG2 STG
     UNION 
     SELECT NULL AS MERGE_KEY, STG1.*
     FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_COST_CHANGE_DETAIL_STG2 STG1
    )STG2 ON TARGET.VENDOR_COST_CHANGE_DETAIL_KEY = STG2.MERGE_KEY AND TARGET.LOCATION_ID = STG2.LOCATION_ID AND TARGET.VENDOR_COST_CHANGE_ID = STG2.VENDOR_COST_CHANGE_ID AND TARGET.VENDOR_COST_CHANGE_KEY=STG2.VENDOR_COST_CHANGE_KEY AND TARGET.VENDOR_ID = STG2.VENDOR_ID AND TARGET.VENDOR_KEY=STG2.VENDOR_KEY and TARGET.LOCATION_KEY=STG2.LOCATION_KEY AND TARGET.ITEM_KEY=STG2.ITEM_KEY AND TARGET.ITEM_ID=STG2.ITEM_ID AND TARGET.ITEM_DEPARTMENT_KEY=STG2.ITEM_DEPARTMENT_KEY AND TARGET.ITEM_DEPARTMENT_ID=STG2.ITEM_DEPARTMENT_ID WHEN MATCHED AND TARGET.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\' THEN
   UPDATE SET TARGET.LAST_EFFECTIVE_TS = dateadd(SECOND, - 1, STG2.FIRST_EFFECTIVE_TS), TARGET.UPDATE_TS = STG2.UPDATE_TS
 WHEN NOT MATCHED AND MERGE_KEY IS NULL THEN
 INSERT (
      VENDOR_COST_CHANGE_DETAIL_KEY,
      VENDOR_COST_CHANGE_KEY,
      VENDOR_COST_CHANGE_ID,
      VENDOR_KEY,
      VENDOR_ID,
      LOCATION_KEY,
      LOCATION_ID,
      LOCATION_TYPE_CD,
      CONCEPT_CD,
      ITEM_KEY,
      ITEM_ID,
      ITEM_DEPARTMENT_KEY,
      ITEM_DEPARTMENT_ID,
      ITEM_DEPARTMENT_DESC,
      ITEM_DIVISION_KEY,
      ITEM_DIVISION_ID,
      ITEM_DIVISION_DESC,
      MARKET_CD,
      FIRST_EFFECTIVE_TS,
      LAST_EFFECTIVE_TS,
      ORIGIN_COUNTRY_CD,
      BRACKET_VALUE_1_AMT,
      BRACKET_UOM_1,
      BRACKET_VALUE_2_AMT,
      UNIT_COST_AMT,
      RECALCULATE_ORDER_FLAG,
      DEFAULT_BRACKET_FLAG,
      VENDOR_DEPT_SEQ_NBR,
      INSERT_TS,
      UPDATE_TS)
 VALUES 
 (    STG2.VENDOR_COST_CHANGE_DETAIL_KEY,
      STG2.VENDOR_COST_CHANGE_KEY,
      STG2.VENDOR_COST_CHANGE_ID,
      STG2.VENDOR_KEY,
      STG2.VENDOR_ID,
      STG2.LOCATION_KEY,
      STG2.LOCATION_ID,
      STG2.LOCATION_TYPE_CD,
      STG2.CONCEPT_CD,
      STG2.ITEM_KEY,
      STG2.ITEM_ID,
      STG2.ITEM_DEPARTMENT_KEY,
      STG2.ITEM_DEPARTMENT_ID,
      STG2.ITEM_DEPARTMENT_DESC,
      STG2.ITEM_DIVISION_KEY,
      STG2.ITEM_DIVISION_ID,
      STG2.ITEM_DIVISION_DESC,
      STG2.MARKET_CD,
      STG2.FIRST_EFFECTIVE_TS,
      STG2.LAST_EFFECTIVE_TS,
      STG2.ORIGIN_COUNTRY_CD,
      STG2.BRACKET_VALUE_1_AMT,
      STG2.BRACKET_UOM_1,
      STG2.BRACKET_VALUE_2_AMT,
      STG2.UNIT_COST_AMT,
      STG2.RECALCULATE_ORDER_FLAG,
      STG2.DEFAULT_BRACKET_FLAG,
      STG2.VENDOR_DEPT_SEQ_NBR,
      STG2.INSERT_TS,
      STG2.UPDATE_TS );',
'Y',
'R') ;




CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.VENDOR_COST_CHANGE_DETAIL_HIST AS 
 select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE_DETAIL ;


CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.VENDOR_COST_CHANGE_DETAIL AS 
 select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.VENDOR_COST_CHANGE_DETAIL where LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';