SELECT
    CASE WHEN INV_FCST_SITE_ATTR_CEA_KEY = - 1 THEN
        ROW_NUMBER() OVER (ORDER BY INV_FCST_SITE_ATTR_CEA_KEY, LOCATION_ID, CONCEPT_CD, SITE_ATTR_NM) + COALESCE(MAX_INV_FCST_SITE_ATTR_CEA_KEY, 0)
        ELSE INV_FCST_SITE_ATTR_CEA_KEY
    END AS INV_FCST_SITE_ATTR_CEA_KEY,
    LOCATION_KEY,
    LOCATION_ID,
    COALESCE(LOCATION_TYPE_CD, case when VIRTUAL_WAREHOUSE_KEY <> -1 then 'W' else null end) as LOCATION_TYPE_CD,
    CONCEPT_CD, 
    VIRTUAL_WAREHOUSE_KEY,
    VIRTUAL_WAREHOUSE_ID,
    VIRTUAL_WAREHOUSE_NM,
    SHIP_NODE_KEY,
    SHIP_NODE_ID,
    FIRST_EFFECTIVE_TS,
    LAST_EFFECTIVE_TS,
    SITE_ATTR_NM,
    SITE_ATTR_VAL,
    INSERT_TS,
    UPDATE_TS
 FROM STG_TEMP_INV_FCST_SITE_ATTR_CEA
 CROSS JOIN (
   SELECT
       MAX(INV_FCST_SITE_ATTR_CEA_KEY) AS MAX_INV_FCST_SITE_ATTR_CEA_KEY
   FROM
      L2_ANALYTICS_TABLES.INV_FCST_SITE_ATTR_CEA
   WHERE
      INV_FCST_SITE_ATTR_CEA_KEY <> - 1
  ) TGT_MAX