SELECT
    CASE WHEN INV_FCST_LOCATION_ITEM_GROUP_KEY = - 1 THEN
        ROW_NUMBER() OVER (ORDER BY INV_FCST_LOCATION_ITEM_GROUP_KEY, ITEM_ID,LOCATION_ID, CONCEPT_CD, INV_GROUP_NM) + COALESCE(MAX_INV_FCST_LOCATION_ITEM_GROUP_KEY, 0)
        ELSE INV_FCST_LOCATION_ITEM_GROUP_KEY
    END AS INV_FCST_LOCATION_ITEM_GROUP_KEY,
    CONCEPT_CD,
    LOCATION_KEY,
    LOCATION_ID,
    ITEM_KEY,
    ITEM_ID,
    MARKET_CD,
    INV_FCST_ITEM_PLACEHOLDER_KEY,
    INV_FCST_ITEM_PLACEHOLDER_ID,
    VIRTUAL_WAREHOUSE_KEY,
    VIRTUAL_WAREHOUSE_ID,
    VIRTUAL_WAREHOUSE_NM,
    SHIP_NODE_KEY,
    SHIP_NODE_ID,
    LastUpdatedDateTime,
    FIRST_EFFECTIVE_TS,
    LAST_EFFECTIVE_TS,
    PARENT_ITEM_PLACEHOLDER_CD,
    ITEM_PLACEHOLDER_DESC,
    ITEM_PLACEHOLDER_DEPT_DESC,
    INV_GROUP_NM,
    INV_GROUP_VAL,
    INSERT_TS,
    UPDATE_TS 
 FROM STG_TEMP_INV_FCST_LOCATION_ITEM_GROUP
 CROSS JOIN (
   SELECT
       MAX(INV_FCST_LOCATION_ITEM_GROUP_KEY) AS MAX_INV_FCST_LOCATION_ITEM_GROUP_KEY
   FROM
      L2_ANALYTICS_TABLES.INV_FCST_LOCATION_ITEM_GROUP
   WHERE
      INV_FCST_LOCATION_ITEM_GROUP_KEY <> - 1
  ) TGT_MAX

