MERGE INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INV_FCST_LOCATION_ITEM_GROUP" TARGET 
 USING ( 
     SELECT STG.INV_FCST_LOCATION_ITEM_GROUP_KEY AS MERGE_KEY, STG.*
     FROM "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INV_FCST_LOCATION_ITEM_GROUP_STAGE" STG
     UNION 
     SELECT NULL AS MERGE_KEY, STG1.*
     FROM "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INV_FCST_LOCATION_ITEM_GROUP_STAGE" STG1
    ) STG2 ON TARGET.INV_FCST_LOCATION_ITEM_GROUP_KEY = STG2.MERGE_KEY
 WHEN MATCHED AND TARGET.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000' THEN
	UPDATE SET TARGET.LAST_EFFECTIVE_TS = dateadd(SECOND, - 1, STG2.FIRST_EFFECTIVE_TS), TARGET.UPDATE_TS = STG2.UPDATE_TS
 WHEN NOT MATCHED AND MERGE_KEY IS NULL THEN
        INSERT (INV_FCST_LOCATION_ITEM_GROUP_KEY,
        CONCEPT_CD, 
        LOCATION_KEY,
        LOCATION_ID,            
        ITEM_KEY,       
        ITEM_ID,    
        MARKET_CD,
        INV_FCST_ITEM_PLACEHOLDER_KEY,
        INV_FCST_ITEM_PLACEHOLDER_ID,
        VIRTUAL_WAREHOUSE_KEY,
        VIRTUAL_WAREHOUSE_ID,
        VIRTUAL_WAREHOUSE_NM,
        SHIP_NODE_KEY,
        SHIP_NODE_ID,           
        FIRST_EFFECTIVE_TS,
        LAST_EFFECTIVE_TS,
        PARENT_ITEM_PLACEHOLDER_CD,
        ITEM_PLACEHOLDER_DESC,
        ITEM_PLACEHOLDER_DEPT_DESC,
        INV_GROUP_NM,
        INV_GROUP_VAL,  
        INSERT_TS,          
        UPDATE_TS )
        VALUES (STG2.INV_FCST_LOCATION_ITEM_GROUP_KEY,
        STG2.CONCEPT_CD,
        STG2.LOCATION_KEY,
        STG2.LOCATION_ID,			 	
        STG2.ITEM_KEY,		
        STG2.ITEM_ID,	
        STG2.MARKET_CD,
        STG2.INV_FCST_ITEM_PLACEHOLDER_KEY,
        STG2.INV_FCST_ITEM_PLACEHOLDER_ID,
        STG2.VIRTUAL_WAREHOUSE_KEY,
        STG2.VIRTUAL_WAREHOUSE_ID,
        STG2.VIRTUAL_WAREHOUSE_NM,
        STG2.SHIP_NODE_KEY,
        STG2.SHIP_NODE_ID,			
        STG2.FIRST_EFFECTIVE_TS,
        STG2.LAST_EFFECTIVE_TS,
        STG2.PARENT_ITEM_PLACEHOLDER_CD,
        STG2.ITEM_PLACEHOLDER_DESC,
        STG2.ITEM_PLACEHOLDER_DEPT_DESC,
        STG2.INV_GROUP_NM,
        STG2.INV_GROUP_VAL,	
        STG2.INSERT_TS,			
        STG2.UPDATE_TS);