/*
******************************************************************

******************************************************************
************************* Look Up *************************
******************************************************************

** Change   Date        Author    Description
**  --      ----------  --------  --------------------------------
**  01      04/10/2020  JAHMED1@WSGC.COM    SQL file created

******************************************************************

** Author			: JUNAID
** Team             : Godavari team (Supplychain_Godavari@wsgc.com)
** Create Date		: AUGUST, 2021
** Purpose      	: Apply mapping rules and generate necessary
					          columns for L2_ANALYTICS_TABLES.ORDER_LINE table

******************************************************************

** Source Table 	: L2_STAGE.ORDER_LINE_STG_TEMP
** Target View  	: OL_BACKFILL
** Lookup       	: L2_ANALYTICS_TABLES.ORDER_HEADER, ITEM, GLOBAL_SUBSIDIARY, GLOBAL_FULFILLMENT_STATUS, GLOBAL_COST_CENTER, PACK_ITEM

** Transformations	:
					: column concatenation and date conversion
					: static columns value insertions

******************************************************************
*/

SET spark.sql.broadcastTimeout = 2400;

CREATE OR REPLACE TEMPORARY VIEW OL_STG_VIEW1 AS ( 
SELECT 
cast(-1 as bigint) AS ORDER_LINE_KEY,
concat( STRING(INT(STG.TRANSACTION_ID)), '-', STRING(INT(STG.TRANSACTION_LINE_ID)) ) AS ORDER_LINE_ID, 
COALESCE(OH.ORDER_HEADER_KEY, -1) AS CHAINED_FROM_ORDER_HEADER_KEY,
STRING(INT(STG.TRANSACTION_ID)) AS CHAINED_FROM_ORDER_HEADER_ID,
'GLOBAL_NETSUITE' AS SOURCE_SYSTEM,
DATE_FORMAT(CAST(UNIX_TIMESTAMP(STG.TRANDATE,"yyyyMMdd") AS TIMESTAMP),"yyyy-MM-dd") AS ORDER_DT,
CAST(COALESCE(I.ITEM_KEY,-1) AS BIGINT) AS ITEM_KEY,
COALESCE(concat('N', STRING(INT(STG.ITEM_ID))), '-1') AS ORDER_ITEM_ID,
I.ITEM_TYPE_CD AS ORDER_ITEM_TYPE_CD,
I.ITEM_NAME AS ORDER_ITEM_NAME,
CAST(COALESCE(GCC.GLOBAL_COST_CENTER_KEY, -1) AS BIGINT) AS GLOBAL_COST_CENTER_KEY,
STRING(INT(STG.DEPARTMENT_ID)) AS GLOBAL_COST_CENTER_ID,
GCC.GLOBAL_COST_CENTER_DESC AS GLOBAL_COST_CENTER_DESC,
CAST(COALESCE(GS.GLOBAL_SUBSIDIARY_KEY,-1) AS BIGINT) AS GLOBAL_SUBSIDIARY_KEY,
STRING(INT(STG.SUBSIDIARY_ID)) AS GLOBAL_SUBSIDIARY_ID,
CAST(COALESCE(GFS.GLOBAL_FULFILLMENT_STATUS_KEY, -1) AS BIGINT) AS GLOBAL_FULFILLMENT_STATUS_KEY,
STRING(INT(STG.FULFILLMENT_STATUS_ID)) AS GLOBAL_FULFILLMENT_STATUS_CD,
CAST(COALESCE(PI.PACK_ITEM_KEY, -1) AS BIGINT) AS PACK_ITEM_KEY,
STRING(INT(STG.PACK_GROUP)) AS PACK_ITEM_ID,
CAST(STG.DATE_LAST_MODIFIED_GMT AS TIMESTAMP) AS FIRST_EFFECTIVE_TS,
CAST(UNIX_TIMESTAMP("9999-12-31 23:59:59.000+0000" , "yyyy-MM-dd HH:mm:ss.SSS") AS TIMESTAMP) AS LAST_EFFECTIVE_TS,
INT(STG.ITEM_COUNT) AS ORDER_QTY,
CAST(STG.DISCOUNT_AMOUNT AS DECIMAL(15,2)) AS EXTENDED_DISCOUNT_AMT,
CAST(STG.AMOUNT AS DECIMAL(15,2)) AS LINE_TOTAL_AMT,
DATE_FORMAT(CAST(UNIX_TIMESTAMP(STG.DATE_CLOSED,"yyyyMMdd") AS TIMESTAMP),"yyyy-MM-dd") AS GLOBAL_PO_CLOSED_DT,
INT(STG.QUANTITY_RECEIVED_IN_SHIPMENT) AS SHIPPED_QTY,
CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss.000') AS TIMESTAMP) AS INSERT_TS,
CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss.000') AS TIMESTAMP) AS UPDATE_TS 
  FROM L2_STAGE.ORDER_LINE_STG_TEMP STG
  
    LEFT OUTER JOIN L2_ANALYTICS_TABLES.ORDER_HEADER OH
      ON CAST(CAST(STG.TRANSACTION_ID AS INT) AS STRING) = OH.ORDER_HEADER_ID AND OH.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' AND OH.SOURCE_SYSTEM = 'GLOBAL_NETSUITE'
    
    LEFT OUTER JOIN L2_ANALYTICS_TABLES.ITEM I
      ON concat('N', STRING(INT(STG.ITEM_ID)) = I.ITEM_ID AND I.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' AND I.MARKET_CD = 'GLOBAL' AND I.SOURCE_SYSTEM = 'GLOBAL_NETSUITE'
      
    LEFT OUTER JOIN L2_ANALYTICS_TABLES.GLOBAL_SUBSIDIARY GS
      ON CAST(CAST(STG.SUBSIDIARY_ID AS INT)AS STRING) = GS.GLOBAL_SUBSIDIARY_ID  AND GS.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000'
      
    LEFT OUTER JOIN L2_ANALYTICS_TABLES.GLOBAL_FULFILLMENT_STATUS GFS
      ON CAST(CAST(STG.FULFILLMENT_STATUS_ID AS INT)AS STRING) = GFS.GLOBAL_FULFILLMENT_STATUS_ID AND GFS.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' 
      
    LEFT OUTER JOIN L2_ANALYTICS_TABLES.GLOBAL_COST_CENTER GCC
      ON CAST(CAST(STG.DEPARTMENT_ID AS INT)AS STRING) = GCC.GLOBAL_COST_CENTER_ID AND GCC.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' 
      
    LEFT OUTER JOIN L2_ANALYTICS_TABLES.PACK_ITEM PI
      ON CAST(CAST(STG.PACK_GROUP AS INT)AS STRING) = PI.PACK_ID AND PI.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' 
);


/*
******************************************************************
** Author					: JAHMED1@WSGC.COM
** Create Date		: JULY, 2021
** Purpose      	: CDC for NETSUITE'S TRANSACTIONS data for ORDER_HEADER
******************************************************************
************************* Change History *************************
******************************************************************

** Change   Date        Author                 Description
**  --      ----------  --------             --------------------------------
**  01      24/07/2021  JAHMED1@WSGC.COM       SQL file created
**
******************************************************************
*/

CREATE OR REPLACE TEMPORARY VIEW OL_STG1_VIEW2 AS ( 
select 
    COALESCE(T.ORDER_LINE_KEY,-1) as ORDER_LINE_KEY,
    STG1.ORDER_LINE_ID,
    STG1.CHAINED_FROM_ORDER_HEADER_KEY,
    STG1.CHAINED_FROM_ORDER_HEADER_ID,
    STG1.SOURCE_SYSTEM,
    STG1.ORDER_DT,
    STG1.ITEM_KEY,
    STG1.ORDER_ITEM_ID,
    STG1.ORDER_ITEM_TYPE_CD,
    STG1.ORDER_ITEM_NAME,
    STG1.GLOBAL_COST_CENTER_KEY,
    STG1.GLOBAL_COST_CENTER_ID,
    STG1.GLOBAL_COST_CENTER_DESC,
    STG1.GLOBAL_SUBSIDIARY_KEY,
    STG1.GLOBAL_SUBSIDIARY_ID,
    STG1.GLOBAL_FULFILLMENT_STATUS_KEY,
    STG1.GLOBAL_FULFILLMENT_STATUS_CD,
    STG1.PACK_ITEM_KEY,
    STG1.PACK_ITEM_ID,
    STG1.FIRST_EFFECTIVE_TS,
    STG1.LAST_EFFECTIVE_TS,
    STG1.ORDER_QTY,
    STG1.EXTENDED_DISCOUNT_AMT,
    STG1.LINE_TOTAL_AMT,
    STG1.GLOBAL_PO_CLOSED_DT,
    STG1.SHIPPED_QTY,
    STG1.INSERT_TS,
    STG1.UPDATE_TS
    FROM  OL_STG_VIEW1 STG1 
 LEFT OUTER JOIN L2_ANALYTICS_TABLES.ORDER_LINE T
	ON STG1.ORDER_LINE_ID = T.ORDER_LINE_ID AND STG1.CHAINED_FROM_ORDER_HEADER_ID = T.CHAINED_FROM_ORDER_HEADER_ID AND T.SOURCE_SYSTEM='GLOBAL_NETSUITE' AND T.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' 
WHERE
	  T.ORDER_LINE_KEY is null
      OR COALESCE(STG1.ORDER_DT,'') <> COALESCE(T.ORDER_DT,'')
      OR COALESCE(STG1.ORDER_ITEM_ID, '') <> COALESCE(T.ORDER_ITEM_ID, '')
      OR COALESCE(STG1.GLOBAL_COST_CENTER_ID, '') <> COALESCE(T.GLOBAL_COST_CENTER_ID, '')
      OR COALESCE(STG1.GLOBAL_SUBSIDIARY_ID, '') <> COALESCE(T.GLOBAL_SUBSIDIARY_ID, '')
      OR COALESCE(STG1.GLOBAL_FULFILLMENT_STATUS_CD, '') <> COALESCE(T.GLOBAL_FULFILLMENT_STATUS_CD, '')  
      OR COALESCE(STG1.PACK_ITEM_ID, '') <> COALESCE(T.PACK_ITEM_ID,'')
      OR COALESCE(STG1.ORDER_QTY, 0) <> COALESCE(T.ORDER_QTY, 0)
      OR COALESCE(STG1.EXTENDED_DISCOUNT_AMT, 0.00) <> COALESCE(T.EXTENDED_DISCOUNT_AMT, 0.00)
      OR COALESCE(STG1.LINE_TOTAL_AMT, 0.00) <> COALESCE(T.LINE_TOTAL_AMT, 0.00)
      OR COALESCE(STG1.GLOBAL_PO_CLOSED_DT,'') <> COALESCE(T.GLOBAL_PO_CLOSED_DT,'')
      OR COALESCE(STG1.SHIPPED_QTY, 0) <> COALESCE(T.SHIPPED_QTY, 0)
);

/*
******************************************************************
** Author					: JAHMED1@WSGC.COM
** Create Date		: JULY, 2021
** Purpose      	: Generate surrogate keys for GLOBAL INVENTORY data 
******************************************************************
** Transformations	: Genarating surrogate keys on ORDER_LINE_KEY, ORDER_LINE_ID
******************************************************************
************************* Change History *************************
******************************************************************
** Change   Date        Author                 Description
**  --      ----------  --------             --------------------------------
**  01      24/07/2021  JAHMED1@WSGC.COM       SQL file created
******************************************************************
*/

CREATE OR REPLACE TEMPORARY VIEW OL_STG1_VIEW3 AS (
  SELECT
    CASE WHEN ORDER_LINE_KEY = -1 THEN
             ROW_NUMBER() OVER (ORDER BY ORDER_LINE_KEY, ORDER_LINE_ID) + COALESCE(MAX_ORDER_LINE_KEY, 0) 
        ELSE ORDER_LINE_KEY
    END AS ORDER_LINE_KEY,
    ORDER_LINE_ID,
    CHAINED_FROM_ORDER_HEADER_KEY,
    CHAINED_FROM_ORDER_HEADER_ID,
    SOURCE_SYSTEM,
    ORDER_DT,
    ITEM_KEY,
    ORDER_ITEM_ID,
    ORDER_ITEM_TYPE_CD,
    ORDER_ITEM_NAME,
    GLOBAL_COST_CENTER_KEY,
    GLOBAL_COST_CENTER_ID,
    GLOBAL_COST_CENTER_DESC,
    GLOBAL_SUBSIDIARY_KEY,
    GLOBAL_SUBSIDIARY_ID,
    GLOBAL_FULFILLMENT_STATUS_KEY,
    GLOBAL_FULFILLMENT_STATUS_CD,
    PACK_ITEM_KEY,
    PACK_ITEM_ID,
    FIRST_EFFECTIVE_TS,
    LAST_EFFECTIVE_TS,
    ORDER_QTY,
    EXTENDED_DISCOUNT_AMT,
    LINE_TOTAL_AMT,
    GLOBAL_PO_CLOSED_DT,
    SHIPPED_QTY,
    INSERT_TS,
    UPDATE_TS
  FROM OL_STG1_VIEW2
  CROSS JOIN
  (SELECT MAX(ORDER_LINE_KEY) AS MAX_ORDER_LINE_KEY FROM L2_ANALYTICS_TABLES.ORDER_LINE WHERE ORDER_LINE_KEY <> -1) TGT_MAX
);


/*
******************************************************************
** Author					: JAHMED1@WSGC.COM
** Create Date		: JULY, 2021
** Purpose      	: Creating the backfill view
******************************************************************
************************* Change History *************************
******************************************************************

** Change   Date        Author                 Description
**  --      ----------  --------             --------------------------------
**  01      27/07/2021  JAHMED1@WSGC.COM       SQL file created
**
******************************************************************
*/

CREATE OR REPLACE TEMPORARY VIEW OL_BACKFILL AS ( 
SELECT 
  ORDER_LINE_KEY
, ORDER_LINE_ID
, -1 AS ORDER_HEADER_KEY
, CHAINED_FROM_ORDER_HEADER_KEY
, CHAINED_FROM_ORDER_HEADER_ID
, -1 AS CHAINED_FROM_ORDER_LINE_KEY
, NULL AS CHAINED_FROM_ORDER_LINE_ID
, SOURCE_SYSTEM
, ORDER_DT
, NULL AS ORDER_LINE_TYPE
, NULL AS PRIME_LINE_SEQ_NBR
, NULL AS SUB_LINE_SEQ_NBR
, -1 AS LINKED_ORDER_HEADER_KEY
, NULL AS LINKED_ORDER_HEADER_ID
, -1 AS LINKED_ORDER_LINE_KEY
, NULL AS LINKED_ORDER_LINE_ID
, ITEM_KEY
, ORDER_ITEM_ID
, ORDER_ITEM_TYPE_CD
, ORDER_ITEM_NAME
, -1 AS GIFT_REGISTRY_KEY
, NULL AS GIFT_REGISTRY_ID
, GLOBAL_SUBSIDIARY_KEY
, GLOBAL_SUBSIDIARY_ID
, GLOBAL_COST_CENTER_KEY
, GLOBAL_COST_CENTER_ID
, GLOBAL_COST_CENTER_DESC
, GLOBAL_FULFILLMENT_STATUS_KEY
, GLOBAL_FULFILLMENT_STATUS_CD
, PACK_ITEM_KEY
, PACK_ITEM_ID
, FIRST_EFFECTIVE_TS
, LAST_EFFECTIVE_TS
, NULL AS UPC_CD
, NULL AS KIT_CD
, NULL AS KIT_QTY
, NULL AS PRODUCT_LINE
, NULL AS BUNDLE_PARENT_ORDER_LINE_ID
, ORDER_QTY
, NULL AS ORIG_ORDER_QTY
, NULL AS ACT_SALE_UNIT_PRICE_AMT
, NULL AS REG_SALE_UNIT_PRICE_AMT
, NULL AS EXTENDED_AMT
, EXTENDED_DISCOUNT_AMT
, NULL AS TAX_AMT
, NULL AS TAXABLE_AMT
, NULL AS GIFT_CARD_AMT
, NULL AS GIFTWRAP_CHARGE_AMT
, LINE_TOTAL_AMT
, NULL AS MERCHANDISE_CHARGE_AMT
, NULL AS MONO_PZ_CHARGE_AMT
, NULL AS MISC_CHARGE_AMT
, NULL AS SHIPPING_HANDLING_CHARGE_AMT
, NULL AS SHIPPING_SURCHARGE_AMT
, NULL AS DONATION_AMT
, NULL AS ASSOCIATE_ID
, NULL AS ENTRY_METHOD
, NULL AS GIFT_MESSAGE
, NULL AS VOID_FLAG
, NULL AS REPO_FLAG
, NULL AS TAXABLE_FLAG
, NULL AS PICKABLE_FLAG
, NULL AS GIFT_FLAG
, NULL AS HOLD_FLAG
, NULL AS HOLD_REASON
, NULL AS ORIG_BACKORDER_FLAG
, NULL AS SUBORDER_COMPLEXITY_GROUP_ID
, NULL AS DELIVERY_CHOICE
, NULL AS MODIFICATION_REASON_CD
, NULL AS MODIFICATION_REASON_CD_DESC
, NULL AS RETURN_ACTION_CD
, NULL AS RETURN_ACTION
, NULL AS RETURN_REASON_CD
, NULL AS RETURN_REASON_DESC
, NULL AS RETURN_SUB_REASON_CD
, NULL AS SHIP_TO_FIRST_NAME
, NULL AS SHIP_TO_MIDDLE_NAME
, NULL AS SHIP_TO_LAST_NAME
, NULL AS SHIP_TO_ADDRESS_LINE_1
, NULL AS SHIP_TO_ADDRESS_LINE_2
, NULL AS SHIP_TO_CITY
, NULL AS SHIP_TO_STATE_OR_PROV
, NULL AS SHIP_TO_POSTAL_CD
, NULL AS SHIP_TO_COUNTRY
, NULL AS SHIP_TO_EMAIL_ADDRESS
, NULL AS SHIP_TO_PHONE_NBR
, NULL AS DELIVERY_METHOD
, NULL AS FULFILLMENT_TYPE
, NULL AS DTC_SUBORDER_NBR
, NULL AS ADDITIONAL_LINE_TYPE_CD
, NULL AS ORIG_CONFIRMED_QTY
, NULL AS RESKU_FLAG
, NULL AS CONSOLIDATOR_ADDRESS_CD
, NULL AS MERGE_NODE_CD
, NULL AS SHIP_NODE_CD
, NULL AS RECEIVING_NODE_CD
, NULL AS LEVEL_OF_SERVICE
, NULL AS CARRIER_SERVICE_CD
, NULL AS CARRIER_CD
, NULL AS ACCESS_POINT_CD
, NULL AS ACCESS_POINT_ID
, NULL AS ACCESS_POINT_NM
, NULL AS MINIMUM_SHIP_DT
, NULL AS REQUESTED_SHIP_DT
, NULL AS REQUESTED_DELIVERY_DT
, NULL AS EARLIEST_SCHEDULE_DT
, NULL AS EARLIEST_DELIVERY_DT
, NULL AS PROMISED_APPT_END_DT
, GLOBAL_PO_CLOSED_DT
, NULL AS CHANGED_DAYS_CNT
, NULL AS SPLIT_QTY
, SHIPPED_QTY
, NULL AS FILL_QTY
, NULL AS WEIGHTED_AVG_COST
, NULL AS DIRECT_SHIP_FLAG
, NULL AS UNIT_COST
, NULL AS LABOR_COST
, NULL AS LABOR_SKU
, NULL AS CUSTOMER_LEVEL_OF_SERVICE
, NULL AS RETURN_POLICY
, NULL AS RETURN_POLICY_CHECK_OVERRIDE_FLAG
, NULL AS PRODUCT_AVAILABILITY_DT
, NULL AS ECDD_OVERRIDDEN_FLAG
, NULL AS ECDD_INVOKED_FLAG
, NULL AS VAS_GIFT_WRAP_CD
, NULL AS VAS_MONO_FLAG
, NULL AS VAS_PZ_FLAG
, NULL AS BO_NOTIFICATION_NBR
, NULL AS BO_NOTIFICATION_TYPE_CD
, INSERT_TS
, UPDATE_TS 
from OL_STG1_VIEW3
);



         /* TRUNCATING THE STAGE TABLE AND REINSERTING THE DATA FROM OL_BACKFILL  */


         TRUNCATE TABLE L2_STAGE.NETSUITE_OL_STG; 
         INSERT INTO L2_STAGE.NETSUITE_OL_STG SELECT * FROM OL_BACKFILL; 
       /*
       ONE_TIME_INSERT ACTIVITY
       */

/*
******************************************************************
** Author					: JAHMED1@WSGC.COM
** Create Date		: JULY, 2021
** Purpose      	: Merging ORDER LINE data from stage table into L2 ORDER_LINE table
******************************************************************
************************* Change History *************************
******************************************************************

** Change   Date        Author                 Description
**  --      ----------  --------             --------------------------------
**  01      27/07/2021  JAHMED1@WSGC.COM       SQL file created
**
******************************************************************
*/

  MERGE INTO L2_ANALYTICS_TABLES.ORDER_LINE TARGET
 USING (
    SELECT STG.ORDER_LINE_KEY as MERGE_KEY, STG.*
        FROM L2_STAGE.NETSUITE_OL_STG STG
    UNION
    SELECT NULL as MERGE_KEY, STG1.*
        FROM  L2_STAGE.NETSUITE_OL_STG STG1) STG2 ON TARGET.ORDER_LINE_KEY = STG2.MERGE_KEY
    WHEN MATCHED AND TARGET.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000' THEN
        UPDATE SET TARGET.LAST_EFFECTIVE_TS = FROM_UNIXTIME (CAST(STG2.FIRST_EFFECTIVE_TS AS LONG) - 1), TARGET.UPDATE_TS = STG2.UPDATE_TS
    WHEN NOT MATCHED AND MERGE_KEY IS NULL THEN
   INSERT
    (ORDER_LINE_KEY,
    ORDER_LINE_ID,
    ORDER_HEADER_KEY,
    CHAINED_FROM_ORDER_HEADER_KEY,
    CHAINED_FROM_ORDER_HEADER_ID,
    CHAINED_FROM_ORDER_LINE_KEY,
    CHAINED_FROM_ORDER_LINE_ID,
    SOURCE_SYSTEM,
    ORDER_DT,
    ORDER_LINE_TYPE,
    PRIME_LINE_SEQ_NBR,
    SUB_LINE_SEQ_NBR,
    LINKED_ORDER_HEADER_KEY,
    LINKED_ORDER_HEADER_ID,
    LINKED_ORDER_LINE_KEY,
    LINKED_ORDER_LINE_ID,
    ITEM_KEY,
    ORDER_ITEM_ID,
    ORDER_ITEM_TYPE_CD,
    ORDER_ITEM_NAME,
    GIFT_REGISTRY_KEY,
    GIFT_REGISTRY_ID,
    GLOBAL_SUBSIDIARY_KEY,
    GLOBAL_SUBSIDIARY_ID, 
    GLOBAL_COST_CENTER_KEY,
    GLOBAL_COST_CENTER_ID,
    GLOBAL_COST_CENTER_DESC,
    GLOBAL_FULFILLMENT_STATUS_KEY,
    GLOBAL_FULFILLMENT_STATUS_CD,
    PACK_ITEM_KEY,
    PACK_ITEM_ID,		
    FIRST_EFFECTIVE_TS,
    LAST_EFFECTIVE_TS,
    UPC_CD,
    KIT_CD,
    KIT_QTY,
    PRODUCT_LINE,
    BUNDLE_PARENT_ORDER_LINE_ID,
    ORDER_QTY,
    ORIG_ORDER_QTY,
    ACT_SALE_UNIT_PRICE_AMT,
    REG_SALE_UNIT_PRICE_AMT,
    EXTENDED_AMT,
    EXTENDED_DISCOUNT_AMT,
    TAX_AMT,
    TAXABLE_AMT,
    GIFT_CARD_AMT,
    GIFTWRAP_CHARGE_AMT,
    LINE_TOTAL_AMT,
    MERCHANDISE_CHARGE_AMT,
    MONO_PZ_CHARGE_AMT,
    MISC_CHARGE_AMT,
    SHIPPING_HANDLING_CHARGE_AMT,
    SHIPPING_SURCHARGE_AMT,
    DONATION_AMT,
    ASSOCIATE_ID,
    ENTRY_METHOD,
    GIFT_MESSAGE,
    VOID_FLAG,
    REPO_FLAG,
    TAXABLE_FLAG,
    PICKABLE_FLAG,
    GIFT_FLAG,
    HOLD_FLAG,
    HOLD_REASON,
    ORIG_BACKORDER_FLAG,
    SUBORDER_COMPLEXITY_GROUP_ID,
    DELIVERY_CHOICE,
    MODIFICATION_REASON_CD,
    MODIFICATION_REASON_CD_DESC,
    RETURN_ACTION_CD,
    RETURN_ACTION,
    RETURN_REASON_CD,
    RETURN_REASON_DESC,
    RETURN_SUB_REASON_CD,
    SHIP_TO_FIRST_NAME,
    SHIP_TO_MIDDLE_NAME,
    SHIP_TO_LAST_NAME,
    SHIP_TO_ADDRESS_LINE_1,
    SHIP_TO_ADDRESS_LINE_2,
    SHIP_TO_CITY,
    SHIP_TO_STATE_OR_PROV,
    SHIP_TO_POSTAL_CD,
    SHIP_TO_COUNTRY,
    SHIP_TO_EMAIL_ADDRESS,
    SHIP_TO_PHONE_NBR,
    DELIVERY_METHOD,
    FULFILLMENT_TYPE,
    DTC_SUBORDER_NBR,
    ADDITIONAL_LINE_TYPE_CD,
    ORIG_CONFIRMED_QTY,
    RESKU_FLAG,
    CONSOLIDATOR_ADDRESS_CD,
    MERGE_NODE_CD,
    SHIP_NODE_CD,
    RECEIVING_NODE_CD,
    LEVEL_OF_SERVICE,
    CARRIER_SERVICE_CD,
    CARRIER_CD,
    ACCESS_POINT_CD,
    ACCESS_POINT_ID,
    ACCESS_POINT_NM,
    MINIMUM_SHIP_DT,
    REQUESTED_SHIP_DT,
    REQUESTED_DELIVERY_DT,
    EARLIEST_SCHEDULE_DT,
    EARLIEST_DELIVERY_DT,
    PROMISED_APPT_END_DT,
    GLOBAL_PO_CLOSED_DT,
    CHANGED_DAYS_CNT,
    SPLIT_QTY,
    SHIPPED_QTY,
    FILL_QTY,
    WEIGHTED_AVG_COST,
    DIRECT_SHIP_FLAG,
    UNIT_COST,
    LABOR_COST,
    LABOR_SKU,
    CUSTOMER_LEVEL_OF_SERVICE,
    RETURN_POLICY,
    RETURN_POLICY_CHECK_OVERRIDE_FLAG,
    PRODUCT_AVAILABILITY_DT,
    ECDD_OVERRIDDEN_FLAG,
    ECDD_INVOKED_FLAG,
    VAS_GIFT_WRAP_CD,
    VAS_MONO_FLAG,
    VAS_PZ_FLAG,
    BO_NOTIFICATION_NBR,
    BO_NOTIFICATION_TYPE_CD,
    INSERT_TS,
    UPDATE_TS)
    VALUES
    (STG2.ORDER_LINE_KEY,
    STG2.ORDER_LINE_ID,
    STG2.ORDER_HEADER_KEY,
    STG2.CHAINED_FROM_ORDER_HEADER_KEY,
    STG2.CHAINED_FROM_ORDER_HEADER_ID,
    STG2.CHAINED_FROM_ORDER_LINE_KEY,
    STG2.CHAINED_FROM_ORDER_LINE_ID,
    STG2.SOURCE_SYSTEM,
    STG2.ORDER_DT,
    STG2.ORDER_LINE_TYPE,
    STG2.PRIME_LINE_SEQ_NBR,
    STG2.SUB_LINE_SEQ_NBR,
    STG2.LINKED_ORDER_HEADER_KEY,
    STG2.LINKED_ORDER_HEADER_ID,
    STG2.LINKED_ORDER_LINE_KEY,
    STG2.LINKED_ORDER_LINE_ID,
    STG2.ITEM_KEY,
    STG2.ORDER_ITEM_ID,
    STG2.ORDER_ITEM_TYPE_CD,
    STG2.ORDER_ITEM_NAME,
    STG2.GIFT_REGISTRY_KEY,
    STG2.GIFT_REGISTRY_ID,
    STG2.GLOBAL_SUBSIDIARY_KEY,
    STG2.GLOBAL_SUBSIDIARY_ID, 
    STG2.GLOBAL_COST_CENTER_KEY,
    STG2.GLOBAL_COST_CENTER_ID,
    STG2.GLOBAL_COST_CENTER_DESC,
    STG2.GLOBAL_FULFILLMENT_STATUS_KEY,
    STG2.GLOBAL_FULFILLMENT_STATUS_CD,
    STG2.PACK_ITEM_KEY,
    STG2.PACK_ITEM_ID,		
    STG2.FIRST_EFFECTIVE_TS,
    STG2.LAST_EFFECTIVE_TS,
    STG2.UPC_CD,
    STG2.KIT_CD,
    STG2.KIT_QTY,
    STG2.PRODUCT_LINE,
    STG2.BUNDLE_PARENT_ORDER_LINE_ID,
    STG2.ORDER_QTY,
    STG2.ORIG_ORDER_QTY,
    STG2.ACT_SALE_UNIT_PRICE_AMT,
    STG2.REG_SALE_UNIT_PRICE_AMT,
    STG2.EXTENDED_AMT,
    STG2.EXTENDED_DISCOUNT_AMT,
    STG2.TAX_AMT,
    STG2.TAXABLE_AMT,
    STG2.GIFT_CARD_AMT,
    STG2.GIFTWRAP_CHARGE_AMT,
    STG2.LINE_TOTAL_AMT,
    STG2.MERCHANDISE_CHARGE_AMT,
    STG2.MONO_PZ_CHARGE_AMT,
    STG2.MISC_CHARGE_AMT,
    STG2.SHIPPING_HANDLING_CHARGE_AMT,
    STG2.SHIPPING_SURCHARGE_AMT,
    STG2.DONATION_AMT,
    STG2.ASSOCIATE_ID,
    STG2.ENTRY_METHOD,
    STG2.GIFT_MESSAGE,
    STG2.VOID_FLAG,
    STG2.REPO_FLAG,
    STG2.TAXABLE_FLAG,
    STG2.PICKABLE_FLAG,
    STG2.GIFT_FLAG,
    STG2.HOLD_FLAG,
    STG2.HOLD_REASON,
    STG2.ORIG_BACKORDER_FLAG,
    STG2.SUBORDER_COMPLEXITY_GROUP_ID,
    STG2.DELIVERY_CHOICE,
    STG2.MODIFICATION_REASON_CD,
    STG2.MODIFICATION_REASON_CD_DESC,
    STG2.RETURN_ACTION_CD,
    STG2.RETURN_ACTION,
    STG2.RETURN_REASON_CD,
    STG2.RETURN_REASON_DESC,
    STG2.RETURN_SUB_REASON_CD,
    STG2.SHIP_TO_FIRST_NAME,
    STG2.SHIP_TO_MIDDLE_NAME,
    STG2.SHIP_TO_LAST_NAME,
    STG2.SHIP_TO_ADDRESS_LINE_1,
    STG2.SHIP_TO_ADDRESS_LINE_2,
    STG2.SHIP_TO_CITY,
    STG2.SHIP_TO_STATE_OR_PROV,
    STG2.SHIP_TO_POSTAL_CD,
    STG2.SHIP_TO_COUNTRY,
    STG2.SHIP_TO_EMAIL_ADDRESS,
    STG2.SHIP_TO_PHONE_NBR,
    STG2.DELIVERY_METHOD,
    STG2.FULFILLMENT_TYPE,
    STG2.DTC_SUBORDER_NBR,
    STG2.ADDITIONAL_LINE_TYPE_CD,
    STG2.ORIG_CONFIRMED_QTY,
    STG2.RESKU_FLAG,
    STG2.CONSOLIDATOR_ADDRESS_CD,
    STG2.MERGE_NODE_CD,
    STG2.SHIP_NODE_CD,
    STG2.RECEIVING_NODE_CD,
    STG2.LEVEL_OF_SERVICE,
    STG2.CARRIER_SERVICE_CD,
    STG2.CARRIER_CD,
    STG2.ACCESS_POINT_CD,
    STG2.ACCESS_POINT_ID,
    STG2.ACCESS_POINT_NM,
    STG2.MINIMUM_SHIP_DT,
    STG2.REQUESTED_SHIP_DT,
    STG2.REQUESTED_DELIVERY_DT,
    STG2.EARLIEST_SCHEDULE_DT,
    STG2.EARLIEST_DELIVERY_DT,
    STG2.PROMISED_APPT_END_DT,
    STG2.GLOBAL_PO_CLOSED_DT,
    STG2.CHANGED_DAYS_CNT,
    STG2.SPLIT_QTY,
    STG2.SHIPPED_QTY,
    STG2.FILL_QTY,
    STG2.WEIGHTED_AVG_COST,
    STG2.DIRECT_SHIP_FLAG,
    STG2.UNIT_COST,
    STG2.LABOR_COST,
    STG2.LABOR_SKU,
    STG2.CUSTOMER_LEVEL_OF_SERVICE,
    STG2.RETURN_POLICY,
    STG2.RETURN_POLICY_CHECK_OVERRIDE_FLAG,
    STG2.PRODUCT_AVAILABILITY_DT,
    STG2.ECDD_OVERRIDDEN_FLAG,
    STG2.ECDD_INVOKED_FLAG,
    STG2.VAS_GIFT_WRAP_CD,
    STG2.VAS_MONO_FLAG,
    STG2.VAS_PZ_FLAG,
    STG2.BO_NOTIFICATION_NBR,
    STG2.BO_NOTIFICATION_TYPE_CD,
    STG2.INSERT_TS,
    STG2.UPDATE_TS);



    /*
    ** Source Table   : L2_ANALYTICS_TABLES.ORDER_LINE
    ** Target Table    : L2_ANALYTICS_TABLES.ORDER_LINE
    ** Optimize delta data for  LAST_EFFECTIVE_TS
    **
    */
    set spark.databricks.delta.optimize.zorder.checkStatsCollection.enabled =false;

        OPTIMIZE L2_ANALYTICS_TABLES.ORDER_LINE ZORDER BY LAST_EFFECTIVE_TS  ;