--Create Target & Stage Table


/* 

Load config json files to this path:

dbfs:/FileStore/tables/config/rms_upc_barcode/sup_attributes/

create or replace table PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.VENDOR_ATTR(
VENDOR_ATTR_KEY NUMBER(38,0) NOT NULL,
VENDOR_KEY NUMBER(38,0) ,
VENDOR_ID VARCHAR(16777216),
PLM_VENDOR_ID VARCHAR(16777216),  
FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
WSI_CLAIM_FLAG  VARCHAR(16777216),
WSI_FEDEX_NBR VARCHAR(16777216),  
WSI_FEDEX_NBR_PRIMARY_FLAG VARCHAR(16777216), 
WSI_GENERATED_FEDEX_NBR VARCHAR(16777216),  
WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG VARCHAR(16777216), 
WSI_VENDOR_FEDEX_NBR VARCHAR(16777216), 
WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG VARCHAR(16777216),  
WSI_PAPER_DELIVERY_METHOD_DESC VARCHAR(16777216), 
WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG VARCHAR(16777216), 
WSI_EMAIL_DELIVERY_METHOD_DESC VARCHAR(16777216), 
WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG VARCHAR(16777216), 
WSI_FAX_DELIVERY_METHOD_DESC VARCHAR(16777216), 
WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG VARCHAR(16777216), 
WSI_DIRECT_SHIP_FLAG VARCHAR(16777216),
WSI_INT_DIRECT_SHIP_FLAG VARCHAR(16777216),   
WSI_PZ_FLAG VARCHAR(16777216),  
SPS_STOCK_PO_FLAG VARCHAR(16777216),    
SPS_STOCK_PO_ACTIVE_DT DATE,  
SPS_DS_PARCEL_PO_FLAG VARCHAR(16777216),  
SPS_DS_PARCEL_ACTIVE_DT DATE, 
SPS_DS_FURNITURE_PO_FLAG VARCHAR(16777216), 
SPS_DS_FURNITURE_ACTIVE_DT DATE,  
BARCODE_ENABLED_FLAG VARCHAR(16777216), 
BARCODE_UPDATE_USER_ID VARCHAR(16777216), 
BARCODE_UPDATE_TS TIMESTAMP_NTZ(9),
LAST_UPDATE_USER_ID VARCHAR(16777216), 
LAST_UPDATE_TS TIMESTAMP_NTZ(9),
INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL
); 
   
   
      
create or replace table PROD_EDAP_STAGE_DB.PROD_EDAP_STAGE_TABLES.VENDOR_ATTR_STG2
  (VENDOR_ATTR_KEY NUMBER(38,0) NOT NULL,
VENDOR_KEY NUMBER(38,0) ,
VENDOR_ID VARCHAR(16777216),
PLM_VENDOR_ID VARCHAR(16777216),  
FIRST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
LAST_EFFECTIVE_TS TIMESTAMP_NTZ(9) NOT NULL,
WSI_CLAIM_FLAG  VARCHAR(16777216),
WSI_FEDEX_NBR VARCHAR(16777216),  
WSI_FEDEX_NBR_PRIMARY_FLAG VARCHAR(16777216), 
WSI_GENERATED_FEDEX_NBR VARCHAR(16777216),  
WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG VARCHAR(16777216), 
WSI_VENDOR_FEDEX_NBR VARCHAR(16777216), 
WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG VARCHAR(16777216),  
WSI_PAPER_DELIVERY_METHOD_DESC VARCHAR(16777216), 
WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG VARCHAR(16777216), 
WSI_EMAIL_DELIVERY_METHOD_DESC VARCHAR(16777216), 
WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG VARCHAR(16777216), 
WSI_FAX_DELIVERY_METHOD_DESC VARCHAR(16777216), 
WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG VARCHAR(16777216), 
WSI_DIRECT_SHIP_FLAG VARCHAR(16777216),
WSI_INT_DIRECT_SHIP_FLAG VARCHAR(16777216),   
WSI_PZ_FLAG VARCHAR(16777216),  
SPS_STOCK_PO_FLAG VARCHAR(16777216),    
SPS_STOCK_PO_ACTIVE_DT DATE,  
SPS_DS_PARCEL_PO_FLAG VARCHAR(16777216),  
SPS_DS_PARCEL_ACTIVE_DT DATE, 
SPS_DS_FURNITURE_PO_FLAG VARCHAR(16777216), 
SPS_DS_FURNITURE_ACTIVE_DT DATE,  
BARCODE_ENABLED_FLAG VARCHAR(16777216), 
BARCODE_UPDATE_USER_ID VARCHAR(16777216), 
BARCODE_UPDATE_TS TIMESTAMP_NTZ(9),
LAST_UPDATE_USER_ID VARCHAR(16777216), 
LAST_UPDATE_TS TIMESTAMP_NTZ(9),
INSERT_TS TIMESTAMP_NTZ(9) NOT NULL,
UPDATE_TS TIMESTAMP_NTZ(9) NOT NULL);

   */



insert into PROD_EDAP_L1_DB.PROD_EDAP_L1_TABLES.DATA_PIPELINE_CONFIG  
values (
4,
'UPC_BARCODE',
10,
'UPC_BARCODE_SUP_ATTRIBUTES',
1,
'RMS_SUP_ATTRIBUTES_INGEST',
1,
1,
'CREATE OR REPLACE VIEW #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_L1_ASSIGNS
  AS (
  SELECT
      cast(-1 as bigint) as VENDOR_ATTR_KEY,
      cast(-1 as bigint) as VENDOR_KEY,
      TRIM(to_varchar(SUPPLIER)) as VENDOR_ID,
      TRIM(to_varchar(PLM_SUPPLIER_ID)) as PLM_VENDOR_ID,
      TO_TIMESTAMP_NTZ(Current_timestamp()) as FIRST_EFFECTIVE_TS,
      TO_TIMESTAMP_NTZ(\'9999-12-31 23:59:59.000\') AS LAST_EFFECTIVE_TS,
      TRIM(to_varchar(WSI_CLAIM_FLAG)) as WSI_CLAIM_FLAG,
      TRIM(to_varchar(WSI_FEDEX_NO)) as WSI_FEDEX_NBR,
      TRIM(to_varchar(WSI_FEDEX_NO_PRIM_IND)) as WSI_FEDEX_NBR_PRIMARY_FLAG,
      TRIM(to_varchar(WSI_GEN_FEDEX_NO)) as WSI_GENERATED_FEDEX_NBR,
      TRIM(to_varchar(WSI_GEN_FEDEX_NO_PRIM_IND)) as WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      TRIM(to_varchar(WSI_VENDOR_FEDEX_NO)) as WSI_VENDOR_FEDEX_NBR,
      TRIM(to_varchar(WSI_VENDOR_FEDEX_NO_PRIM_IND)) as WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      TRIM(to_varchar(WSI_PAPER_DELIVERY_METHOD)) as WSI_PAPER_DELIVERY_METHOD_DESC,
      TRIM(to_varchar(WSI_PAPER_DEL_METHD_PRIM_IND)) as WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      TRIM(to_varchar(WSI_EMAIL_DELIVERY_METHOD)) as WSI_EMAIL_DELIVERY_METHOD_DESC,
      TRIM(to_varchar(WSI_EMAIL_DEL_METHD_PRIM_IND)) as WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      TRIM(to_varchar(WSI_FAX_DELIVERY_METHOD)) as WSI_FAX_DELIVERY_METHOD_DESC,
      TRIM(to_varchar(WSI_FAX_DEL_METHD_PRIM_IND)) as WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      TRIM(to_varchar(WSI_DIRECT_SHIP_IND)) as WSI_DIRECT_SHIP_FLAG,
      TRIM(to_varchar(WSI_INT_DIRECT_SHIP_IND)) as WSI_INT_DIRECT_SHIP_FLAG,
      TRIM(to_varchar(WSI_PERSONALIZATION_IND)) as WSI_PZ_FLAG,
      TRIM(to_varchar(SPS_STOCK_PO)) as SPS_STOCK_PO_FLAG,
      TRIM(to_varchar(SPS_STOCK_PO_ACTIVE_DATE)) as SPS_STOCK_PO_ACTIVE_DT,
      TRIM(to_varchar(SPS_DS_PARCEL_PO)) as SPS_DS_PARCEL_PO_FLAG,
      TRIM(to_date(SPS_DS_PARCEL_ACTIVE_DATE)) as SPS_DS_PARCEL_ACTIVE_DT,
      TRIM(to_varchar(SPS_DS_FURNITURE_PO)) as SPS_DS_FURNITURE_PO_FLAG,
      TRIM(to_date(SPS_DS_FURNITURE_ACTIVE_DATE)) as SPS_DS_FURNITURE_ACTIVE_DT,
      TRIM(to_varchar(BARCODE_ENABLED)) as BARCODE_ENABLED_FLAG,
      TRIM(to_varchar(BARCODE_UPDATE_ID)) as BARCODE_UPDATE_USER_ID,
      TO_TIMESTAMP_NTZ(BARCODE_UPDATE_TS) as BARCODE_UPDATE_TS,
      TRIM(to_varchar(LAST_DS_UPDATE_ID)) as LAST_UPDATE_USER_ID,
      TO_TIMESTAMP_NTZ(LAST_DS_UPDATE_DATE) as LAST_UPDATE_TS,
      Current_timestamp() as INSERT_TS,
      Current_timestamp() as UPDATE_TS
  FROM #ENV#_EDAP_L1_DB.#ENV#_EDAP_L1_TABLES.L1_RMS_SUP_ATTRIBUTES_LANDING
      );
  
CREATE OR REPLACE VIEW #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_CDC AS
 (
  SELECT
    COALESCE(TGT.VENDOR_ATTR_KEY, -1) AS VENDOR_ATTR_KEY,
      vattr.VENDOR_KEY,
      vattr.VENDOR_ID,
      vattr.PLM_VENDOR_ID,
      vattr.FIRST_EFFECTIVE_TS,
      vattr.LAST_EFFECTIVE_TS,
      vattr.WSI_CLAIM_FLAG,
      vattr.WSI_FEDEX_NBR,
      vattr.WSI_FEDEX_NBR_PRIMARY_FLAG,
      vattr.WSI_GENERATED_FEDEX_NBR,
      vattr.WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      vattr.WSI_VENDOR_FEDEX_NBR,
      vattr.WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      vattr.WSI_PAPER_DELIVERY_METHOD_DESC,
      vattr.WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      vattr.WSI_EMAIL_DELIVERY_METHOD_DESC,
      vattr.WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      vattr.WSI_FAX_DELIVERY_METHOD_DESC,
      vattr.WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      vattr.WSI_DIRECT_SHIP_FLAG,
      vattr.WSI_INT_DIRECT_SHIP_FLAG,
      vattr.WSI_PZ_FLAG,
      vattr.SPS_STOCK_PO_FLAG,
      vattr.SPS_STOCK_PO_ACTIVE_DT,
      vattr.SPS_DS_PARCEL_PO_FLAG,
      vattr.SPS_DS_PARCEL_ACTIVE_DT,
      vattr.SPS_DS_FURNITURE_PO_FLAG,
      vattr.SPS_DS_FURNITURE_ACTIVE_DT,
      vattr.BARCODE_ENABLED_FLAG,
      vattr.BARCODE_UPDATE_USER_ID,
      vattr.BARCODE_UPDATE_TS,
      vattr.LAST_UPDATE_USER_ID,
      vattr.LAST_UPDATE_TS,
      vattr.INSERT_TS,
      vattr.UPDATE_TS
  FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_L1_ASSIGNS vattr
  LEFT OUTER JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_ATTR TGT
         ON TRIM(COALESCE(vattr.VENDOR_ID,\'-1\')) = TRIM(COALESCE(TGT.VENDOR_ID,\'-1\'))
         AND TGT.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\'
  WHERE COALESCE(vattr.VENDOR_ID,\'\') <> COALESCE(TGT.VENDOR_ID,\'\')
        OR COALESCE(vattr.PLM_VENDOR_ID,\'0\') <> COALESCE(TGT.PLM_VENDOR_ID,\'0\')
        OR COALESCE(vattr.WSI_CLAIM_FLAG,\'0\') <> COALESCE(TGT.WSI_CLAIM_FLAG,\'0\')
        OR COALESCE(vattr.WSI_FEDEX_NBR,\'0\') <> COALESCE(TGT.WSI_FEDEX_NBR,\'0\')
        OR COALESCE(vattr.WSI_FEDEX_NBR_PRIMARY_FLAG,\'NA\') <> COALESCE(TGT.WSI_FEDEX_NBR_PRIMARY_FLAG,\'NA\')
        OR COALESCE(vattr.WSI_GENERATED_FEDEX_NBR,\'NA\') <> COALESCE(TGT.WSI_GENERATED_FEDEX_NBR,\'NA\')
    OR COALESCE(vattr.WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,\'NA\') <> COALESCE(TGT.WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,\'NA\')
        OR COALESCE(vattr.WSI_VENDOR_FEDEX_NBR,\'NA\') <> COALESCE(TGT.WSI_VENDOR_FEDEX_NBR,\'NA\')
        OR COALESCE(vattr.WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,\'NA\') <> COALESCE(TGT.WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,\'NA\')
        OR COALESCE(vattr.WSI_PAPER_DELIVERY_METHOD_DESC,\'0\') <> COALESCE(TGT.WSI_PAPER_DELIVERY_METHOD_DESC,\'0\')
        OR COALESCE(vattr.WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,\'0\') <> COALESCE(TGT.WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,\'0\')
        OR COALESCE(vattr.WSI_EMAIL_DELIVERY_METHOD_DESC,\'0\') <> COALESCE(TGT.WSI_EMAIL_DELIVERY_METHOD_DESC,\'0\')
        OR COALESCE(vattr.WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,\'0\') <> COALESCE(TGT.WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,\'0\')
        OR COALESCE(vattr.WSI_FAX_DELIVERY_METHOD_DESC,\'0\') <> COALESCE(TGT.WSI_FAX_DELIVERY_METHOD_DESC,\'0\')
        OR COALESCE(vattr.WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,\'0\') <> COALESCE(TGT.WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,\'0\')
        OR COALESCE(vattr.WSI_DIRECT_SHIP_FLAG,\'0\') <> COALESCE(TGT.WSI_DIRECT_SHIP_FLAG,\'0\')
        OR COALESCE(vattr.WSI_INT_DIRECT_SHIP_FLAG,\'0\') <> COALESCE(TGT.WSI_INT_DIRECT_SHIP_FLAG,\'0\')
        OR COALESCE(vattr.WSI_PZ_FLAG,\'0\') <> COALESCE(TGT.WSI_PZ_FLAG,\'0\')
        OR COALESCE(vattr.SPS_STOCK_PO_FLAG,\'0\') <> COALESCE(TGT.SPS_STOCK_PO_FLAG,\'0\')
        OR COALESCE(vattr.SPS_STOCK_PO_ACTIVE_DT,current_date()) <> COALESCE(TGT.SPS_STOCK_PO_ACTIVE_DT,current_date())
        OR COALESCE(vattr.SPS_DS_PARCEL_PO_FLAG,\'0\') <> COALESCE(TGT.SPS_DS_PARCEL_PO_FLAG,\'0\')
        OR COALESCE(vattr.SPS_DS_PARCEL_ACTIVE_DT,current_date()) <> COALESCE(TGT.SPS_DS_PARCEL_ACTIVE_DT,current_date())
        OR COALESCE(vattr.SPS_DS_FURNITURE_PO_FLAG,\'0\') <> COALESCE(TGT.SPS_DS_FURNITURE_PO_FLAG,\'0\')
        OR COALESCE(vattr.SPS_DS_FURNITURE_ACTIVE_DT,current_date()) <> COALESCE(TGT.SPS_DS_FURNITURE_ACTIVE_DT,current_date())
        OR COALESCE(vattr.BARCODE_ENABLED_FLAG,\'0\') <> COALESCE(TGT.BARCODE_ENABLED_FLAG,\'0\')
        OR COALESCE(vattr.BARCODE_UPDATE_USER_ID,\'0\') <> COALESCE(TGT.BARCODE_UPDATE_USER_ID,\'0\')
        OR COALESCE(vattr.BARCODE_UPDATE_TS,current_timestamp()) <> COALESCE(TGT.BARCODE_UPDATE_TS,current_timestamp())
        OR COALESCE(vattr.LAST_UPDATE_USER_ID,\'0\') <> COALESCE(TGT.LAST_UPDATE_USER_ID,\'0\')
        OR COALESCE(vattr.LAST_UPDATE_TS,current_timestamp()) <> COALESCE(TGT.LAST_UPDATE_TS,current_timestamp()) 
   );

create or replace table #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_GEN_SK as (
SELECT
  CASE WHEN VENDOR_ATTR_KEY = - 1 THEN
             ROW_NUMBER() OVER (ORDER BY VENDOR_ID) + COALESCE(MAX_VENDOR_ATTR_KEY, 0)
           ELSE VENDOR_ATTR_KEY
    END AS VENDOR_ATTR_KEY,
      VENDOR_KEY,
      VENDOR_ID,
      PLM_VENDOR_ID,
      FIRST_EFFECTIVE_TS,
      LAST_EFFECTIVE_TS,
      WSI_CLAIM_FLAG,
      WSI_FEDEX_NBR,
      WSI_FEDEX_NBR_PRIMARY_FLAG,
      WSI_GENERATED_FEDEX_NBR,
      WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      WSI_VENDOR_FEDEX_NBR,
      WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      WSI_PAPER_DELIVERY_METHOD_DESC,
      WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_EMAIL_DELIVERY_METHOD_DESC,
      WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_FAX_DELIVERY_METHOD_DESC,
      WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_DIRECT_SHIP_FLAG,
      WSI_INT_DIRECT_SHIP_FLAG,
      WSI_PZ_FLAG,
      SPS_STOCK_PO_FLAG,
      SPS_STOCK_PO_ACTIVE_DT,
      SPS_DS_PARCEL_PO_FLAG,
      SPS_DS_PARCEL_ACTIVE_DT,
      SPS_DS_FURNITURE_PO_FLAG,
      SPS_DS_FURNITURE_ACTIVE_DT,
      BARCODE_ENABLED_FLAG,
      BARCODE_UPDATE_USER_ID,
      BARCODE_UPDATE_TS,
      LAST_UPDATE_USER_ID,
      LAST_UPDATE_TS,
      INSERT_TS,
      UPDATE_TS
 FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_CDC 
 CROSS JOIN (SELECT MAX(VENDOR_ATTR_KEY) AS MAX_VENDOR_ATTR_KEY FROM #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_ATTR
   WHERE VENDOR_ATTR_KEY <> - 1) TGT_MAX);

create or replace table #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_JOINS_GEN as
(
select vattr.VENDOR_ATTR_KEY as VENDOR_ATTR_KEY,
      vdr.VENDOR_KEY as VENDOR_KEY,
      vattr.VENDOR_ID as VENDOR_ID,
      vattr.PLM_VENDOR_ID as PLM_VENDOR_ID,
      vattr.FIRST_EFFECTIVE_TS as FIRST_EFFECTIVE_TS,
      vattr.LAST_EFFECTIVE_TS as LAST_EFFECTIVE_TS,
      vattr.WSI_CLAIM_FLAG as WSI_CLAIM_FLAG,
      vattr.WSI_FEDEX_NBR as WSI_FEDEX_NBR,
      vattr.WSI_FEDEX_NBR_PRIMARY_FLAG as WSI_FEDEX_NBR_PRIMARY_FLAG,
      vattr.WSI_GENERATED_FEDEX_NBR as WSI_GENERATED_FEDEX_NBR,
      vattr.WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG as WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      vattr.WSI_VENDOR_FEDEX_NBR as WSI_VENDOR_FEDEX_NBR,
      vattr.WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG as WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      vattr.WSI_PAPER_DELIVERY_METHOD_DESC as WSI_PAPER_DELIVERY_METHOD_DESC,
      vattr.WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG as WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      vattr.WSI_EMAIL_DELIVERY_METHOD_DESC as WSI_EMAIL_DELIVERY_METHOD_DESC,
      vattr.WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG as WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      vattr.WSI_FAX_DELIVERY_METHOD_DESC as WSI_FAX_DELIVERY_METHOD_DESC,
      vattr.WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG as WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      vattr.WSI_DIRECT_SHIP_FLAG as WSI_DIRECT_SHIP_FLAG,
      vattr.WSI_INT_DIRECT_SHIP_FLAG as WSI_INT_DIRECT_SHIP_FLAG,
      vattr.WSI_PZ_FLAG as WSI_PZ_FLAG,
      vattr.SPS_STOCK_PO_FLAG as SPS_STOCK_PO_FLAG,
      vattr.SPS_STOCK_PO_ACTIVE_DT as SPS_STOCK_PO_ACTIVE_DT,
      vattr.SPS_DS_PARCEL_PO_FLAG as SPS_DS_PARCEL_PO_FLAG,
      vattr.SPS_DS_PARCEL_ACTIVE_DT as SPS_DS_PARCEL_ACTIVE_DT,
      vattr.SPS_DS_FURNITURE_PO_FLAG as SPS_DS_FURNITURE_PO_FLAG,
      vattr.SPS_DS_FURNITURE_ACTIVE_DT as SPS_DS_FURNITURE_ACTIVE_DT,
      vattr.BARCODE_ENABLED_FLAG as BARCODE_ENABLED_FLAG,
      vattr.BARCODE_UPDATE_USER_ID as BARCODE_UPDATE_USER_ID,
      vattr.BARCODE_UPDATE_TS as BARCODE_UPDATE_TS,
      vattr.LAST_UPDATE_USER_ID as LAST_UPDATE_USER_ID,
      vattr.LAST_UPDATE_TS as LAST_UPDATE_TS,
      vattr.INSERT_TS as INSERT_TS,
      vattr.UPDATE_TS as UPDATE_TS     
from #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_GEN_SK vattr 
 LEFT JOIN #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR vdr on vdr.VENDOR_ID = vattr.VENDOR_ID and vdr.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\'
);

 INSERT OVERWRITE INTO #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_STG2
  SELECT 
      VENDOR_ATTR_KEY,
      VENDOR_KEY,
      VENDOR_ID,
      PLM_VENDOR_ID,
      FIRST_EFFECTIVE_TS,
      LAST_EFFECTIVE_TS,
      WSI_CLAIM_FLAG,
      WSI_FEDEX_NBR,
      WSI_FEDEX_NBR_PRIMARY_FLAG,
      WSI_GENERATED_FEDEX_NBR,
      WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      WSI_VENDOR_FEDEX_NBR,
      WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      WSI_PAPER_DELIVERY_METHOD_DESC,
      WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_EMAIL_DELIVERY_METHOD_DESC,
      WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_FAX_DELIVERY_METHOD_DESC,
      WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_DIRECT_SHIP_FLAG,
      WSI_INT_DIRECT_SHIP_FLAG,
      WSI_PZ_FLAG,
      SPS_STOCK_PO_FLAG,
      SPS_STOCK_PO_ACTIVE_DT,
      SPS_DS_PARCEL_PO_FLAG,
      SPS_DS_PARCEL_ACTIVE_DT,
      SPS_DS_FURNITURE_PO_FLAG,
      SPS_DS_FURNITURE_ACTIVE_DT,
      BARCODE_ENABLED_FLAG,
      BARCODE_UPDATE_USER_ID,
      BARCODE_UPDATE_TS,
      LAST_UPDATE_USER_ID,
      LAST_UPDATE_TS,
      INSERT_TS,
      UPDATE_TS
  FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_JOINS_GEN;
  
  MERGE INTO #ENV#_EDAP_ANALYTICS_DB.#ENV#_EDAP_ANALYTICS_TABLES.VENDOR_ATTR TARGET 
 USING ( 
     SELECT STG.VENDOR_ATTR_KEY AS MERGE_KEY, STG.*
     FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_STG2 STG
     UNION 
     SELECT NULL AS MERGE_KEY, STG1.*
     FROM #ENV#_EDAP_STAGE_DB.#ENV#_EDAP_STAGE_TABLES.VENDOR_ATTR_STG2 STG1
    ) STG2 ON TARGET.VENDOR_ATTR_KEY = STG2.MERGE_KEY AND TARGET.VENDOR_ID = STG2.VENDOR_ID AND TARGET.VENDOR_KEY = STG2.VENDOR_KEY
 WHEN MATCHED AND TARGET.LAST_EFFECTIVE_TS = \'9999-12-31 23:59:59.000\' THEN
   UPDATE SET TARGET.LAST_EFFECTIVE_TS = dateadd(SECOND, - 1, STG2.FIRST_EFFECTIVE_TS), TARGET.UPDATE_TS = STG2.UPDATE_TS
 WHEN NOT MATCHED AND MERGE_KEY IS NULL THEN
 INSERT (
      VENDOR_ATTR_KEY,
      VENDOR_KEY,
      VENDOR_ID,
      PLM_VENDOR_ID,
      FIRST_EFFECTIVE_TS,
      LAST_EFFECTIVE_TS,
      WSI_CLAIM_FLAG,
      WSI_FEDEX_NBR,
      WSI_FEDEX_NBR_PRIMARY_FLAG,
      WSI_GENERATED_FEDEX_NBR,
      WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      WSI_VENDOR_FEDEX_NBR,
      WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      WSI_PAPER_DELIVERY_METHOD_DESC,
      WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_EMAIL_DELIVERY_METHOD_DESC,
      WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_FAX_DELIVERY_METHOD_DESC,
      WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      WSI_DIRECT_SHIP_FLAG,
      WSI_INT_DIRECT_SHIP_FLAG,
      WSI_PZ_FLAG,
      SPS_STOCK_PO_FLAG,
      SPS_STOCK_PO_ACTIVE_DT,
      SPS_DS_PARCEL_PO_FLAG,
      SPS_DS_PARCEL_ACTIVE_DT,
      SPS_DS_FURNITURE_PO_FLAG,
      SPS_DS_FURNITURE_ACTIVE_DT,
      BARCODE_ENABLED_FLAG,
      BARCODE_UPDATE_USER_ID,
      BARCODE_UPDATE_TS,
      LAST_UPDATE_USER_ID,
      LAST_UPDATE_TS,
      INSERT_TS,
      UPDATE_TS)
 VALUES 
 (    STG2.VENDOR_ATTR_KEY,
      STG2.VENDOR_KEY,
      STG2.VENDOR_ID,
      STG2.PLM_VENDOR_ID,
      STG2.FIRST_EFFECTIVE_TS,
      STG2.LAST_EFFECTIVE_TS,
      STG2.WSI_CLAIM_FLAG,
      STG2.WSI_FEDEX_NBR,
      STG2.WSI_FEDEX_NBR_PRIMARY_FLAG,
      STG2.WSI_GENERATED_FEDEX_NBR,
      STG2.WSI_GENERATED_FEDEX_NBR_PRIMARY_FLAG,
      STG2.WSI_VENDOR_FEDEX_NBR,
      STG2.WSI_VENDOR_FEDEX_NBR_PRIMARY_FLAG,
      STG2.WSI_PAPER_DELIVERY_METHOD_DESC,
      STG2.WSI_PAPER_DELIVERY_METHOD_PRIMARY_FLAG,
      STG2.WSI_EMAIL_DELIVERY_METHOD_DESC,
      STG2.WSI_EMAIL_DELIVERY_METHOD_PRIMARY_FLAG,
      STG2.WSI_FAX_DELIVERY_METHOD_DESC,
      STG2.WSI_FAX_DELIVERY_METHOD_PRIMARY_FLAG,
      STG2.WSI_DIRECT_SHIP_FLAG,
      STG2.WSI_INT_DIRECT_SHIP_FLAG,
      STG2.WSI_PZ_FLAG,
      STG2.SPS_STOCK_PO_FLAG,
      STG2.SPS_STOCK_PO_ACTIVE_DT,
      STG2.SPS_DS_PARCEL_PO_FLAG,
      STG2.SPS_DS_PARCEL_ACTIVE_DT,
      STG2.SPS_DS_FURNITURE_PO_FLAG,
      STG2.SPS_DS_FURNITURE_ACTIVE_DT,
      STG2.BARCODE_ENABLED_FLAG,
      STG2.BARCODE_UPDATE_USER_ID,
      STG2.BARCODE_UPDATE_TS,
      STG2.LAST_UPDATE_USER_ID,
      STG2.LAST_UPDATE_TS,
      STG2.INSERT_TS,
      STG2.UPDATE_TS );',
'Y',
'R') ;



CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.VENDOR_ATTR_HIST AS 
 select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.VENDOR_ATTR ;


CREATE OR REPLACE VIEW PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS.VENDOR_ATTR AS 
 select * from PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.VENDOR_ATTR where LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000';