SELECT
    CASE WHEN INV_FCST_INTER_SITE_DEMAND_KEY = - 1 THEN
        ROW_NUMBER() OVER (ORDER BY INV_FCST_INTER_SITE_DEMAND_KEY, CONCEPT_CD, ITEM_ID, LOCATION_ID,FROM_VIRTUAL_WAREHOUSE_ID,ORDER_DT) + COALESCE(MAX_INV_FCST_INTER_SITE_DEMAND_KEY, 0)
        ELSE INV_FCST_INTER_SITE_DEMAND_KEY
    END AS INV_FCST_INTER_SITE_DEMAND_KEY,
        LOCATION_KEY,
        LOCATION_ID,
        LOCATION_TYPE_CD,
        CONCEPT_CD,
        ITEM_KEY,
        ITEM_ID,
        MARKET_CD,
        INV_FCST_ITEM_PLACEHOLDER_KEY,
        INV_FCST_ITEM_PLACEHOLDER_ID,
        FROM_VIRTUAL_WAREHOUSE_KEY,
        FROM_VIRTUAL_WAREHOUSE_ID,
        FROM_VIRTUAL_WAREHOUSE_NM,
        TO_VIRTUAL_WAREHOUSE_KEY,
        TO_VIRTUAL_WAREHOUSE_ID,
        TO_VIRTUAL_WAREHOUSE_NM,
        SHIP_NODE_KEY,
        SHIP_NODE_ID,
        FIRST_EFFECTIVE_TS,
        LAST_EFFECTIVE_TS,
        PARENT_ITEM_PLACEHOLDER_CD,
        ITEM_PLACEHOLDER_DESC,
        ITEM_PLACEHOLDER_DEPT_DESC,
        ORDER_QTY,
        ORDER_DT,
        ESTIMATED_DELIVERY_DT,
        INSERT_TS,
        UPDATE_TS FROM STG_TEMP_INV_FCST_INTER_SITE_DEMAND 
 CROSS JOIN (
   SELECT
       MAX(INV_FCST_INTER_SITE_DEMAND_KEY) AS MAX_INV_FCST_INTER_SITE_DEMAND_KEY
   FROM
      L2_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND
   WHERE
      INV_FCST_INTER_SITE_DEMAND_KEY <> - 1
  ) TGT_MAX