MERGE INTO L2_ANALYTICS_TABLES.INV_FCST_INTER_SITE_DEMAND TARGET
 USING (
    SELECT STG.INV_FCST_INTER_SITE_DEMAND_KEY as MERGE_KEY, STG.*
    FROM L2_STAGE.INV_FCST_INTER_SITE_DEMAND_STG STG
    UNION
    SELECT NULL as MERGE_KEY, STG1.*
    FROM L2_STAGE.INV_FCST_INTER_SITE_DEMAND_STG STG1
    ) STG2 
    ON TARGET.INV_FCST_INTER_SITE_DEMAND_KEY = STG2.MERGE_KEY
    WHEN MATCHED AND TARGET.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000' 
    THEN
        UPDATE SET 
        TARGET.LAST_EFFECTIVE_TS = FROM_UNIXTIME(CAST(STG2.FIRST_EFFECTIVE_TS AS LONG) - 1),
        TARGET.UPDATE_TS = STG2.UPDATE_TS
    WHEN NOT MATCHED AND MERGE_KEY IS NULL 
    THEN
        INSERT (INV_FCST_INTER_SITE_DEMAND_KEY,
        LOCATION_KEY,
        LOCATION_ID,
        LOCATION_TYPE_CD,
        CONCEPT_CD,
        ITEM_KEY,
        ITEM_ID,
        MARKET_CD,
        INV_FCST_ITEM_PLACEHOLDER_KEY,
        INV_FCST_ITEM_PLACEHOLDER_ID,
        FROM_VIRTUAL_WAREHOUSE_KEY,
        FROM_VIRTUAL_WAREHOUSE_ID,
        FROM_VIRTUAL_WAREHOUSE_NM,
        TO_VIRTUAL_WAREHOUSE_KEY,
        TO_VIRTUAL_WAREHOUSE_ID,
        TO_VIRTUAL_WAREHOUSE_NM,
        SHIP_NODE_KEY,
        SHIP_NODE_ID,
        FIRST_EFFECTIVE_TS,
        LAST_EFFECTIVE_TS,
        PARENT_ITEM_PLACEHOLDER_CD,
        ITEM_PLACEHOLDER_DESC,
        ITEM_PLACEHOLDER_DEPT_DESC,
        ORDER_QTY,
        ORDER_DT,
        ESTIMATED_DELIVERY_DT,
        INSERT_TS,
        UPDATE_TS) 
        VALUES (STG2.INV_FCST_INTER_SITE_DEMAND_KEY,
        STG2.LOCATION_KEY,
        STG2.LOCATION_ID,
        STG2.LOCATION_TYPE_CD,
        STG2.CONCEPT_CD,
        STG2.ITEM_KEY,
        STG2.ITEM_ID,
        STG2.MARKET_CD,
        STG2.INV_FCST_ITEM_PLACEHOLDER_KEY,
        STG2.INV_FCST_ITEM_PLACEHOLDER_ID,
        STG2.FROM_VIRTUAL_WAREHOUSE_KEY,
        STG2.FROM_VIRTUAL_WAREHOUSE_ID,
        STG2.FROM_VIRTUAL_WAREHOUSE_NM,
        STG2.TO_VIRTUAL_WAREHOUSE_KEY,
        STG2.TO_VIRTUAL_WAREHOUSE_ID,
        STG2.TO_VIRTUAL_WAREHOUSE_NM,
        STG2.SHIP_NODE_KEY,
        STG2.SHIP_NODE_ID,
        STG2.FIRST_EFFECTIVE_TS,
        STG2.LAST_EFFECTIVE_TS,
        STG2.PARENT_ITEM_PLACEHOLDER_CD,
        STG2.ITEM_PLACEHOLDER_DESC,
        STG2.ITEM_PLACEHOLDER_DEPT_DESC,
        STG2.ORDER_QTY,
        STG2.ORDER_DT,
        STG2.ESTIMATED_DELIVERY_DT,
        STG2.INSERT_TS,
        STG2.UPDATE_TS)