select 
    str.INVOICE_KEY,
    str.INVOICE_ID,
    str.SOURCE_SYSTEM ,
	COALESCE(oc.ORDER_CHARGE_TRANSACTION_KEY,-1) AS ORDER_CHARGE_TRANSACTION_KEY,  /* HINATUAN CHANGE */
	str.ORDER_CHARGE_TRANSACTION_ID, /* HINATUAN CHANGE */
    str.SOURCE_INVOICE_ID , 
    str.SUB_CHANNEL_CD ,
    CASE WHEN COALESCE(str.CONCEPT_CD,oh.CONCEPT_CD) IS NULL THEN -1 ELSE COALESCE(str.CONCEPT_CD,oh.CONCEPT_CD) END as CONCEPT_CD ,
    oh.LOCATION_KEY AS LOCATION_KEY ,
    oh.LOCATION_ID  AS LOCATION_ID ,
    CAST(str.DAY_KEY AS INT) AS DAY_KEY, 
    COALESCE(str.INVOICE_DT, TO_DATE('1900-01-01', 'yyyy-MM-dd')) AS INVOICE_DT, 
    str.INVOICE_CREATE_TS , 
    COALESCE(oh.ORDER_HEADER_KEY,-1) AS ORDER_HEADER_KEY, 
    TRIM(str.ORDER_HEADER_ID) AS ORDER_HEADER_ID , 
    TRIM(str.ORDER_ID) AS ORDER_ID ,
    str.GLOBAL_TXN_ID ,
    str.FIRST_EFFECTIVE_TS , 
    str.LAST_EFFECTIVE_TS , 
    str.POS_WORKSTATION_ID ,
    str.POS_WORKSTATION_SEQ_NBR ,
    str.WSSPL_PURCHASE_ORDER_ID ,
    str.NOSALE_OVERRIDE_DT ,
    str.OVERRIDE_REASON_ID ,
    str.CASHIER_ID ,
    str.ASSOCIATE_ID  , 
    str.IS_ASSOCIATE_FLAG ,
    str.EMPLOYEE_ID , 
    str.REPLACEMENT_ORDER_FLAG,
    str.INTERNAL_FLAG,
    str.DTC_INVOICE_TYPE_CD, 
    str.DTC_INVOICE_FULFILLMENT_TYPE_CD ,
    str.DTC_INVOICE_REVISED_TYPE_CD,
    oh.TXN_TYPE_CD AS DTC_TXN_TYPE_CD , 
    str.DTC_STATUS_CD , 
    str.DTC_REFERENCE_1 , 
    str.DTC_COLLECTED_AMT , 
    str.TOTAL_QTY , 
    str.TOTAL_AMT , 
    str.CREATE_USER_ID ,
    str.CURRENCY_CD ,
    str.INSERT_TS ,
    str.UPDATE_TS 
from INV_VIEW2  str 
LEFT JOIN L2_ANALYTICS_TABLES.ORDER_HEADER oh 
on TRIM(str.ORDER_HEADER_ID) = TRIM(oh.ORDER_HEADER_ID) 
and oh.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' 
and oh.SOURCE_SYSTEM = 'STERLING_DTC' 

LEFT JOIN L2_ANALYTICS_TABLES.ORDER_CHARGE_TRANSACTION oc    /* HINATUAN CHANGES START */
on TRIM(str.ORDER_CHARGE_TRANSACTION_ID)=TRIM(oc.ORDER_CHARGE_TRANSACTION_ID)
and oc.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000'   /* HINATUAN CHANGES END */                  