SELECT 
COALESCE(TARGET.INVOICE_KEY,T1.INVOICE_KEY) AS INVOICE_KEY ,
T1.INVOICE_ID,
T1.SOURCE_SYSTEM,
T1.ORDER_CHARGE_TRANSACTION_KEY,  /* HINATUAN CHANGE */
T1.ORDER_CHARGE_TRANSACTION_ID,   /* HINATUAN CHANGE */
T1.SOURCE_INVOICE_ID,
T1.SUB_CHANNEL_CD,
T1.CONCEPT_CD,
T1.LOCATION_KEY,
T1.LOCATION_ID,
T1.DAY_KEY,
T1.INVOICE_DT,
T1.INVOICE_CREATE_TS,
T1.ORDER_HEADER_KEY,
T1.ORDER_HEADER_ID,
T1.ORDER_ID,
T1.GLOBAL_TXN_ID,
T1.FIRST_EFFECTIVE_TS,
T1.LAST_EFFECTIVE_TS,
T1.POS_WORKSTATION_ID,
T1.POS_WORKSTATION_SEQ_NBR,
T1.WSSPL_PURCHASE_ORDER_ID,
T1.NOSALE_OVERRIDE_DT,
T1.OVERRIDE_REASON_ID,
T1.CASHIER_ID,
T1.ASSOCIATE_ID,
T1.IS_ASSOCIATE_FLAG,
T1.EMPLOYEE_ID,
T1.REPLACEMENT_ORDER_FLAG,
T1.INTERNAL_FLAG,
T1.DTC_INVOICE_TYPE_CD,
T1.DTC_INVOICE_FULFILLMENT_TYPE_CD,
T1.DTC_INVOICE_REVISED_TYPE_CD,
T1.DTC_TXN_TYPE_CD,
T1.DTC_STATUS_CD,
T1.DTC_REFERENCE_1,
T1.DTC_COLLECTED_AMT,
T1.TOTAL_QTY,
T1.TOTAL_AMT,
T1.CREATE_USER_ID,
T1.CURRENCY_CD,
T1.INSERT_TS,
T1.UPDATE_TS 
FROM INV_VIEW3 T1 
LEFT JOIN L2_ANALYTICS_TABLES.INVOICE  TARGET 
ON TARGET.SOURCE_SYSTEM = 'STERLING_DTC'  
AND TRIM(TARGET.INVOICE_ID) = TRIM(T1.INVOICE_ID)  
AND TARGET.LAST_EFFECTIVE_TS = '9999-12-31T23:59:59.000+0000' 
AND T1.ORDER_HEADER_KEY <> -1 

WHERE 
(    
   COALESCE( T1.INVOICE_ID, 'NULL' ) 
|| COALESCE( T1.SOURCE_SYSTEM, 'NULL' ) 
|| COALESCE( T1.ORDER_CHARGE_TRANSACTION_KEY,'NULL')    /* HINATUAN CHANGE */
|| COALESCE( T1.ORDER_CHARGE_TRANSACTION_ID,'NULL')     /* HINATUAN CHANGE */
|| COALESCE( T1.SOURCE_INVOICE_ID, 'NULL' ) 
|| COALESCE( T1.SUB_CHANNEL_CD, 'NULL' ) 
|| COALESCE( T1.CONCEPT_CD, 'NULL' ) 
|| COALESCE( T1.LOCATION_KEY, 'NULL' ) 
|| COALESCE( T1.LOCATION_ID, 'NULL' ) 
|| COALESCE( T1.DAY_KEY, 'NULL' ) 
|| COALESCE( T1.INVOICE_DT, 'NULL' ) 
|| COALESCE( T1.INVOICE_CREATE_TS, 'NULL' ) 
|| COALESCE( T1.ORDER_HEADER_KEY, 'NULL' ) 
|| COALESCE( T1.ORDER_HEADER_ID, 'NULL' ) 
|| COALESCE( T1.ORDER_ID, 'NULL' ) 
|| COALESCE( T1.GLOBAL_TXN_ID, 'NULL' ) 
|| COALESCE( T1.FIRST_EFFECTIVE_TS, 'NULL' ) 
|| COALESCE( T1.LAST_EFFECTIVE_TS, 'NULL' ) 
|| COALESCE( T1.POS_WORKSTATION_ID, 'NULL' ) 
|| COALESCE( T1.POS_WORKSTATION_SEQ_NBR, 'NULL' ) 
|| COALESCE( T1.WSSPL_PURCHASE_ORDER_ID, 'NULL' ) 
|| COALESCE( T1.NOSALE_OVERRIDE_DT, 'NULL' ) 
|| COALESCE( T1.OVERRIDE_REASON_ID, 'NULL' ) 
|| COALESCE( T1.CASHIER_ID, 'NULL' ) 
|| COALESCE( T1.ASSOCIATE_ID, 'NULL' ) 
|| COALESCE( T1.IS_ASSOCIATE_FLAG, 'NULL' ) 
|| COALESCE( T1.EMPLOYEE_ID, 'NULL' ) 
|| COALESCE( T1.REPLACEMENT_ORDER_FLAG, 'NULL' ) 
|| COALESCE( T1.INTERNAL_FLAG, 'NULL' ) 
|| COALESCE( T1.DTC_INVOICE_TYPE_CD, 'NULL' ) 
|| COALESCE( T1.DTC_INVOICE_FULFILLMENT_TYPE_CD, 'NULL' ) 
|| COALESCE( T1.DTC_INVOICE_REVISED_TYPE_CD, 'NULL' ) 
|| COALESCE( T1.DTC_TXN_TYPE_CD, 'NULL' ) 
|| COALESCE( T1.DTC_STATUS_CD, 'NULL' ) 
|| COALESCE( T1.DTC_REFERENCE_1, 'NULL' ) 
|| COALESCE( T1.DTC_COLLECTED_AMT, 'NULL' ) 
|| COALESCE( T1.TOTAL_QTY, 'NULL' ) 
|| COALESCE( T1.TOTAL_AMT, 'NULL' ) 
|| COALESCE( T1.CREATE_USER_ID, 'NULL' ) 
|| COALESCE( T1.CURRENCY_CD, 'NULL' ) 
<>
   COALESCE( TARGET.INVOICE_ID, 'NULL' ) 
|| COALESCE( TARGET.SOURCE_SYSTEM, 'NULL' ) 
|| COALESCE( TARGET.ORDER_CHARGE_TRANSACTION_KEY,'NULL')   /* HINATUAN CHANGE */
|| COALESCE( TARGET.ORDER_CHARGE_TRANSACTION_ID,'NULL')    /* HINATUAN CHANGE */
|| COALESCE( TARGET.SOURCE_INVOICE_ID, 'NULL' ) 
|| COALESCE( TARGET.SUB_CHANNEL_CD, 'NULL' ) 
|| COALESCE( TARGET.CONCEPT_CD, 'NULL' ) 
|| COALESCE( TARGET.LOCATION_KEY, 'NULL' ) 
|| COALESCE( TARGET.LOCATION_ID, 'NULL' ) 
|| COALESCE( TARGET.DAY_KEY, 'NULL' ) 
|| COALESCE( TARGET.INVOICE_DT, 'NULL' ) 
|| COALESCE( TARGET.INVOICE_CREATE_TS, 'NULL' ) 
|| COALESCE( TARGET.ORDER_HEADER_KEY, 'NULL' ) 
|| COALESCE( TARGET.ORDER_HEADER_ID, 'NULL' ) 
|| COALESCE( TARGET.ORDER_ID, 'NULL' ) 
|| COALESCE( TARGET.GLOBAL_TXN_ID, 'NULL' ) 
|| COALESCE( TARGET.FIRST_EFFECTIVE_TS, 'NULL' ) 
|| COALESCE( TARGET.LAST_EFFECTIVE_TS, 'NULL' ) 
|| COALESCE( TARGET.POS_WORKSTATION_ID, 'NULL' ) 
|| COALESCE( TARGET.POS_WORKSTATION_SEQ_NBR, 'NULL' ) 
|| COALESCE( TARGET.WSSPL_PURCHASE_ORDER_ID, 'NULL' ) 
|| COALESCE( TARGET.NOSALE_OVERRIDE_DT, 'NULL' ) 
|| COALESCE( TARGET.OVERRIDE_REASON_ID, 'NULL' ) 
|| COALESCE( TARGET.CASHIER_ID, 'NULL' ) 
|| COALESCE( TARGET.ASSOCIATE_ID, 'NULL' ) 
|| COALESCE( TARGET.IS_ASSOCIATE_FLAG, 'NULL' ) 
|| COALESCE( TARGET.EMPLOYEE_ID, 'NULL' ) 
|| COALESCE( TARGET.REPLACEMENT_ORDER_FLAG, 'NULL' ) 
|| COALESCE( TARGET.INTERNAL_FLAG, 'NULL' ) 
|| COALESCE( TARGET.DTC_INVOICE_TYPE_CD, 'NULL' ) 
|| COALESCE( TARGET.DTC_INVOICE_FULFILLMENT_TYPE_CD, 'NULL' ) 
|| COALESCE( TARGET.DTC_INVOICE_REVISED_TYPE_CD, 'NULL' ) 
|| COALESCE( TARGET.DTC_TXN_TYPE_CD, 'NULL' ) 
|| COALESCE( TARGET.DTC_STATUS_CD, 'NULL' ) 
|| COALESCE( TARGET.DTC_REFERENCE_1, 'NULL' ) 
|| COALESCE( TARGET.DTC_COLLECTED_AMT, 'NULL' ) 
|| COALESCE( TARGET.TOTAL_QTY, 'NULL' ) 
|| COALESCE( TARGET.TOTAL_AMT, 'NULL' ) 
|| COALESCE( TARGET.CREATE_USER_ID, 'NULL' ) 
|| COALESCE( TARGET.CURRENCY_CD, 'NULL' ) 
)
AND COALESCE( TARGET.FIRST_EFFECTIVE_TS, '1900-01-01T23:59:59.000+0000') < T1.FIRST_EFFECTIVE_TS 

