 SELECT
	 CASE WHEN INV4.INVOICE_KEY = -1 AND INV4.ORDER_HEADER_KEY <> -1 THEN dense_rank() OVER (ORDER BY INV4.INVOICE_KEY, INV4.INVOICE_ID) + MAX_INVOICE_KEY ELSE INV4.INVOICE_KEY END AS INVOICE_KEY
	,INV4.INVOICE_ID
	,INV4.SOURCE_SYSTEM
	,INV4.ORDER_CHARGE_TRANSACTION_KEY  /* HINATUAN CHANGE */
	,INV4.ORDER_CHARGE_TRANSACTION_ID   /* HINATUAN CHANGE */
	,INV4.SOURCE_INVOICE_ID
	,INV4.SUB_CHANNEL_CD
	,INV4.CONCEPT_CD
	,INV4.LOCATION_KEY
	,INV4.LOCATION_ID
	,INV4.DAY_KEY
	,INV4.INVOICE_DT
	,INV4.INVOICE_CREATE_TS
	,INV4.ORDER_HEADER_KEY
	,INV4.ORDER_HEADER_ID
	,INV4.ORDER_ID
	,INV4.GLOBAL_TXN_ID
	,INV4.FIRST_EFFECTIVE_TS
	,INV4.LAST_EFFECTIVE_TS
	,INV4.POS_WORKSTATION_ID
	,INV4.POS_WORKSTATION_SEQ_NBR
	,INV4.WSSPL_PURCHASE_ORDER_ID
	,INV4.NOSALE_OVERRIDE_DT
	,INV4.OVERRIDE_REASON_ID
	,INV4.CASHIER_ID
	,INV4.ASSOCIATE_ID
	,INV4.IS_ASSOCIATE_FLAG
	,INV4.EMPLOYEE_ID
	,INV4.REPLACEMENT_ORDER_FLAG
	,INV4.INTERNAL_FLAG
	,INV4.DTC_INVOICE_TYPE_CD
	,INV4.DTC_INVOICE_FULFILLMENT_TYPE_CD
	,INV4.DTC_INVOICE_REVISED_TYPE_CD
	,INV4.DTC_TXN_TYPE_CD
	,INV4.DTC_STATUS_CD
	,INV4.DTC_REFERENCE_1
	,INV4.DTC_COLLECTED_AMT
	,INV4.TOTAL_QTY
	,INV4.TOTAL_AMT
	,INV4.CREATE_USER_ID
	,INV4.CURRENCY_CD
	,INV4.INSERT_TS
	,INV4.UPDATE_TS 
	FROM INV_VIEW4 INV4 
	 
	CROSS JOIN ( 
    
    SELECT COALESCE(MAX(INVOICE_KEY),0) AS MAX_INVOICE_KEY FROM L2_ANALYTICS_TABLES.INVOICE WHERE INVOICE_KEY <> -1 
    
    ) TARGET_MAX   