MERGE INTO "PROD_EDAP_ANALYTICS_DB"."PROD_EDAP_ANALYTICS_TABLES"."INVOICE" TARGET USING 
 (  
 SELECT  STG1_VIEW3_1.INVOICE_KEY AS MERGE_KEY, STG1_VIEW3_1.*  
 FROM  "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INVOICE_STAGE_ODBC" STG1_VIEW3_1 
 WHERE STG1_VIEW3_1.ORDER_HEADER_KEY <> -1 
 
 UNION 
 
 SELECT  NULL AS MERGE_KEY, STG1_VIEW3_2.*  
 FROM  "PROD_EDAP_STAGE_DB"."PROD_EDAP_STAGE_TABLES"."INVOICE_STAGE_ODBC" STG1_VIEW3_2 
 WHERE STG1_VIEW3_2.ORDER_HEADER_KEY <> -1 

 ) STG1_VIEW4   
 ON TARGET.INVOICE_KEY = STG1_VIEW4.MERGE_KEY  
 
 WHEN  MATCHED AND TARGET.LAST_EFFECTIVE_TS = '9999-12-31 23:59:59.000' 
 THEN  
 UPDATE  
 SET   LAST_EFFECTIVE_TS = dateadd(SECOND, - 1, STG1_VIEW4.FIRST_EFFECTIVE_TS), UPDATE_TS = STG1_VIEW4.UPDATE_TS 
 
 WHEN   NOT MATCHED  AND MERGE_KEY IS NULL AND STG1_VIEW4.FIRST_EFFECTIVE_TS IS NOT NULL  
 THEN   
 INSERT (
	INVOICE_KEY ,
	INVOICE_ID ,
	SOURCE_SYSTEM ,
	ORDER_CHARGE_TRANSACTION_KEY,  /* HINATUAN CHANGE */
	ORDER_CHARGE_TRANSACTION_ID ,  /* HINATUAN CHANGE */
	SOURCE_INVOICE_ID ,
	SUB_CHANNEL_CD ,
	CONCEPT_CD ,
	LOCATION_KEY ,
	LOCATION_ID ,
	DAY_KEY ,
	INVOICE_DT ,
	INVOICE_CREATE_TS ,
	ORDER_HEADER_KEY ,
	ORDER_HEADER_ID ,
	ORDER_ID ,
	GLOBAL_TXN_ID ,
	FIRST_EFFECTIVE_TS ,
	LAST_EFFECTIVE_TS ,
	POS_WORKSTATION_ID ,
	POS_WORKSTATION_SEQ_NBR ,
	WSSPL_PURCHASE_ORDER_ID ,
	NOSALE_OVERRIDE_DT ,
	OVERRIDE_REASON_ID ,
	CASHIER_ID ,
	ASSOCIATE_ID ,
	IS_ASSOCIATE_FLAG ,
	EMPLOYEE_ID ,
	REPLACEMENT_ORDER_FLAG ,
	INTERNAL_FLAG ,
	DTC_INVOICE_TYPE_CD ,
	DTC_INVOICE_FULFILLMENT_TYPE_CD ,
	DTC_INVOICE_REVISED_TYPE_CD ,
	DTC_TXN_TYPE_CD ,
	DTC_STATUS_CD ,
	DTC_REFERENCE_1 ,
	DTC_COLLECTED_AMT ,
	TOTAL_QTY ,
	TOTAL_AMT ,
	CREATE_USER_ID ,
	CURRENCY_CD ,
	INSERT_TS ,
	UPDATE_TS 
  )  
VALUES    
(     
	INVOICE_KEY ,
	INVOICE_ID ,
	SOURCE_SYSTEM ,
	ORDER_CHARGE_TRANSACTION_KEY,  /* HINATUAN CHANGE */
	ORDER_CHARGE_TRANSACTION_ID ,  /* HINATUAN CHANGE */
	SOURCE_INVOICE_ID ,
	SUB_CHANNEL_CD ,
	CONCEPT_CD ,
	LOCATION_KEY ,
	LOCATION_ID ,
	DAY_KEY ,
	INVOICE_DT ,
	INVOICE_CREATE_TS ,
	ORDER_HEADER_KEY ,
	ORDER_HEADER_ID ,
	ORDER_ID ,
	GLOBAL_TXN_ID ,
	FIRST_EFFECTIVE_TS ,
	LAST_EFFECTIVE_TS ,
	POS_WORKSTATION_ID ,
	POS_WORKSTATION_SEQ_NBR ,
	WSSPL_PURCHASE_ORDER_ID ,
	NOSALE_OVERRIDE_DT ,
	OVERRIDE_REASON_ID ,
	CASHIER_ID ,
	ASSOCIATE_ID ,
	IS_ASSOCIATE_FLAG ,
	EMPLOYEE_ID ,
	REPLACEMENT_ORDER_FLAG ,
	INTERNAL_FLAG ,
	DTC_INVOICE_TYPE_CD ,
	DTC_INVOICE_FULFILLMENT_TYPE_CD ,
	DTC_INVOICE_REVISED_TYPE_CD ,
	DTC_TXN_TYPE_CD ,
	DTC_STATUS_CD ,
	DTC_REFERENCE_1 ,
	DTC_COLLECTED_AMT ,
	TOTAL_QTY ,
	TOTAL_AMT ,
	CREATE_USER_ID ,
	CURRENCY_CD ,
	INSERT_TS ,
	UPDATE_TS  
)  