-- Databricks notebook source
-- DBTITLE 1,Creating Backup Table
CREATE TABLE PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.ORDER_HOLD_2504 CLONE PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.ORDER_HOLD;

-- COMMAND ----------

-- DBTITLE 1,Checking Count
SELECT COUNT(*) FROM PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.ORDER_HOLD_2504;
SELECT COUNT(*) FROM PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.ORDER_HOLD;

-- COMMAND ----------

-- DBTITLE 1,Merge with Target Table
-- MAGIC %sql
-- MAGIC MERGE INTO PROD_EDAP_ANALYTICS_DB.PROD_EDAP_ANALYTICS_TABLES.ORDER_HOLD TGT 
-- MAGIC USING DEV_EDAP_STAGE_DB.DEV_EDAP_TDM_STAGE_TABLES.ORDER_HOLD_HIST_LOAD STG
-- MAGIC ON STG.ORDER_HOLD_ID=TGT.ORDER_HOLD_ID
-- MAGIC WHEN NOT MATCHED THEN
-- MAGIC INSERT
-- MAGIC (
-- MAGIC ORDER_HOLD_KEY  ,
-- MAGIC 	ORDER_HOLD_ID  ,
-- MAGIC 	SOURCE_SYSTEM  ,
-- MAGIC 	ORDER_HEADER_KEY  ,
-- MAGIC 	ORDER_HEADER_ID  ,
-- MAGIC 	ORDER_LINE_KEY  ,
-- MAGIC 	ORDER_LINE_ID  ,
-- MAGIC 	HOLD_TYPE_KEY  ,
-- MAGIC 	HOLD_TYPE_ID ,
-- MAGIC 	HOLD_TYPE_CD ,
-- MAGIC 	DOCUMENT_TYPE_CD ,
-- MAGIC 	ORDER_AUDIT_KEY  ,
-- MAGIC 	ORDER_AUDIT_ID ,
-- MAGIC 	FIRST_EFFECTIVE_TS  ,
-- MAGIC 	LAST_EFFECTIVE_TS  ,
-- MAGIC 	LAST_HOLD_TYPE_TS  ,
-- MAGIC 	ORDER_HOLD_TYPE_TXN_ID ,
-- MAGIC 	ORDER_HOLD_TYPE_STATUS ,
-- MAGIC 	ORDER_HOLD_TYPE_REASON ,
-- MAGIC 	CREATE_TS  ,
-- MAGIC 	CREATE_USER_ID ,
-- MAGIC 	CREATE_PROG_ID ,
-- MAGIC 	RESOLVER_USER_ID ,
-- MAGIC 	MODIFY_TS ,
-- MAGIC 	MODIFY_USER_ID ,
-- MAGIC 	MODIFY_PROG_ID ,
-- MAGIC 	LOCK_ID,
-- MAGIC     INSERT_TS,
-- MAGIC     UPDATE_TS
-- MAGIC )
-- MAGIC VALUES
-- MAGIC (
-- MAGIC     STG.ORDER_HOLD_KEY  ,
-- MAGIC 	STG.ORDER_HOLD_ID  ,
-- MAGIC 	STG.SOURCE_SYSTEM  ,
-- MAGIC 	STG.ORDER_HEADER_KEY  ,
-- MAGIC 	STG.ORDER_HEADER_ID  ,
-- MAGIC 	STG.ORDER_LINE_KEY  ,
-- MAGIC 	STG.ORDER_LINE_ID  ,
-- MAGIC 	STG.HOLD_TYPE_KEY  ,
-- MAGIC 	STG.HOLD_TYPE_ID ,
-- MAGIC 	STG.HOLD_TYPE_CD ,
-- MAGIC 	STG.DOCUMENT_TYPE_CD ,
-- MAGIC 	STG.ORDER_AUDIT_KEY  ,
-- MAGIC 	STG.ORDER_AUDIT_ID ,
-- MAGIC 	STG.FIRST_EFFECTIVE_TS  ,
-- MAGIC 	STG.LAST_EFFECTIVE_TS  ,
-- MAGIC 	STG.LAST_HOLD_TYPE_TS  ,
-- MAGIC 	STG.ORDER_HOLD_TYPE_TXN_ID ,
-- MAGIC 	STG.ORDER_HOLD_TYPE_STATUS ,
-- MAGIC 	STG.ORDER_HOLD_TYPE_REASON ,
-- MAGIC 	STG.CREATE_TS  ,
-- MAGIC 	STG.CREATE_USER_ID ,
-- MAGIC 	STG.CREATE_PROG_ID ,
-- MAGIC 	STG.RESOLVER_USER_ID ,
-- MAGIC 	STG.MODIFY_TS ,
-- MAGIC 	STG.MODIFY_USER_ID ,
-- MAGIC 	STG.MODIFY_PROG_ID ,
-- MAGIC 	STG.LOCK_ID,
-- MAGIC     TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()),
-- MAGIC     TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP())
-- MAGIC )

-- COMMAND ----------

-- DBTITLE 1,Merge with Archive Table
MERGE INTO PROD_EDAP_L1_DB.PROD_EDAP_L1_TABLES.STERLING_ORDER_ORDER_HOLD_TABLE_ARCHIVE TGT 
USING DEV_EDAP_STAGE_DB.DEV_EDAP_TDM_STAGE_TABLES.ORDER_HOLD_HIST_LOAD STG
ON STG.ORDER_HOLD_ID=TGT.ORDER_HOLD_TYPE_KEY
WHEN NOT MATCHED THEN
INSERT
(
		ORDER_HOLD_TYPE_KEY,
		ORDER_HEADER_KEY,
		ORDER_LINE_KEY,
		HOLD_TYPE,
        DOCUMENT_TYPE,
        ORDER_AUDIT_KEY,
        LAST_HOLD_TYPE_DATE,
		TRANSACTION_ID,
		STATUS,
        REASON_TEXT,
        CREATETS,
        CREATEUSERID,
        CREATEPROGID,
		RESOLVER_USER_ID,
		MODIFYTS,
		MODIFYUSERID,
		MODIFYPROGID,
		LOCKID,
		INSERT_TS
)
VALUES
(
	STG.ORDER_HOLD_ID  ,
	STG.ORDER_HEADER_ID  ,
	STG.ORDER_LINE_ID  ,
	STG.HOLD_TYPE_CD ,
	STG.DOCUMENT_TYPE_CD ,
	STG.ORDER_AUDIT_ID ,
	STG.LAST_HOLD_TYPE_TS  ,
	STG.ORDER_HOLD_TYPE_TXN_ID ,
	STG.ORDER_HOLD_TYPE_STATUS ,
	STG.ORDER_HOLD_TYPE_REASON ,
	STG.CREATE_TS  ,
	STG.CREATE_USER_ID ,
	STG.CREATE_PROG_ID ,
	STG.RESOLVER_USER_ID ,
	STG.MODIFY_TS ,
	STG.MODIFY_USER_ID ,
	STG.MODIFY_PROG_ID ,
	STG.LOCK_ID,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP())
)
